---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: templateinstances.tenantoperator.stakater.com
spec:
  group: tenantoperator.stakater.com
  names:
    kind: TemplateInstance
    listKind: TemplateInstanceList
    plural: templateinstances
    singular: templateinstance
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TemplateInstance is the Schema for the templatesinstance API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TemplateInstanceSpec holds the expected cluster status of
              the template instance
            properties:
              parameters:
                description: Parameters hold the values of the defined parameters
                  in the template
                items:
                  properties:
                    name:
                      description: Name is the name of the parameter to set
                      type: string
                    value:
                      description: Value is the value of the parameter to set
                      type: string
                  type: object
                type: array
              sync:
                description: If true the template instance will keep the deployed
                  resources in sync with the template.
                type: boolean
              template:
                description: The template to instantiate. This is an immutable field
                type: string
            required:
            - template
            type: object
          status:
            description: TemplateInstanceStatus describes the current status of the
              template instance in the cluster
            properties:
              message:
                description: A human readable message indicating details about why
                  the namespace is in this condition.
                type: string
              observedAt:
                description: LastAppliedAt indicates when the template was last applied
                format: date-time
                type: string
              reason:
                description: A brief CamelCase message indicating details about why
                  the namespace is in this state.
                type: string
              status:
                description: Status holds the template instances status
                type: string
              templateHash:
                description: TemplateHash is used to ignore false-positive template
                  update events
                type: string
              templateManifests:
                description: TemplateManifests are the manifests that were rendered
                  before
                type: string
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
