apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    redhat.marketplace.com/name: ibm-metrics-operator
  name: ibm-metrics-operator-controller-manager-metrics-monitor
spec:
  endpoints:
  - bearerTokenSecret:
      key: token
      name: ibm-metrics-operator-servicemonitor-metrics-reader
    path: /metrics
    port: https
    scheme: https
  selector:
    matchLabels:
      control-plane: controller-manager
      redhat.marketplace.com/name: ibm-metrics-operator
