apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  creationTimestamp: null
  name: commoncorenetworkfunctions.ccnf.zte.com.cn
spec:
  group: ccnf.zte.com.cn
  names:
    kind: CommonCoreNetworkFunction
    listKind: CommonCoreNetworkFunctionList
    plural: commoncorenetworkfunctions
    shortNames:
    - ccnfs
    singular: commoncorenetworkfunction
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.lcm.releaseLcm
      name: LCMSTATUS
      type: string
    - jsonPath: .status.cnf.status
      name: CNFSTATUS
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: CommonCoreNetworkFunction is the Schema for the commoncorenetworkfunctions
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: CommonCoreNetworkFunctionSpec defines the desired state of
              CommonCoreNetworkFunction.
            properties:
              compute:
                properties:
                  runtimeClassHT:
                    type: string
                  runtimeClassSTD:
                    type: string
                type: object
              expert:
                properties:
                  cnfInstID:
                    type: string
                  cnfZone:
                    properties:
                      nodeLabels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  enableRtSched:
                    type: boolean
                  enableUserTipc:
                    type: boolean
                  nodeAffinity:
                    items:
                      type: string
                    type: array
                  retryTimesOnFailure:
                    properties:
                      cnfInstantiate:
                        type: integer
                    type: object
                  timeout:
                    properties:
                      cnfInstantiate:
                        additionalProperties:
                          type: integer
                        type: object
                      cnfTerminate:
                        additionalProperties:
                          type: integer
                        type: object
                      cnfUpdate:
                        additionalProperties:
                          type: integer
                        type: object
                    type: object
                type: object
              extension:
                additionalProperties:
                  type: string
                type: object
              global:
                properties:
                  bureauID:
                    type: integer
                  caasPlat:
                    type: string
                  cnfInstName:
                    type: string
                  cnfType:
                    type: string
                  configScriptCRName:
                    type: string
                  deployScenario:
                    type: string
                  nfTypeList:
                    type: string
                  nodeBasicType:
                    type: string
                  oam:
                    properties:
                      addresses:
                        items:
                          properties:
                            dduFloatIP:
                              type: string
                            floatIP:
                              type: string
                            gateway:
                              type: string
                            hostIP:
                              type: string
                          required:
                          - floatIP
                          - hostIP
                          type: object
                        type: array
                      defaultNetwork:
                        type: string
                      emsConnection:
                        properties:
                          emsIP:
                            type: string
                          localPort:
                            type: integer
                          protocol:
                            type: string
                        type: object
                      enableOamNetwork:
                        type: boolean
                      lang:
                        type: string
                      routes:
                        items:
                          properties:
                            cidr:
                              type: string
                            gateway:
                              type: string
                          required:
                          - cidr
                          - gateway
                          type: object
                        type: array
                    required:
                    - enableOamNetwork
                    - lang
                    type: object
                  updateMode:
                    type: string
                  workloadType:
                    type: string
                required:
                - bureauID
                - caasPlat
                - cnfInstName
                - cnfType
                - deployScenario
                - oam
                type: object
              network:
                properties:
                  ipvlanNetworks:
                    items:
                      properties:
                        enable:
                          type: string
                        ipamType:
                          type: string
                        key:
                          type: string
                        mtu:
                          type: integer
                        name:
                          type: string
                        physicalNetwork:
                          type: string
                        ranges:
                          items:
                            properties:
                              cidr:
                                type: string
                              gateway:
                                type: string
                              range:
                                type: string
                            required:
                            - cidr
                            type: object
                          type: array
                      required:
                      - key
                      - name
                      - physicalNetwork
                      - ranges
                      type: object
                    type: array
                  sriovNetworks:
                    items:
                      properties:
                        enable:
                          type: string
                        ipamType:
                          type: string
                        key:
                          type: string
                        mode:
                          type: string
                        mtu:
                          type: integer
                        name:
                          type: string
                        physicalNetwork:
                          type: string
                        ranges:
                          items:
                            properties:
                              cidr:
                                type: string
                              gateway:
                                type: string
                              range:
                                type: string
                            type: object
                          type: array
                        vlanID:
                          type: integer
                        vlanIDPools:
                          items:
                            properties:
                              end:
                                type: integer
                              start:
                                type: integer
                            type: object
                          type: array
                      required:
                      - key
                      - name
                      - physicalNetwork
                      type: object
                    type: array
                type: object
              security:
                properties:
                  appDpdkServiceAccount:
                    type: string
                  appServiceAccount:
                    type: string
                  authentications:
                    items:
                      properties:
                        role:
                          type: string
                        roleBinding:
                          type: string
                        securityContextConstraints:
                          type: string
                        serviceAccount:
                          type: string
                      required:
                      - role
                      - roleBinding
                      - serviceAccount
                      type: object
                    type: array
                  imagePullSecret:
                    type: string
                  imagePushSecret:
                    type: string
                  lcmServiceAccount:
                    type: string
                required:
                - authentications
                - lcmServiceAccount
                type: object
              storage:
                properties:
                  storageClassName:
                    type: string
                required:
                - storageClassName
                type: object
              version:
                properties:
                  catalog:
                    type: string
                  imageRegistry:
                    type: string
                required:
                - imageRegistry
                type: object
            required:
            - global
            - security
            - storage
            - version
            type: object
          status:
            description: CommonCoreNetworkFunctionStatus defines the observed state
              of CommonCoreNetworkFunction.
            properties:
              cnf:
                properties:
                  status:
                    type: string
                type: object
              cnfIndex:
                type: integer
              conditions:
                items:
                  description: |-
                    Condition represents the state of the operator's
                    reconciliation functionality.
                  properties:
                    lastHeartbeatTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      description: ConditionType is the state of the operator's reconciliation
                        functionality.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              lcm:
                properties:
                  ccnfcatalogStartTime:
                    type: string
                  ccnflcmStartTime:
                    type: string
                  etcdStartTime:
                    type: string
                  registrySecret:
                    type: string
                  releaseCatalog:
                    type: string
                  releaseETCD:
                    type: string
                  releaseLcm:
                    type: string
                type: object
              retryTimesOnFailure:
                properties:
                  cnfInstantiate:
                    type: integer
                type: object
              sessionInfo:
                properties:
                  lastInstantiateSessionID:
                    type: string
                  lastTerminateSessionID:
                    type: string
                  lastUpdateSessionID:
                    type: string
                  sessionNamespace:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
