apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnf-operator
  name: cnf-operator-commoncorenetworkfunctionoperation-editor-role
rules:
- apiGroups:
  - ccnf.zte.com.cn
  resources:
  - commoncorenetworkfunctionoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ccnf.zte.com.cn
  resources:
  - commoncorenetworkfunctionoperations/status
  verbs:
  - get
