apiVersion: v1
data:
  tls.crt: TFMwdExTMUNSVWQuLi50Q2c9PQ==
  tls.key: TFMwdExTMUNSVWQuLi4wdExRbz0=
kind: Secret
metadata:
  labels:
    control-plane: controller-manager
    tlsState: noReady
  name: cnf-operator-webhook-cert-secret
type: kubernetes.io/tls
