apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnf-operator
  name: cnf-operator-commoncorenetworkfunctionbackuprestore-editor-role
rules:
- apiGroups:
  - ccnf.zte.com.cn
  resources:
  - commoncorenetworkfunctionbackuprestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ccnf.zte.com.cn
  resources:
  - commoncorenetworkfunctionbackuprestores/status
  verbs:
  - get
