apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  creationTimestamp: null
  name: demos.deployments.netai.tech
spec:
  group: deployments.netai.tech
  names:
    kind: Demo
    listKind: DemoList
    plural: demos
    singular: demo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Demo is the Schema for the Demos API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DemoSpec defines the desired state of Demo
            properties:
              antennas:
                items:
                  description: |-
                    NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
                    Important: Run "make" to regenerate code after modifying this file
                  properties:
                    carriers:
                      type: integer
                    id:
                      type: integer
                  required:
                  - carriers
                  - id
                  type: object
                type: array
              base_url:
                type: string
              data_dump:
                default: '{"forecast_model_throughput":[[1,2,3],[1,2,3]],"future_groundtruth_throughput":[[1,2,3],[1,2,3]],"historical_groundtruth_throughput":[[1,2,3],[1,2,3]],"historical_model_throughput":[[1,2,3],[1,2,3]],"legacy_energy_consumption":123.4,"legacy_power_consumption":[1,2,3],"model_carrier_allocation":[[2,2,2],[2,2,2]],"model_energy_consumption":123,"model_power_consumption":[1,2,3],"optimal_carrier_allocation":[[2,1,0],[1,1,2]],"optimal_energy_consumption":123,"optimal_power_consumption":[1,2,3],"timestep":16}'
                type: string
              last_updated:
                format: int64
                type: integer
              sub_domains:
                items:
                  type: string
                type: array
              version:
                type: string
            required:
            - antennas
            - base_url
            - last_updated
            - sub_domains
            - version
            type: object
          status:
            description: DemoStatus defines the observed state of Demo
            properties:
              antennas:
                items:
                  description: |-
                    NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
                    Important: Run "make" to regenerate code after modifying this file
                  properties:
                    carriers:
                      type: integer
                    id:
                      type: integer
                  required:
                  - carriers
                  - id
                  type: object
                type: array
              last_updated:
                format: int64
                type: integer
            required:
            - antennas
            - last_updated
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
