---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.nsx.vmware.com/v1",
          "kind": "NcpInstall",
          "metadata": {
            "name": "ncp-install",
            "namespace": "nsx-system-operator"
          },
          "spec": {
            "ncpReplicas": 1
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Networking, Security
    certified: "True"
    containerImage: kobisamoray/nsx-container-plugin-operator@sha256:5b793de5665a19c62bada4f51ab0e21255c384742f73e9b9fdf366d09155015a
    description: An operator which provides NSX as default network for an Openshift
      cluster. Simplifies the process of installing and upgrading the NSX Container
      plugin (NCP) components running in an Openshift cluster. The operator also allows
      for detailed monitoring of NCP components and reacts to configuration changes.
      This is a cluster operator and must be installed upon cluster creation; for
      more information please refer to install-time instructions.
    marketplace.openshift.io/action-text: install-time Instructions
    marketplace.openshift.io/remote-workflow: https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.1/ncp-openshift/GUID-1D75FE92-051C-4E30-8903-AF832E854AA7.html
    repository: https://github.com/vmware/nsx-container-plugin/operator
    support: VMware
  name: nsx-container-plugin-operator.v4.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NcpInstall is the Schema for the ncpinstalls API
      displayName: NcpInstall
      kind: NcpInstall
      name: ncpinstalls.operator.nsx.vmware.com
      resources:
      - kind: Deployment
        name: A Kubernetes Deployment for the Operator
        version: v1
      - kind: Configmap
        name: A Configmap with parameter for setting up Operands
        version: v1
      - kind: NcpInstall
        name: this operator's CR
        version: v1
      - kind: ClusterOperator
        name: nsx-ncp cluster operator
        version: v1
      - kind: Network
        name: Openshift's cluster network
        version: v1
      - kind: Daemonset
        name: A Daemonset
        version: v1
      - kind: Pod
        name: A Pod
        version: v1
      - kind: Secret
        name: It's a secret, I can't tell you
        version: v1
      - kind: Node
        name: A Kubernetes Node
        version: v1
      - kind: Status
        name: A Kubernetes resource status
        version: v1
      specDescriptors:
      - description: the replica numbers for the nsx-ncp deployment
        path: ncpReplicas
      statusDescriptors:
      - description: standard conditions field for Kubernetes resources
        path: conditions
      version: v1
  description: An operator which provides NSX as default network for an Openshit cluster.
    Simplifies the process of installing and upgrading the NSX Container plugin (NCP)
    components running in the Openshift cluster. The operator also allows for detailed
    monitoring of NCP components and reacts to configuration changes.
  displayName: NSX Container Plugin Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          - namespaces
          - serviceaccounts
          - secrets
          - nodes/status
          verbs:
          - create
          - get
          - list
          - patch
          - delete
          - update
          - watch
          - deletecollection
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - networks
          - networks/finalizers
          verbs:
          - get
          - list
          - watch
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          verbs:
          - create
          - get
          - list
          - patch
          - delete
          - update
          - watch
        - apiGroups:
          - config.openshift.io
          - apiextensions.k8s.io
          resources:
          - clusteroperators
          - clusteroperators/status
          - customresourcedefinitions
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
        - apiGroups:
          - operator.nsx.vmware.com
          resources:
          - ncpinstalls
          - ncpinstalls/status
          verbs:
          - get
          - list
          - watch
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - endpoints
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - extensions
          - networking.k8s.io
          - config.openshift.io
          - apps
          resources:
          - deployments
          - endpoints
          - pods/log
          - nodes
          - replicationcontrollers
          - secrets
          - ingressclasses
          - routes
          - network
          - networks
          - statefulsets
          verbs:
          - get
          - watch
          - list
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - get
          - watch
          - list
        - apiGroups:
          - ""
          - extensions
          - networking.k8s.io
          - apps
          resources:
          - namespaces
          - ingresses
          - services
          - pods
          - networkpolicies
          - routes
          - statefulsets
          verbs:
          - get
          - watch
          - list
          - update
          - patch
        - apiGroups:
          - nsx.vmware.com
          resources:
          - nsxerrors
          - nsxlocks
          - ncpconfigs
          verbs:
          - create
          - get
          - list
          - patch
          - delete
          - update
        - apiGroups:
          - ""
          - extensions
          - networking.k8s.io
          resources:
          - ingresses/status
          - services/status
          - routes/status
          verbs:
          - replace
          - update
          - patch
        - apiGroups:
          - config.openshift.io
          resources:
          - networks
          verbs:
          - patch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/status
          verbs:
          - patch
          - update
        - apiGroups:
          - k8s.cni.cncf.io
          resources:
          - network-attachment-definitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - vmware.com
          resources:
          - loadbalancers
          - loadbalancers/status
          - nsxlbmonitors
          - nsxlbmonitors/status
          - virtualnetworkinterfaces
          - virtualnetworkinterfaces/status
          - virtualnetworks
          - virtualnetworks/status
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - get
          - create
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - delete
        serviceAccountName: nsx-ncp-operator
      deployments:
      - name: nsx-ncp-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: nsx-ncp-operator
          template:
            metadata:
              labels:
                name: nsx-ncp-operator
                tier: nsx-networking
            spec:
              containers:
              - command:
                - /bin/bash
                - -c
                - nsx-ncp-operator --zap-time-encoding=iso8601 --metrics-server-bind-address=:8181
                env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: nsx-ncp-operator
                - name: NCP_IMAGE
                  value: nsx-ncp:latest
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                image: kobisamoray/nsx-container-plugin-operator@sha256:5b793de5665a19c62bada4f51ab0e21255c384742f73e9b9fdf366d09155015a
                imagePullPolicy: IfNotPresent
                name: nsx-ncp-operator
                volumeMounts:
                - mountPath: /host/etc/os-release
                  name: host-os-release
              hostNetwork: true
              serviceAccountName: nsx-ncp-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
              - effect: NoSchedule
                key: node-role.kubernetes.io/control-plane
              - effect: NoSchedule
                key: node.kubernetes.io/not-ready
              - effect: NoSchedule
                key: node.kubernetes.io/network-unavailable
              volumes:
              - hostPath:
                  path: /etc/os-release
                name: host-os-release
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - networking
  - security
  maintainers:
  - email: sorlando@vmware.com
    name: Salvatore Orlando
  - email: jsui@vmware.com
    name: Jianwei Sui
  - email: ksamoray@vmware.com
    name: Kobi Samoray
  maturity: alpha
  minKubeVersion: 1.20.0
  provider:
    name: VMware
  version: 4.0.1
