apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ape-local
    app.kubernetes.io/instance: csi-controller-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: ape-local-csi-driver
  name: apelocal-csi-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apelocal-csi-controller-role
subjects:
- kind: ServiceAccount
  name: apelocal-controller-manager
  namespace: apelocal-system
