# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-triliovault-config
  labels:
    app.kubernetes.io/instance: k8s-triliovault-config
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-triliovault
    app.kubernetes.io/part-of: k8s-triliovault
data:
  dataJobLimits: |-
    cpu: 1500m
    memory: 3584Mi
  metadataJobLimits: |-
    cpu: 500m
    memory: 512Mi
