apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: schemas.platform.confluent.io
spec:
  group: platform.confluent.io
  names:
    categories:
      - all
      - confluent-platform
      - confluent
    kind: Schema
    listKind: SchemaList
    plural: schemas
    shortNames:
      - schema
    singular: schema
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.format
          name: Format
          type: string
        - jsonPath: .status.id
          name: ID
          type: string
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.phase
          name: Status
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
        - jsonPath: .status.schemaRegistryEndpoint
          name: SchemaRegistryEndpoint
          priority: 1
          type: string
      name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: ""
              type: string
            kind:
              description: ""
              type: string
            metadata:
              type: object
            spec:
              description: ""
              properties:
                data:
                  description: ""
                  properties:
                    configRef:
                      description: ""
                      minLength: 1
                      type: string
                    format:
                      description: ""
                      enum:
                        - avro
                        - json
                        - protobuf
                      minLength: 1
                      type: string
                  required:
                    - configRef
                    - format
                  type: object
                name:
                  description: ""
                  maxLength: 255
                  minLength: 1
                  pattern: ^[^\\]*$
                  type: string
                schemaReferences:
                  description: ""
                  items:
                    description: ""
                    properties:
                      avro:
                        description: ""
                        properties:
                          avro:
                            description: ""
                            minLength: 1
                            type: string
                        required:
                          - avro
                        type: object
                      format:
                        description: ""
                        enum:
                          - avro
                          - json
                          - protobuf
                        minLength: 1
                        type: string
                      json:
                        description: ""
                        properties:
                          url:
                            description: ""
                            minLength: 1
                            type: string
                        required:
                          - url
                        type: object
                      protobuf:
                        description: ""
                        properties:
                          file:
                            description: ""
                            minLength: 1
                            type: string
                        required:
                          - file
                        type: object
                      subject:
                        description: ""
                        minLength: 1
                        type: string
                      version:
                        description: ""
                        format: int32
                        type: integer
                    required:
                      - format
                      - subject
                      - version
                    type: object
                  type: array
                schemaRegistryClusterRef:
                  description: ""
                  properties:
                    name:
                      description: ""
                      type: string
                    namespace:
                      description: ""
                      type: string
                  required:
                    - name
                  type: object
                schemaRegistryRest:
                  description: ""
                  properties:
                    authentication:
                      description: ""
                      properties:
                        basic:
                          description: ""
                          properties:
                            debug:
                              description: ""
                              type: boolean
                            directoryPathInContainer:
                              description: ""
                              minLength: 1
                              type: string
                            restrictedRoles:
                              description: ""
                              items:
                                type: string
                              minItems: 1
                              type: array
                            roles:
                              description: ""
                              items:
                                type: string
                              type: array
                            secretRef:
                              description: ""
                              maxLength: 30
                              minLength: 1
                              pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                              type: string
                          type: object
                        bearer:
                          description: ""
                          properties:
                            directoryPathInContainer:
                              description: ""
                              minLength: 1
                              type: string
                            secretRef:
                              description: ""
                              maxLength: 30
                              minLength: 1
                              pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                              type: string
                          type: object
                        type:
                          description: ""
                          enum:
                            - basic
                            - bearer
                            - mtls
                          type: string
                      required:
                        - type
                      type: object
                    endpoint:
                      description: ""
                      minLength: 1
                      pattern: ^https?://.*
                      type: string
                    kafkaClusterID:
                      description: ""
                      minLength: 1
                      type: string
                    tls:
                      description: ""
                      properties:
                        directoryPathInContainer:
                          description: ""
                          minLength: 1
                          type: string
                        jksPassword:
                          description: ""
                          properties:
                            secretRef:
                              description: ""
                              maxLength: 30
                              minLength: 1
                              pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                              type: string
                          required:
                            - secretRef
                          type: object
                        secretRef:
                          description: ""
                          maxLength: 30
                          minLength: 1
                          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                          type: string
                      type: object
                  type: object
              required:
                - data
              type: object
            status:
              description: ""
              properties:
                conditions:
                  description: ""
                  items:
                    description: ""
                    properties:
                      lastProbeTime:
                        description: ""
                        format: date-time
                        type: string
                      lastTransitionTime:
                        description: ""
                        format: date-time
                        type: string
                      message:
                        description: ""
                        type: string
                      reason:
                        description: ""
                        type: string
                      status:
                        description: ""
                        type: string
                      type:
                        description: ""
                        type: string
                    type: object
                  type: array
                deletedVersions:
                  description: ""
                  items:
                    format: int32
                    type: integer
                  type: array
                format:
                  description: ""
                  type: string
                id:
                  description: ""
                  format: int32
                  type: integer
                schemaReferences:
                  description: ""
                  items:
                    description: ""
                    properties:
                      avro:
                        description: ""
                        properties:
                          avro:
                            description: ""
                            minLength: 1
                            type: string
                        required:
                          - avro
                        type: object
                      format:
                        description: ""
                        enum:
                          - avro
                          - json
                          - protobuf
                        minLength: 1
                        type: string
                      json:
                        description: ""
                        properties:
                          url:
                            description: ""
                            minLength: 1
                            type: string
                        required:
                          - url
                        type: object
                      protobuf:
                        description: ""
                        properties:
                          file:
                            description: ""
                            minLength: 1
                            type: string
                        required:
                          - file
                        type: object
                      subject:
                        description: ""
                        minLength: 1
                        type: string
                      version:
                        description: ""
                        format: int32
                        type: integer
                    required:
                      - format
                      - subject
                      - version
                    type: object
                  type: array
                schemaRegistryAuthenticationType:
                  description: ""
                  type: string
                schemaRegistryEndpoint:
                  description: ""
                  type: string
                schemaRegistryTLS:
                  description: ""
                  type: boolean
                softDeletedVersions:
                  description: ""
                  items:
                    format: int32
                    type: integer
                  type: array
                state:
                  description: ""
                  type: string
                subject:
                  description: ""
                  type: string
                version:
                  description: ""
                  format: int32
                  type: integer
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
