apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "app.terraform.io/v1alpha2",
          "kind": "AgentPool",
          "metadata": {
            "name": "NAME"
          },
          "spec": {
            "agentTokens": [
              {
                "name": "token"
              }
            ],
            "name": "NAME",
            "organization": "HCP_TF_ORG_NAME",
            "token": {
              "secretKeyRef": {
                "key": "SECRET_KEY",
                "name": "SECRET_NAME"
              }
            }
          }
        },
        {
          "apiVersion": "app.terraform.io/v1alpha2",
          "kind": "AgentToken",
          "metadata": {
            "name": "NAME"
          },
          "spec": {
            "agentPool": {
              "name": "AGENT_POOL_NAME"
            },
            "agentTokens": [
              {
                "name": "token-a"
              },
              {
                "name": "token-b"
              }
            ],
            "deletionPolicy": "destroy",
            "managementPolicy": "merge",
            "organization": "HCP_TF_ORG_NAME",
            "secretName": "SECRET_NAME",
            "token": {
              "secretKeyRef": {
                "key": "SECRET_KEY",
                "name": "SECRET_NAME"
              }
            }
          }
        },
        {
          "apiVersion": "app.terraform.io/v1alpha2",
          "kind": "Module",
          "metadata": {
            "name": "NAME"
          },
          "spec": {
            "module": {
              "source": "redeux/terraform-cloud-agent/kubernetes",
              "version": "1.0.1"
            },
            "organization": "HCP_TF_ORG_NAME",
            "token": {
              "secretKeyRef": {
                "key": "SECRET_KEY",
                "name": "SECRET_NAME"
              }
            },
            "workspace": {
              "id": "WORKSPACE_ID"
            }
          }
        },
        {
          "apiVersion": "app.terraform.io/v1alpha2",
          "kind": "Project",
          "metadata": {
            "name": "NAME"
          },
          "spec": {
            "name": "NAME",
            "organization": "HCP_TF_ORG_NAME",
            "token": {
              "secretKeyRef": {
                "key": "SECRET_KEY",
                "name": "SECRET_NAME"
              }
            }
          }
        },
        {
          "apiVersion": "app.terraform.io/v1alpha2",
          "kind": "RunsCollector",
          "metadata": {
            "name": "NAME"
          },
          "spec": {
            "agentPool": {
              "name": "AGENT_POOL_NAME"
            },
            "organization": "HCP_TF_ORG_NAME",
            "token": {
              "secretKeyRef": {
                "key": "SECRET_KEY",
                "name": "SECRET_NAME"
              }
            }
          }
        },
        {
          "apiVersion": "app.terraform.io/v1alpha2",
          "kind": "Workspace",
          "metadata": {
            "name": "NAME"
          },
          "spec": {
            "name": "NAME",
            "organization": "HCP_TF_ORG_NAME",
            "token": {
              "secretKeyRef": {
                "key": "SECRET_KEY",
                "name": "SECRET_NAME"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Integration & Delivery
    containerImage: registry.connect.redhat.com/hashicorp/hcp-terraform-operator@sha256:a80e83e7b6c08783e89be972588d5c24a6f9efafeb66eb63a3dd490642857c91
    createdAt: "2025-12-22T09:35:34Z"
    description: HCP Terraform Operator for Kubernetes allows managing HCP Terraform / Terraform Enterprise resources via Kubernetes Custom Resources.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: Valid HCP Terraform / Terraform Enterprise subscription is required
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    repository: https://github.com/hashicorp/hcp-terraform-operator
    support: HashiCorp
  name: hcp-terraform-operator.v2.11.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: |-
          AgentPool manages HCP Terraform Agent Pools, HCP Terraform Agent Tokens and can perform HCP Terraform Agent scaling.
          More infromation:
            - https://developer.hashicorp.com/terraform/cloud-docs/agents/agent-pools
            - https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#agent-api-tokens
            - https://developer.hashicorp.com/terraform/cloud-docs/agents
        displayName: Agent Pool
        kind: AgentPool
        name: agentpools.app.terraform.io
        version: v1alpha2
      - description: |-
          AgentToken manages HCP Terraform Agent Tokens.
          More information:
          - https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens#agent-api-tokens
        displayName: Agent Token
        kind: AgentToken
        name: agenttokens.app.terraform.io
        version: v1alpha2
      - description: |-
          Module implements API-driven Run Workflows.
          More information:
            - https://developer.hashicorp.com/terraform/cloud-docs/run/api
        displayName: Module
        kind: Module
        name: modules.app.terraform.io
        version: v1alpha2
      - description: |-
          Project manages HCP Terraform Projects.
          More information:
            - https://developer.hashicorp.com/terraform/cloud-docs/projects/manage
        displayName: Project
        kind: Project
        name: projects.app.terraform.io
        version: v1alpha2
      - description: |-
          RunsCollector scraptes HCP Terraform Run statuses from a given Agent Pool and exposes them as Prometheus-compatible metrics.
          More information:
            - https://developer.hashicorp.com/terraform/cloud-docs/run/remote-operations
        displayName: Runs Collector
        kind: RunsCollector
        name: runscollectors.app.terraform.io
        version: v1alpha2
      - description: |-
          Workspace manages HCP Terraform Workspaces.
          More information:
            - https://developer.hashicorp.com/terraform/cloud-docs/workspaces
        displayName: Workspace
        kind: Workspace
        name: workspaces.app.terraform.io
        version: v1alpha2
  description: HCP Terraform Operator for Kubernetes allows managing HCP Terraform / Terraform Enterprise resources via Kubernetes Custom Resources.
  displayName: HCP Terraform Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iTG9nb3MiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDY1Ljk3IDY1Ljk3Ij4KICA8ZGVmcz4KICAgIDxzdHlsZT4KICAgICAgLmNscy0xLCAuY2xzLTIgewogICAgICAgIGZpbGw6ICM3YjQyYmM7CiAgICAgICAgc3Ryb2tlLXdpZHRoOiAwcHg7CiAgICAgIH0KCiAgICAgIC5jbHMtMiB7CiAgICAgICAgZmlsbC1ydWxlOiBldmVub2RkOwogICAgICB9CiAgICA8L3N0eWxlPgogIDwvZGVmcz4KICA8cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0yNy42MSwxOS45MWwxMC43LDYuMnYxMi40bC0xMC43LTYuMnYtMTIuNFoiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0zOS41MSwyNi4xMXYxMi40bDEwLjctNi4ydi0xMi40bC0xMC43LDYuMloiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNS44MSwxMy4wMXYxMi40bDEwLjcsNi4ydi0xMi40bC0xMC43LTYuMloiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0yNy42MSw0Ni4wMWwxMC43LDYuMnYtMTIuNGwtMTAuNy02LjJ2MTIuNFoiLz4KICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik01Ny4xNyw2NS45N0g4LjhjLTEuNTYsMC0yLjcsMC0zLjYxLS4wNy0uOTYtLjA4LTEuNjItLjI0LTIuMTgtLjUyLTEuMDQtLjUzLTEuODctMS4zNi0yLjQtMi40LS4yOS0uNTctLjQ1LTEuMjItLjUyLTIuMTgtLjA3LS45Mi0uMDctMi4wNS0uMDctMy42MVY4LjhjMC0xLjU2LDAtMi42OS4wNy0zLjYxLjA4LS45Ni4yNC0xLjYyLjUyLTIuMThDMS4xMywxLjk2LDEuOTYsMS4xMywzLC42Yy41Ny0uMjksMS4yMi0uNDUsMi4xOC0uNTIuOTItLjA3LDIuMDUtLjA3LDMuNjEtLjA3aDQ4LjM4YzEuNTYsMCwyLjY5LDAsMy42MS4wNy45Ni4wOCwxLjYyLjI0LDIuMTguNTIsMS4wNC41MywxLjg3LDEuMzYsMi40LDIuNC4yOS41Ny40NSwxLjIyLjUyLDIuMTguMDcuOTIuMDcsMi4wNS4wNywzLjYxdjQ4LjM4YzAsMS41NiwwLDIuNy0uMDcsMy42MS0uMDguOTctLjI0LDEuNjItLjUyLDIuMTgtLjUzLDEuMDQtMS4zNiwxLjg3LTIuNCwyLjQtLjU3LjI5LTEuMjIuNDUtMi4xOC41Mi0uOTIuMDctMi4wNS4wNy0zLjYxLjA3Wk04LjgsMi43NWMtMS41LDAtMi41OCwwLTMuMzkuMDctLjU2LjA1LS45NC4xMi0xLjE2LjIzLS41Mi4yNy0uOTQuNjgtMS4yLDEuMi0uMTEuMjItLjE5LjYtLjIzLDEuMTYtLjA3LjgxLS4wNywxLjg5LS4wNywzLjM5djQ4LjM4YzAsMS40NCwwLDIuNTguMDcsMy4zOS4wNS41Ni4xMi45NC4yMywxLjE2LjI3LjUyLjY4Ljk0LDEuMiwxLjIuMjIuMTEuNi4xOSwxLjE2LjIzLjguMDcsMS44OS4wNywzLjM5LjA3aDQ4LjM4YzEuNSwwLDIuNTgsMCwzLjM5LS4wNy41Ni0uMDUuOTQtLjEyLDEuMTYtLjIzLjUyLS4yNy45NC0uNjgsMS4yLTEuMi4xMS0uMjIuMTktLjYuMjMtMS4xNi4wNy0uOC4wNy0xLjg5LjA3LTMuMzlWOC44YzAtMS41LDAtMi41OC0uMDctMy4zOS0uMDUtLjU2LS4xMi0uOTQtLjIzLTEuMTYtLjI3LS41Mi0uNjgtLjk0LTEuMi0xLjItLjIyLS4xMS0uNi0uMTktMS4xNi0uMjMtLjgxLS4wNy0xLjk0LS4wNy0zLjM5LS4wN0g4LjhaIi8+Cjwvc3ZnPg==
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
                - secrets
              verbs:
                - create
                - list
                - update
                - watch
                - patch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - app.terraform.io
              resources:
                - agentpools
                - agenttokens
                - modules
                - projects
                - runscollectors
                - workspaces
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - app.terraform.io
              resources:
                - agentpools/finalizers
                - agenttokens/finalizers
                - modules/finalizers
                - projects/finalizers
                - runscollectors/finalizers
                - workspaces/finalizers
              verbs:
                - update
            - apiGroups:
                - app.terraform.io
              resources:
                - agentpools/status
                - agenttokens/status
                - modules/status
                - projects/status
                - runscollectors/status
                - workspaces/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
          serviceAccountName: hcp-terraform-operator-manager
      deployments:
        - label:
            app.kubernetes.io/name: hcp-terraform-operator
            control-plane: controller-manager
          name: hcp-terraform-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:c8336efb1269a7f40113aa9767c6dc9affe4fd830a1ca6004206bcef1d0274a3
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                  - args:
                      - --sync-period=5m
                      - --agent-pool-workers=1
                      - --agent-pool-sync-period=30s
                      - --agent-token-workers=1
                      - --agent-token-sync-period=30s
                      - --module-workers=1
                      - --module-sync-period=5m
                      - --project-workers=1
                      - --project-sync-period=5m
                      - --runs-collector-workers=1
                      - --runs-collector-sync-period=15s
                      - --workspace-workers=1
                      - --workspace-sync-period=5m
                    command:
                      - /manager
                    image: registry.connect.redhat.com/hashicorp/hcp-terraform-operator@sha256:a80e83e7b6c08783e89be972588d5c24a6f9efafeb66eb63a3dd490642857c91
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 50m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                      seccompProfile:
                        type: RuntimeDefault
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: hcp-terraform-operator-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: hcp-terraform-operator-manager
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - terraform
  links:
    - name: HCP Terraform Operator
      url: https://github.com/hashicorp/hcp-terraform-operator
  maintainers:
    - email: hcp-tf-operator@hashicorp.com
      name: HashiCorp
  maturity: alpha
  minKubeVersion: 1.24.0
  provider:
    name: HashiCorp
    url: https://www.hashicorp.com/
  relatedImages:
    - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:c8336efb1269a7f40113aa9767c6dc9affe4fd830a1ca6004206bcef1d0274a3
      name: kube-rbac-proxy
    - image: registry.connect.redhat.com/hashicorp/hcp-terraform-operator@sha256:a80e83e7b6c08783e89be972588d5c24a6f9efafeb66eb63a3dd490642857c91
      name: manager
  replaces: hcp-terraform-operator.v2.9.2
  version: 2.11.0
