apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-mteric-state-mdef-editor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redhat-marketplace-meterdefinition-editor-role
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-metric-state
  namespace: openshift-redhat-marketplace
