---
apiVersion: v1
kind: Service
metadata:
  annotations:
    infoscale.veritas.com/certificate: iso-webhook-cert
  creationTimestamp: null
  name: iso-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: infoscale-operator
status:
  loadBalancer: {}
