---
# The catalog for intended distribution.
# Can be either "certified-operators" or "redhat-marketplace"
organization: certified-operators

# tests to ignore for certain partners (until static checker's bugs are fixed):
tests:
  - name: check_operator_name
    ignore_operators:
      - ^vfunction-server-operator
      - ^kubeturbo-certified
      - ^prometurbo-certified
      - ^t8c-certified
  - name: check_replaces_availability
    ignore_operators:
      - ^vfunction-server-operator
  - name: check_upgrade_graph_loop
    ignore_operators:
      - ^vfunction-server-operator
