---
# Source: nifi-operator/templates/configmap.yaml
apiVersion: v1
data:
  properties.yaml: |
    version: 0.1.0
    spec:
      units: []

    properties:
      - property:
          propertyNames:
            - name: "networkaddress.cache.ttl"
              kind:
                type: "file"
                file: "security.properties"
          datatype:
            type: "integer"
            min: "0"
          recommendedValues:
            - fromVersion: "0.0.0"
              value: "30"
          roles:
            - name: "node"
              required: true
          asOfVersion: "0.0.0"
          comment: "TTL for successfully resolved domain names."
          description: "TTL for successfully resolved domain names."

      - property:
          propertyNames:
            - name: "networkaddress.cache.negative.ttl"
              kind:
                type: "file"
                file: "security.properties"
          datatype:
            type: "integer"
            min: "0"
          recommendedValues:
            - fromVersion: "0.0.0"
              value: "0"
          roles:
            - name: "node"
              required: true
          asOfVersion: "0.0.0"
          comment: "TTL for host names that cannot be resolved."
          description: "TTL for host names that cannot be resolved."
kind: ConfigMap
metadata:
  name: nifi-operator-configmap
  labels:
    helm.sh/chart: nifi-operator-0.0.0-dev
    app.kubernetes.io/name: nifi-operator
    app.kubernetes.io/instance: nifi-operator
    app.kubernetes.io/version: "0.0.0-dev"
    app.kubernetes.io/managed-by: Helm
