---
apiVersion: v1
data:
  properties.yaml: |
    ---
    version: 0.1.0
    spec:
      units: []

    properties: []
kind: ConfigMap
metadata:
  name: nifi-operator-configmap
  labels:
    app.kubernetes.io/name: nifi-operator
    app.kubernetes.io/instance: nifi-operator
    app.kubernetes.io/version: "23.4.0"
