# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: v1
data:
  OPERATOR_NAME: '"splunk-operator"'
  RELATED_IMAGE_SPLUNK_ENTERPRISE: ""
  WATCH_NAMESPACE: ""
kind: ConfigMap
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-config
