---
# Source: kurrentdb-operator/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kurrentdb-operator
  annotations:
  labels:
    app.kubernetes.io/created-by: kurrent
    app.kubernetes.io/part-of: kurrentdb-operator
data:
  config.yaml: |-
    logging:
      level: info
    license:
      secretName: kurrentdb-operator
    dnsImage: registry.connect.redhat.com/kurrent-io/dns@sha256:07e8771886b4e4ab7393dee7a56c4a6d2c2225ba0aeca25e47199da616c903e4
