apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: infinidat-csi-operator-infinidat-iboxpromote-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infinidat-csi-operator-infinidat-iboxpromote-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: infinidat-csi-operator-infinidat-csi-controller
  namespace: infinidat-csi
