apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: infinidat-csi-operator-infinidat-iboxpromote-controller
rules:
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxpromotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxpromotes/finalizers
  verbs:
  - update
- apiGroups:
  - csidriver.infinidat.com
  resources:
  - iboxpromotes/status
  verbs:
  - get
  - patch
  - update
