---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"xcrypt.zettaset.com/v1alpha1\",\n\
      \    \"kind\": \"XCrypt\",\n    \"metadata\": {\n      \"name\": \"zts-masterset\"\
      \n    },\n    \"spec\": {\n      \"status\": {\n        \"podNames\": \"zts-ca\"\
      ,\n        \"replicas\": \"1,\"\n      }\n    }\n  }\n]"
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: zts-xcrypt
    categories: Security
    certified: 'false'
    containerImage: registry.connect.redhat.com/zts/xcrypt-operator-1@sha256:592d8522747cebcc101dd6b6a67e352474c85559e04a690f9b2695b9222cdd5f
    createdAt: '2021-11-08T23:29:58.032799898Z'
    description: XCrypt Operator deploys Zettaset XCrypt Container Encryption  - the
      only software-defined solution that offers transparent high performance data-at-rest
      encryption of critical data in container environments.
    support: Zettaset
  creationTimestamp: null
  name: zts-xcrypt-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: XCrypt is the Schema for the xcrypts API
      kind: XCrypt
      name: xcrypts.xcrypt.zettaset.com
      version: v1alpha1
  description: |-
    Zettaset’s RedHat Certified XCrypt Operator allows users to deploy multiple XCrypt components on OpenShift with just a few simple commands. The XCrypt Operator deployment provides software-defined encryption that transparently protects container data throughout your OpenShift environment.

    ## Core Features
    * **Automated XCrypt provisioning** - Deploying a Zettaset XCrypt has never been easier. Adjust cluster specific configuration and let the Zettaset Operator take care of provisioning XCrypt services and setting up the XCrypt encryption to your exact specification.
    * **CSI Driver deployment**: Zettaset XCrypt Operator automatically deploys Zettaset XCrypt CSI Driver in order to provide automated and transparent data-at-rest  encryption functionality compatible with Openshift and any other container orchestrator. Once the Operator is provisioned, the driver runs fine tuned and ready to work with other XCrypt components.
    * **Multi-node topology**: Encrypt as many nodes and volumes as you need to. XCrypt components can be installed on multiple nodes across the cluster. This is defined by two labels: zts-master and zts-worker. Normally zts-master node is a single node that runs Zettaset XCrypt major services required for the product operation. Multiple nodes can be marked as zts-worker and those are the nodes that can have encrypted volumes.
    * **Seamless Encrypted Volume mount**: Volumes are not only being encrypted, but also are mounted/unmounted to containers with Persistent Volume Claims. This happens as seamlessly as regular volumes provision and mount/unmount.
    * **Robust failover**: A node failure doesn’t affect XCrypt operations on other nodes of the cluster. Encryption on a restarted/recovered node gets back to normal functioning if the node stays healthy and data hasn’t been corrupted during the restart

    ## About Zettaset XCrypt Kubernetes Encryption for OpenShift
    XCrypt Kubernetes Encryption for OpenShift is a software-only solution that enables encryption of data at rest stored in Red Hat OpenShift container environments without slowing down the DevSecOps process. In addition to providing a transparent and high-performance layer of security that flexibly protects container data across on-premise, in hybrid, and multi-cloud environments, it also helps your organization efficiently transition from DevOps to DevSecOps.

    More information about Zettaset XCrypt Kubernetes Encryption for OpenShift can be found in the [Deployment and Administration Guide](https://1f2aca073706bb52f501-133f3466c38fdb0417539cdf095d8336.ssl.cf1.rackcdn.com/ZettasetXCryptContainerEncryption.8.5.0.Final.pdf)

    ## RedHat OpenShift + Zettaset: The next generation of secure enterprise infrastructure for DevSecOps
    By combining RedHat’s Container Platform with Zettaset’s certified software-defined encryption, you can create the next generation of secure enterprise infrastructure that DevSecOps requires. Together they create the stable, consistent, and supported base that your organization needs to develop applications faster, simplify updates, drive innovation, and reduce the risk of potential security breaches and data theft.
    ### Core Features
    * Software-only for simple and scalable deployments
    * Negligible performance impact
    * Transparent to developers and administrators
    * Works with AWS, Google, and Azure
    * Unique encryption key per container volume
    * Encrypted volumes are only available when in use
    * Direct integration with OpenShift
    * Automated encryption policy management Secure erase of volumes
    * Ability to securely decommission a node

    ## How does XCrypt Kubernetes Encryption fit into OpenShift?
    XCrypt XCrypt Kubernetes Encryption for OpenShift Encryption makes it incredibly easy to protect container data in your OpenShift environment.
    ### Use cases include:
    * Transitioning from DevOps to DevSecOps
    * Ensuring data protection in OpenShift container environments with negligible performance impact
    * Achieving compliance in regulated industries like healthcare and finance

    Role-based access control needs to be configured prior to the Operator installation. Please find details in the [Deployment and Administration Guide](https://1f2aca073706bb52f501-133f3466c38fdb0417539cdf095d8336.ssl.cf1.rackcdn.com/ZettasetXCryptContainerEncryption.8.5.0.Final.pdf)
    ## Other Information
  displayName: Zettaset XCrypt Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAyMzQgNjMiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDIzNCA2MzsiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCgkuc3Qwe2ZpbGw6IzAwOUJEQTt9DQoJLnN0MXtmaWxsOiNGNzkwMUU7fQ0KCS5zdDJ7ZmlsbDojMEEzQTZFO30NCjwvc3R5bGU+DQo8Zz4NCgk8Zz4NCgkJPHBhdGggY2xhc3M9InN0MCIgZD0iTTI5LDIyLjZjMywwLjQsNS41LDIuNCw2LjUsNS4xbDcuNy05LjR2LTcuOEgxM3Y3LjhoMTkuNUwyOSwyMi42eiIvPg0KCQk8Y2lyY2xlIGNsYXNzPSJzdDEiIGN4PSIyOCIgY3k9IjMwLjYiIHI9IjYuMSIvPg0KCTwvZz4NCgk8cGF0aCBjbGFzcz0ic3QwIiBkPSJNNDUuMSw0Mi40SDIzLjNsMy4xLTMuOGMtMy0wLjUtNS40LTIuNy02LjMtNS42bC03LjksOS40djguMWgzOS41QzQ4LjcsNDguNiw0Ni40LDQ1LjgsNDUuMSw0Mi40eiIvPg0KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik03Mi44LDQ1LjdjLTIuNywzLjQtNy4yLDUuNC0xMS42LDUuNGMtOC41LDAtMTUuMi01LjYtMTUuMi0xNC40YzAtOC43LDYuOC0xNC40LDE1LjItMTQuNA0KCQljNy45LDAsMTIuOCw1LjYsMTIuOCwxNC40djIuNkg1NC40YzAuNywzLjIsMy4xLDUuMyw2LjQsNS4zYzIuOCwwLDQuNi0xLjQsNi0zLjNMNzIuOCw0NS43eiBNNjUuNiwzMy43YzAuMS0yLjgtMi4xLTUuMi01LjItNS4yDQoJCWMtMy43LDAtNS43LDIuNS02LDUuMkg2NS42eiIvPg0KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0xMTcuMywyOS44VjIzaC03LjR2LThoLTguNXY4LjFIOTZoLTcuNFYxNWgtOC41djguMWgtNS40djYuOGg1LjR2MTNjMCw2LDQuMyw4LjMsMTAsOC4zYzIsMCw0LjEtMC4yLDUuOS0wLjgNCgkJdi03Yy0wLjcsMC43LTIuNSwwLjgtMy40LDAuOGMtMy43LDAtNC0yLjEtNC01LjFWMzBIOTZoNS40djEzYzAsNiw0LjMsOC4zLDEwLDguM2MyLDAsNC4xLTAuMiw1LjktMC44di03DQoJCWMtMC43LDAuNy0yLjUsMC44LTMuNCwwLjhjLTMuNywwLTQtMi4xLTQtNS4xdi05LjFoNy40VjI5Ljh6Ii8+DQoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTEzNy4xLDQ3SDEzN2MtMS45LDIuOS01LjIsNC4xLTguNyw0LjFjLTUuMSwwLTkuOC0yLjktOS44LTguNWMwLTkuNSwxMS41LTkuNiwxOC41LTkuNmMwLTMtMi41LTQuOS01LjQtNC45DQoJCWMtMi44LDAtNS4xLDEuMi02LjksMy4zbC00LjUtNC42YzMuMS0yLjksNy42LTQuNCwxMi4xLTQuNGM5LjksMCwxMi41LDUsMTIuNSwxNC4xdjEzLjlIMTM3TDEzNy4xLDQ3TDEzNy4xLDQ3eiBNMTM1LDM4LjUNCgkJYy0yLjYsMC04LjMsMC4yLTguMywzLjljMCwyLDIuMSwzLDQsM2MzLjMsMCw2LjQtMS43LDYuNC01LjF2LTEuOEgxMzV6Ii8+DQoJPHBhdGggY2xhc3M9InN0MiIgZD0iTTE2NC4yLDMxLjFjLTEuMi0xLjUtMi45LTIuMy00LjktMi4zYy0xLjQsMC0zLjEsMC42LTMuMSwyLjNjMCw0LjEsMTQuMywwLjYsMTQuMywxMWMwLDctNi44LDktMTIuNiw5DQoJCWMtMy44LDAtOC4xLTEtMTAuOC0zLjdsNS4xLTUuN2MxLjYsMS45LDMuNCwzLDYsM2MxLjksMCwzLjgtMC41LDMuOC0yYzAtNC40LTE0LjMtMC43LTE0LjMtMTEuMWMwLTYuNCw1LjctOS4yLDExLjUtOS4yDQoJCWMzLjYsMCw3LjYsMC45LDEwLjEsMy42TDE2NC4yLDMxLjF6Ii8+DQoJPHBhdGggY2xhc3M9InN0MiIgZD0iTTE5OC42LDQ1LjdjLTIuNywzLjQtNy4yLDUuNC0xMS42LDUuNGMtOC41LDAtMTUuMi01LjYtMTUuMi0xNC40YzAtOC43LDYuOC0xNC40LDE1LjItMTQuNA0KCQljNy45LDAsMTIuOCw1LjYsMTIuOCwxNC40djIuNmgtMTkuNmMwLjcsMy4yLDMuMSw1LjMsNi40LDUuM2MyLjgsMCw0LjYtMS40LDYtMy4zTDE5OC42LDQ1Ljd6IE0xOTEuNCwzMy43DQoJCWMwLjEtMi44LTIuMS01LjItNS4yLTUuMmMtMy43LDAtNS43LDIuNS02LDUuMkgxOTEuNHoiLz4NCgk8cGF0aCBjbGFzcz0ic3QyIiBkPSJNMjIxLjgsMjkuOGgtNy40djkuMWMwLDIuOSwwLjMsNS4xLDQsNS4xYzAuOSwwLDIuNy0wLjEsMy40LTAuOHY3Yy0xLjksMC43LTMuOSwwLjgtNS45LDAuOA0KCQljLTUuNiwwLTEwLTIuMy0xMC04LjN2LTEzaC01LjR2LTYuOGg1LjRWMTVoOC41djguMWg3LjRWMjkuOHoiLz4NCjwvZz4NCjwvc3ZnPg0K
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          - anyuid
          - hostmount-anyuid
          - hostnetwork
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - zts-xcrypt-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ''
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - xcrypt.zettaset.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: zts-xcrypt-operator
      deployments:
      - name: zts-xcrypt-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: zts-xcrypt-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: zts-xcrypt-operator
            spec:
              containers:
              - command:
                - zts-xcrypt-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: zts-xcrypt-operator
                - name: RELATED_IMAGE_CA
                  value: registry.connect.redhat.com/zts/xcrypt-ca-1@sha256:9f1015dfb459b69f5dbf449efa0517452095a6cf4f20826ebae278f9f800ffe7
                - name: RELATED_IMAGE_KMIP
                  value: registry.connect.redhat.com/zts/xcrypt-kmip-server-1@sha256:9af5d21dd748dfbf4e107f27a5f10fa3c0ba928ade9b989a744b620ce34ec757
                - name: RELATED_IMAGE_LS
                  value: registry.connect.redhat.com/zts/xcrypt-license-server-1@sha256:bc5486892a41e70f5dc4c4e1d82fca8db2149598fb8b5950ba5da1ee2d9d245d
                - name: RELATED_IMAGE_HM
                  value: registry.connect.redhat.com/zts/xcrypt-host-manager-1@sha256:2c69f887b431d6ebc89cb44ac9f2b27bd5625e99fbc63e937c2b0b723999f9e1
                - name: RELATED_IMAGE_CSI_DRIVER
                  value: registry.connect.redhat.com/zts/zts-csi-driver-1@sha256:c15fa9a7cc40891103f426206663dcebe1210c8ee3ab6037cbf64e1f86b9c7e5
                image: registry.connect.redhat.com/zts/xcrypt-operator-1@sha256:592d8522747cebcc101dd6b6a67e352474c85559e04a690f9b2695b9222cdd5f
                imagePullPolicy: Always
                name: zts-xcrypt-operator
                resources: {}
              serviceAccountName: zts-xcrypt-operator
              tolerations:
              - effect: NoSchedule
                key: zts
                operator: Equal
                value: zts-master
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - security
  - encryption
  - storage
  links:
  - name: Zettaset
    url: https://www.zettaset.com/
  maintainers:
  - email: info@zettaset.com
    name: Zettaset
  maturity: stable
  provider:
    name: Zettaset
  version: 1.0.0
  relatedImages:
  - name: host-manager
    image: registry.connect.redhat.com/zts/xcrypt-host-manager-1@sha256:2c69f887b431d6ebc89cb44ac9f2b27bd5625e99fbc63e937c2b0b723999f9e1
  - name: certificate-authority
    image: registry.connect.redhat.com/zts/xcrypt-ca-1@sha256:9f1015dfb459b69f5dbf449efa0517452095a6cf4f20826ebae278f9f800ffe7
  - name: kmip
    image: registry.connect.redhat.com/zts/xcrypt-kmip-server-1@sha256:9af5d21dd748dfbf4e107f27a5f10fa3c0ba928ade9b989a744b620ce34ec757
  - name: license-server
    image: registry.connect.redhat.com/zts/xcrypt-license-server-1@sha256:bc5486892a41e70f5dc4c4e1d82fca8db2149598fb8b5950ba5da1ee2d9d245d
  - name: csi-driver
    image: registry.connect.redhat.com/zts/zts-csi-driver-1@sha256:c15fa9a7cc40891103f426206663dcebe1210c8ee3ab6037cbf64e1f86b9c7e5
  - name: xcrypt-operator
    image: registry.connect.redhat.com/zts/xcrypt-operator-1@sha256:592d8522747cebcc101dd6b6a67e352474c85559e04a690f9b2695b9222cdd5f
status:
  certsLastUpdated: null
  certsRotateAt: null
  lastTransitionTime: null
  lastUpdateTime: null
