apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units: []\n\nproperties: []\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: opa-operator
    app.kubernetes.io/name: opa-operator
    app.kubernetes.io/version: 25.7.0
    stackable.tech/vendor: Stackable
  name: opa-operator-configmap
