# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: flashsystemclusters.odf.ibm.com
spec:
  group: odf.ibm.com
  names:
    kind: FlashSystemCluster
    listKind: FlashSystemClusterList
    plural: flashsystemclusters
    singular: flashsystemcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Current Phase
      jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Created At
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: FlashSystemCluster is the Schema for the flashsystemclusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FlashSystemClusterSpec defines the desired state of FlashSystemCluster
            properties:
              defaultPool:
                description: DefaultPool has the configuration to create default storage class
                properties:
                  fsType:
                    enum:
                    - ext4
                    - xfs
                    type: string
                  poolName:
                    type: string
                  spaceEfficiency:
                    enum:
                    - thick
                    - thin
                    - compressed
                    - deduplicated
                    type: string
                  storageclassName:
                    type: string
                  volumeNamePrefix:
                    maxLength: 20
                    type: string
                required:
                - poolName
                - storageclassName
                type: object
              insecureSkipVerify:
                description: InsecureSkipVerify disables target certificate validation if true
                type: boolean
              name:
                description: Name is the name of the flashsystem storage cluster
                type: string
              secret:
                description: Secret refers to a secret that has the credentials for flashsystem csi storageclass
                properties:
                  name:
                    description: Name is unique within a namespace to reference a secret resource.
                    type: string
                  namespace:
                    description: Namespace defines the space within which the secret name must be unique.
                    type: string
                type: object
            required:
            - name
            - secret
            type: object
          status:
            description: FlashSystemClusterStatus defines the observed state of FlashSystemCluster
            properties:
              conditions:
                description: Conditions describes the state of the FlashSystemCluster resource.
                items:
                  description: Condition represents the state of the operator's reconciliation functionality.
                  properties:
                    lastHeartbeatTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      description: ConditionType is the state of the operator's reconciliation functionality.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                description: Phase describes the Phase of FlashSystemCluster This is used by OLM UI to provide status information to the user
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
