---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-operator-rb
subjects:
  - kind: ServiceAccount
    name: webserver-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webserver-operator-role
