apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webserver-operator-crb
subjects:
- kind: ServiceAccount
  name: webserver-operator
  # namespace is required for SA subjects in ClusterRoleBinding
  namespace: kiwi   # IMPORTANT: if you ship this in a bundle, hardcoding namespace is usually WRONG
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webserver-operator-cr
