---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webserver-operator-cr
rules:
- apiGroups: ["example.com"]
  resources: ["webservers", "webservers/status", "webservers/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
