# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backup-manager
  name: pachyderm-operator-backup-manager
spec:
  ports:
  - name: api
    port: 8890
    protocol: TCP
    targetPort: 8890
  selector:
    app: pachyderm-backup-manager
  type: ClusterIP
status:
  loadBalancer: {}
