apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: coralogixloggers.loggers.coralogix.com
spec:
  group: loggers.coralogix.com
  names:
    kind: CoralogixLogger
    listKind: CoralogixLoggerList
    plural: coralogixloggers
    singular: coralogixlogger
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Coralogix logging agent.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CoralogixLoggerSpec defines the desired state of CoralogixLogger
            properties:
              cluster_name:
                default: cluster.local
                description: Current cluster name
                type: string
              private_key:
                description: Coralogix Private Key
                format: password
                maxLength: 36
                minLength: 36
                pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-z]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
                type: string
              region:
                default: Europe
                description: Coralogix Region
                enum:
                - Europe
                - Europe2
                - India
                - Singapore
                - US
                type: string
            required:
            - private_key
            type: object
          status:
            description: CoralogixLoggerStatus defines the observed state of CoralogixLogger
            properties:
              clusterRole:
                description: ClusterRole name
                type: string
              clusterRoleBinding:
                description: ClusterRoleBinding name
                type: string
              daemonSet:
                description: DaemonSet name
                type: string
              phase:
                description: Phase
                type: string
              reason:
                description: Reason
                type: string
              serviceAccount:
                description: ServiceAccount name
                type: string
              state:
                description: Current state of logging agent
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
