# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: integrationconfigs.tenantoperator.stakater.com
spec:
  group: tenantoperator.stakater.com
  names:
    kind: IntegrationConfig
    listKind: IntegrationConfigList
    plural: integrationconfigs
    singular: integrationconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: IntegrationConfig is the Schema for the integrationConfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: IntegrationConfigSpec defines the desired state of IntegrationConfig
            properties:
              argocd:
                description: Argocd contains details about argocd Applications and
                  AppProjects
                properties:
                  clusterResourceWhitelist:
                    items:
                      description: GroupKind specifies a Group and a Kind, but does
                        not force a version.  This is useful for identifying concepts
                        during lookup stages without having partially valid types
                      properties:
                        group:
                          type: string
                        kind:
                          type: string
                      required:
                      - group
                      - kind
                      type: object
                    type: array
                  namespace:
                    type: string
                  namespaceResourceBlacklist:
                    items:
                      description: GroupKind specifies a Group and a Kind, but does
                        not force a version.  This is useful for identifying concepts
                        during lookup stages without having partially valid types
                      properties:
                        group:
                          type: string
                        kind:
                          type: string
                      required:
                      - group
                      - kind
                      type: object
                    type: array
                required:
                - namespace
                type: object
              nexus:
                description: Nexus is the config for a managed application.
                properties:
                  enabled:
                    default: false
                    type: boolean
                  endpoint:
                    description: Endpoint is used to connect to an application
                    properties:
                      secretReference:
                        description: SecretReference contains details of a secret
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        type: object
                      url:
                        type: string
                    type: object
                  sso:
                    description: SSO contains details for single sign on
                    properties:
                      accessorID:
                        type: string
                      clientName:
                        type: string
                    type: object
                required:
                - enabled
                type: object
              openshift:
                description: Openshift is the config containing labels and annotations
                properties:
                  clusterAdminGroups:
                    description: ClusterAdminGroups contains groups which are admins
                      of tenants
                    items:
                      type: string
                    type: array
                  group:
                    description: Group contains labels and annotations applied to
                      the group
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  namespaceAccessPolicy:
                    description: NamespaceAccessPolicy contains groups/users which
                      are denied access over managed namespaces
                    properties:
                      deny:
                        description: Policy contains policies relating to privilegedNamespaces
                        properties:
                          privilegedNamespaces:
                            description: PrivilegedNamespaces contains groups/users
                            properties:
                              groups:
                                items:
                                  type: string
                                type: array
                              users:
                                items:
                                  type: string
                                type: array
                            type: object
                        type: object
                    type: object
                  privilegedNamespaces:
                    description: PrivilegedNamespaces contains list of privileged
                      namespaces regex
                    items:
                      type: string
                    type: array
                  privilegedServiceAccounts:
                    description: PrivilegedServiceAccounts contains list of privileged
                      serviceAccounts regex
                    items:
                      type: string
                    type: array
                  project:
                    description: Project contains labels and annotations applied to
                      the namespace
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  sandbox:
                    description: Sandbox contains labels and annotations applied to
                      the sandbox
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                type: object
              rhsso:
                description: Nexus is the config for a managed application.
                properties:
                  enabled:
                    default: false
                    type: boolean
                  endpoint:
                    description: Endpoint is used to connect to an application
                    properties:
                      secretReference:
                        description: SecretReference contains details of a secret
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        type: object
                      url:
                        type: string
                    type: object
                  sso:
                    description: SSO contains details for single sign on
                    properties:
                      accessorID:
                        type: string
                      clientName:
                        type: string
                    type: object
                required:
                - enabled
                type: object
              vault:
                description: Nexus is the config for a managed application.
                properties:
                  enabled:
                    default: false
                    type: boolean
                  endpoint:
                    description: Endpoint is used to connect to an application
                    properties:
                      secretReference:
                        description: SecretReference contains details of a secret
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        type: object
                      url:
                        type: string
                    type: object
                  sso:
                    description: SSO contains details for single sign on
                    properties:
                      accessorID:
                        type: string
                      clientName:
                        type: string
                    type: object
                required:
                - enabled
                type: object
            type: object
          status:
            description: IntegrationConfigStatus defines the observed state of IntegrationConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
