apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-admin-cluster-panslot
  #namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cnseries-service-controller-manager
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-admin-cluster-panslot
  apiGroup: rbac.authorization.k8s.io
