apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: airlock-microgateway
    app.kubernetes.io/name: microgateway-operator
    app.kubernetes.io/part-of: microgateway
    app.kubernetes.io/version: 4.8.3
  name: airlock-microgateway-operator-leader
spec:
  endpoints:
  - metricRelabelings:
    - action: keep
      regex: ^(microgateway_license|microgateway_sidecars).*$
      sourceLabels:
      - __name__
    path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: airlock-microgateway
      app.kubernetes.io/name: microgateway-operator
      operator.microgateway.airlock.com/isLeader: "true"
