apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: modelbuildersaws.modelbuilder.com
spec:
  group: modelbuilder.com
  names:
    kind: ModelbuilderAWS
    listKind: ModelbuilderAWSList
    plural: modelbuildersaws
    singular: modelbuilderaws
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: modelbuilder is the Schema for the modelbuilder
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              license:
                description: License Agreement
                properties:
                  accept:
                    description: License agreement
                    type: boolean
                type: object
              postgres:
                description: Storage parameters for vision database
                properties:
                  storage_size:
                    description: Leave as default unless directed by IBM Support
                    type: string
                  storage_class:
                    description: Leave as default unless directed by IBM Support
                    type: string
                  backup_storage_size:
                    description: Leave as default unless directed by IBM Support
                    type: string
                type: object
              env_type:
                description: 'Set replicas for service pods ( lite:single replica, prod:
                  2 replicas) Default: lite'
                type: string
              vm_request_method:
                description: 'VM request method. Default: dynamic'
                type: string
              email_notification:
                description: Notify via email when Virtual Machine provisioning fails for model training tasks
                type: object
                properties:
                  accept:
                    description: Email Notification
                    type: boolean
                  vm_mail_recipient:
                    description: Provide email address on which you'd like to get the notifications.
                    type: string
            type: object
          status:
            description: Status defines the observed state of Modelbuilder
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    additionalPrinterColumns:
    - jsonPath: .status.phase
      description: IBM Modelbuilder for Vision Deployment Status
      name: Status
      type: string
    - jsonPath: .status.url
      description: User Management Console
      name: URL
      type: string
    - jsonPath: .status.workbenchUrl
      description: URL for IBM Inspection Workbench
      name: URL
      type: string
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null