apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  creationTimestamp: null
  name: clusterresourcesupervisors.hibernation.stakater.com
spec:
  group: hibernation.stakater.com
  names:
    kind: ClusterResourceSupervisor
    listKind: ClusterResourceSupervisorList
    plural: clusterresourcesupervisors
    singular: clusterresourcesupervisor
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ClusterResourceSupervisor is the Schema for the resourcesupervisors
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ClusterResourceSupervisorSpec defines the desired state of
              ClusterResourceSupervisor
            properties:
              argocd:
                description: ArgoCD contains details about ArgoCD to which the schedule
                  will be applied
                properties:
                  appProjects:
                    description: AppProjects is a list of the ArgoCD AppProject names
                      that will follow the Hibernation schedule
                    items:
                      type: string
                    type: array
                  namespace:
                    description: Namespace is the name of the namespace where the
                      AppProjects are residing
                    type: string
                required:
                - appProjects
                - namespace
                type: object
              namespaces:
                description: Namespaces is a list of namespaces to which the schedule
                  will be applied
                properties:
                  labelSelector:
                    description: |-
                      A label selector is a label query over a set of resources. The result of matchLabels and
                      matchExpressions are ANDed. An empty label selector matches all objects. A null
                      label selector matches no objects.
                    properties:
                      matchExpressions:
                        description: matchExpressions is a list of label selector
                          requirements. The requirements are ANDed.
                        items:
                          description: |-
                            A label selector requirement is a selector that contains values, a key, and an operator that
                            relates the key and values.
                          properties:
                            key:
                              description: key is the label key that the selector
                                applies to.
                              type: string
                            operator:
                              description: |-
                                operator represents a key's relationship to a set of values.
                                Valid operators are In, NotIn, Exists and DoesNotExist.
                              type: string
                            values:
                              description: |-
                                values is an array of string values. If the operator is In or NotIn,
                                the values array must be non-empty. If the operator is Exists or DoesNotExist,
                                the values array must be empty. This array is replaced during a strategic
                                merge patch.
                              items:
                                type: string
                              type: array
                              x-kubernetes-list-type: atomic
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                        x-kubernetes-list-type: atomic
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: |-
                          matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                          map is equivalent to an element of matchExpressions, whose key field is "key", the
                          operator is "In", and the values array contains only "value". The requirements are ANDed.
                        type: object
                    type: object
                    x-kubernetes-map-type: atomic
                  names:
                    items:
                      type: string
                    type: array
                type: object
              schedule:
                description: Hibernation defines the schedule for putting resources
                  to sleep and waking them up
                properties:
                  sleepSchedule:
                    description: SleepSchedule specifies the cron schedule for resource
                      hibernation. It must follow the standard cron format
                    type: string
                  wakeSchedule:
                    description: |-
                      WakeSchedule specifies the cron schedule for waking up resources. It must follow the standard cron format awoken
                      It is optional and if not provided, resources will stay asleep
                    type: string
                type: object
            required:
            - schedule
            type: object
          status:
            description: ClusterResourceSupervisorStatus defines the observed state
              of ClusterResourceSupervisor
            properties:
              currentStatus:
                description: CurrentStatus shows the state the tenant's resources
                enum:
                - sleeping
                - running
                - error
                type: string
              ignoreNamespaces:
                description: IgnoreNamespaces contains the list of namespaces that
                  are being ignored by the ClusterResourceSupervisor
                items:
                  type: string
                type: array
              nextReconcileTime:
                description: NextReconcileTime contains the next time at which the
                  namespace resources will sleep or wake up
                format: date-time
                type: string
              sleepingNamespaces:
                description: SleepingResources contains the previous states for each
                  of the deployments currently scaled down
                items:
                  description: SleepingNamespace contains the previous states for
                    the Deployments or StatefulSets currently scaled down
                  properties:
                    Namespace:
                      description: Namespace is the namespace that contains the application
                      type: string
                    sleepingApplications:
                      items:
                        properties:
                          kind:
                            description: Kind stores the application's kind (Deployment
                              or StatefulSet)
                            enum:
                            - Deployment
                            - StatefulSet
                            type: string
                          name:
                            description: Name is the name of the sleeping application
                            type: string
                          replicas:
                            description: Replicas are the number of desired pods for
                              the Deployment, stored at the time of sleep
                            format: int32
                            type: integer
                          status:
                            enum:
                            - sleeping
                            - running
                            - error
                            type: string
                        required:
                        - kind
                        - name
                        - replicas
                        type: object
                      type: array
                    status:
                      enum:
                      - sleeping
                      - running
                      - error
                      type: string
                  required:
                  - Namespace
                  - sleepingApplications
                  type: object
                type: array
              watchedNamespaces:
                description: WatchedNamespaces contains the list of namespaces that
                  are being watched by the ClusterResourceSupervisor
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
