apiVersion: v1
data:
  component_config.yaml: |
    apiVersion: marketplace.redhat.com/v1alpha1
    kind: ComponentConfig
    apiHandlerConfig:
      handlerTimeout: "30s"
    eventHandlerConfig:
      memoryLimit: "50Mi"
      maxFlushTimeout: "300s"
      maxEventEntries: 50
      dataServiceTokenFile: "/etc/data-service-sa/data-service-token"
      dataServiceCertFile: "/etc/configmaps/serving-cert-ca-bundle/service-ca.crt"
    managerConfig:
      leaderElectionId: "datareporter.marketplace.redhat.com"
      health:
        healthProbeBindAddress: :8081
      metrics:
        bindAddress: :8443
      webhook:
        port: 9443
      leaderElection:
        leaderElect: false
kind: ConfigMap
metadata:
  annotations:
    operatorImage: quay.io/rh-marketplace/ibm-data-reporter-operator:2.22.0-2518
    rbacProxyImage: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9:v4.17
  labels:
    redhat.marketplace.com/name: ibm-data-reporter-operator
  name: ibm-data-reporter-operator-component-config-42m8t7c92h
