# permissions for end users to view memcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcached-viewer-role
rules:
- apiGroups:
  - cache.omarg.net
  resources:
  - memcacheds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.omarg.net
  resources:
  - memcacheds/status
  verbs:
  - get
