apiVersion: v1
data:
  kes: |
    image: "quay.io/minio/aistor/kes:RELEASE.2025-12-04T20-12-15Z"
  kes-sidecar: |
    image: "quay.io/minio/aistor/kes-sidecar:RELEASE.2025-12-17T18-48-32Z"
  minio: |
    image: "quay.io/minio/aistor/minio:RELEASE.2025-12-20T04-58-37Z"
  minio-sidecar: |
    image: "quay.io/minio/aistor/minio-sidecar:RELEASE.2025-12-17T19-01-44Z"
kind: ConfigMap
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2025-12-17T19-10-08Z
  name: object-store-operator
