apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: airlock-microgateway
    app.kubernetes.io/name: microgateway-operator
    app.kubernetes.io/part-of: microgateway
    app.kubernetes.io/version: 4.5.3
  name: airlock-microgateway-operator-metrics
spec:
  ports:
  - appProtocol: http
    name: metrics
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: airlock-microgateway
    app.kubernetes.io/name: microgateway-operator
status:
  loadBalancer: {}
