---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vcp-operator
    app.kubernetes.io/name: vcp-operator
  name: vcp-operator-metrics
spec:
  ports:
    - name: metrics
      port: 9402
      protocol: TCP
      targetPort: 9402
  selector:
    app: vcp-operator
  type: ClusterIP
status:
  loadBalancer: {}
