apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: aci-containers-operator
  namespace: placeholder
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "aci.ctrl/v1alpha1",
          "kind": "AciContainersOperator",
          "metadata": {
            "name": "acicnioperator",
            "namespace": "aci-containers-system",
          },
          "spec": {}
        }
      ]
    categories: Networking
    certified: 'false'
    createdAt: '2022-02-15T12:00:00Z'
    description: >-
      The Cisco Application Centric Infrastructure (ACI) Containers Operator
      brings the ACI CNI Plugin and Policy model to Kubernetes clusters.
    containerImage: quay.io/noiro/aci-containers-operator@sha256:0db556fc8f188159fbb18797d8fcbd96303176d7803acaaf6bf604de8dcc0fd0
    support: 'acisupport@cisco.com'
    capabilities: Seamless Upgrades
    repository: 'https://github.com/noironetworks/aci-containers'
    marketplace.openshift.io/remote-workflow: "https://github.com/noironetworks/aci-containers/blob/master/README.md"
    marketplace.openshift.io/action-text: "Install-time Instructions"
spec:
  displayName: Cisco ACI Containers Operator
  description: >
    ## ACI CNI Plugin


    The Cisco Application Centric Infrastructure (ACI) CNI plugin brings the ACI
    Networking and Policy model to Kubernetes clusters that reside on-prem or in
    the cloud. It is fully open source and relies on the Opflex Protocol to
    program Open vSwitch instances running on the Kubernetes nodes. It provides
    IP address management, L2/L3 networking, load balancing, and security
    functions for container workloads.


    Features of Cisco ACI?

    Links to learn more about the Plugin?

    ## ACI Containers Operator


    How does the Operator work?

    What does the Operator do?

    Links to learn more about the Operator?

    ## Prerequisites for enabling this Operator


    Please describe any steps a user needs to take prior to enabling this
    Operator (e.g. any Secrets or ConfigMaps that need to be in place upfront).
  maturity: alpha
  version: 1.0.0
  replaces: ''
  minKubeVersion: 1.11.0
  keywords:
    - cisco
    - aci
  maintainers:
    - name: 'Abhishek Sharma '
      email: abhishs9@cisco.com
    - name: Sumit Naiksatam
      email: sumitnaiksatam@gmail.com
    - name: Vishal Lella
      email: vlella@cisco.com
  provider:
    name: Cisco
  labels: {}
  selector:
    matchLabels: {}
  links:
    - name: Cisco ACI Homepage
      url: >-
        https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/b_Kubernetes_Integration_with_ACI.html
  icon:
    - base64data: >-
        iVBORw0KGgoAAAANSUhEUgAAAMgAAABqCAYAAAD5jB57AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH4gcGEDk23QsotgAAFUtJREFUeNrtnXl8lNW5x3/PeWeykZDMZIZNuKKyVZJJ0lggybBEKRCoy22NSIEUazetVT72Vj92g27Y3X7qba96rRu0tkHsLVY2ZUsyESwImQQhqBWwpWSbrIQkM+957h+JbY1J5p0tmQnn+2fm5LznPOf8znnOOc97XsIoYELRHXZJvoeYsQxACjOOCo1/XP/ylkooIs64FWvypU4PECEXQDsRdgk2PXxh59MNsV43ivUKWItWTxYQFQRc2e8nnQh31O/YvFl14chhK1qzmkDPAtD6daxzPt3k9Ox5+r1Yrp+I9QYyQfvVAOIAAI0Zj9mXr5ugunGEZo6bVo0n0OP9xQEADPyHpvl+Fet1jGmBWBYXpzJ4xRBJkgj6LaorRwbZY74FwJghkixPu2VdmhLISBU+PmHSQKNXv5HsStWVI+SfE0/xk0SL9+qTlUBGzL0aWhwAwBz7bmTUYsC27GNNCUShGKUogSgUSiAKhRKIQqEEolAogSgUSiAKhRKIQqEEolAogSgUlyGm4XqQbemaiUS0lAGLEFxTP2faXmzcKGPFULblJTME+HqWiJNMh5p2P/d6LDV0+tKSOYJ4Hgn0SNC+xh3PnY6Zwm/cKMa9/vYNUlIGAc3MvLtx95Z/jBqB2IrWrifgYQAJBICZYD/89nGxZO0n6/ZsfjeqG6e4WLN3JP4CzHczIECAIIZ9ecnLvp5Lq5tf3doazcW3LC5ONcUl/hbcG/XMDBBY2otKft2QfGk9tm7Vo7n8E5atm6offudFBuVQ39tLRNRlW7b26427Nj8S8y6WvahkJQGPAEj44C+ULTXsnFb0lfhobiB7e8JGgO/5kK2YV5jMCVui3kUwJ2x+XxwfbHe+p7du0cu0oq/E60LfCSCn308JRPi5bdna20fBGoQ3DPHjzDY0r4zWBhq/ZO0YEO4fIsknbEvXfDRqxV1UkgPgxkETEL5qX1ScHK3lb6OW28CYNWjxBTbEtED6jP+RIeVDmBvFK7QMAElDGlBEb/mZMcdPkkRKSMyM3vLT0OVnzLIWrR4bswIRcQlJ/lNRUrQ2kE6GyjYmep0U9lt+4iguP3Gi3z4maUzMCkShiHWUQBQKJRCFQglEoVACUSiUQBSKKOGfoSZpt6xLM/f4lhAjnaR4q6773AEcOOBTJhoe7EtKiiDkShAAid837N6yS1llmFi0yDQ+4YqFTDSDmRq9CdorLf/3TMs/BWJbtmYVdcv/ASiVAbBgjEuc8qa+Yu2tTS9vPqksGDlsN302hXw9R8E8/Z9XJQt8xl609nRDclcutm7tUFaKHOlL1s3SNH2bBK4FABBg7tZb7EUlX2rY+dwfhG3ZmkVEtBng1H//RwauFRK7I31Sedn7uF7va2CaPsBPM+wd8ep2+ghiLVo9Vmj6Hn5fHP8iDeAt44o+UyAI9G0MfkPhFMHiTmXKCLlVRSU5DMwePAVljlu2yqEsFakFuPgsgMGuTzUx5LcE/MRCEWieMmWk4E/5SyFJu1XZKTIQ/MXR0TwBP8F4ENEcaxTbSFCq/0YUacpSkRKIv1g7HqO2eRWKIecHhUKhBKJQKIEoFEogCoUSiEKhBKJQKIEoFDEukItDpmAOJVjuot8U0kCaEYJ9BspG1BG88dnvpXMM2RJ0BchA+YUevcGQjE6/aeLjOoLPnv3l3yEYdGjoTHAo2ALU7dl8EaDqIfMnfi1a2yc+LqHGr8j1EMpP2gv+kmg6lQYtQCZ/bXdRM41xR60+yG/5axq3P9UevP3ZT/78miCi7wLQBx6AcA5m829CqSQxNvTqbJAKJndvjdYGOv/SE51g/HCIEfrF+t1bqoLNv2HHM8cBrh5idKqq27O5Jtj863c95wb4hcGzpx+df+mJzmi1f2NdwtahBlgi3hiSAE1xTzFwdpCffSTwfdGw49kyZqwB0H8qr9F1bWlICu1tpD8S+Mv9R2IGDuu6aTm2bu2JZh+0Yd41mxj00w8NIoQX2WReF/IoaY4rAHB6gN5b25DS5Qy5Ape67wCwrf+8R8DPGude/YOoXgAcfcKr69oKBg73n/mI6cv1O7ZsC0mA259qB/NSAP0HoWYQr65/eUslvf8Xy+LiVJMpYQmB7DrxqabkroPhvNh40o2rbD1e7eMCwsKAu2HXc64hZhZDjF+xNkNKVPtxEX/cuHPzg6GWf+LyT1/pk6ZFDCQIlodCmTkGYtyytUuZeFWv9rTf1e98dk948y9xSOJ5xNStQRy8sOuZM6HmaV+2dhMIDw3pQUjODoOtyL6spIAAh4RsjjPrr5x/6fnGsBmnuFhL70hYqDHNYkK9z3vplfcvJadY3mEYToEoRlQgI4ba5lUolEAUistQIOQTrJow2hspttsopgUi43uMLNTqVS+NDAw0+E0jRL0SyAhRv/35OgB/GUpDLLBDdeUICURqOwEM9Z3JIw07nrmgBDKiFZD3AugacHYHHlH3ekWOpj3PnGLQzwf5uZuY7o31OmqxXoGLb1f/LWVG1qsMygAwue/PdQx8q2Hn5u+pbhxZOt+uejVpelYL9X5HsO9zbnRIQK6q37XlUKzXj0ZTY11xQ0n6pTg90TN3+vlY+sT0qGDjRmE9/NakxB7t0t/3PtekDKJQKBQKhUKhUCgUCoVCoVAoFAqFQqFQKBQKhUKhUCgUCoVCYYCoiOZlgFy2nIkMmQzIFI1kKwutrbWus3U53u6OVePunzo1wdxhsUJKC0kyS9bb4qS3tbN9QmshDvhGqlyVk/MS9faOiSw42QRiZlNbD7i1sOV4y0iUxzXeMQ5dMkWaKU1jXBRMHXM97vM09MtYo1cg+6dOTTC1pxYR+ONg5AGYBSBhgKQ6CGcIOMmSXEJg39+aZhy9Dcbv6yq3ZS8inYf8Uqxg/Ca/pepYOOoV15p6KxMvJiCfgemDJPWCcA7M7zCJ44L5dV2YKxc0Hv1HJOxdnpp5NWn0SRAWgPFRAFcMMlS1AagFqIoZ+8xmuW9efU1duAfD16wZeZLFChAWAsgAkDpAz+wGo5YIFQDvaW26tGskBsthFUh5aubV0Og+Aq8DaGyQJv6u01O9wfAzrY77CPiFHzOsdHqqSkMRhrkt5SGA7gZgC7IlHnM2ue8KY0cUlVbHJxlYD6Ag2GwumpGytM4d8gXjRyblJnV3++5k8H1gXBNEFs0EPEVEj+Q3Vf19uPqsaTgeUmGbmUIyfgMDXwEQF6Iuo+olL1dadja36b8F6NpoKVOZJbvAJeSjYOSEOoDGST1ke7ssjtu7urw/HXzmMoSFga8y890uq+NHPWPbflR45kxXpG0Z8XfSXenZH4Oe8AYDX+0Vx+ihzJLhYCH3Ros4SlGsVVgcmwTJg2EQR8gcss4dW251PM+E50MUx7+TyMBGc9vY18ptWTNiWiCu9MybmeVBEE8bbbsbZck5dkHiFQDWaCjPkUm5SZMstS/2XQU64ncNHBqXMd5Hlw4QcHuEHpFNkg9XWBzzY1Ig5RbHjcz0AoBEjEK0OPl9AOOioSwnMDuuq8v7Agg3RUN59qfk2nw+cWAYZrE0EHa5rJl5MSWQyrSsHCKUDtcaZ/hdB8dkBt8ZLeXxWMVjAIqiYiZDrtls9m5H787kcJDEoJcOpjquiolF+pFJuUndXd4/YOBt21GBl/hmYjLqxhwHeDsDf2dCvWARD4YF4CkgzAKQDeDq4BfAWWsYfEe02KbL6v0BgLxhfmy6puH5/VjkDPf5UtgF0nXJ+03QoPv/Q8D/ANERZm4koi6SNFESxhH4WgBp0SQQIcViJr9XznrAuMXZ7C73u56x5U4U0hfwWqZy7GyrFPzzIL6yojNwFMBfidBMEsl9tp4C0KxgPQtXWnY2Q94fxL+2AngLQCOAFABXAZgUYB5zzVbPPfD429IfQYGU2XIngr33B9BgOhi/FUy/yGtxH6cBPqhTimJtYnrtdZC4kQhR4dYwySv87TYzaNP85qpyI/n1HRAGfEjIZtMDYLYH8C9nwfQwS1k6v7W6ebD1g9nsux6QJQAF5LZJIX9KgWwQMP5EAr/sabKW9R/5yywZDkHaOhDfDUa8wRw3HLHkPn1d89HWqBSI4J57wWS0Mucg5KecjTVHhkp0G7bqaMJhAIdPYPZ3PTbT1JGXCPldnBNxYyRLUGGbmcJS3mX8WIgfb/Ncus/faXRh+9FGAKUASsttWTNSGhK6jZUn4zpI3GB02QTI253NNa8MOmg017gB3H8w1fGopuHFPlfU76K9C767gCG+KzlSi/RSFGtgKjGY/F2TSc7xJ47+zMaJnvmNVaejYA7xf7LM+PwR5JojJlGO+5TRaAQGvuP0VH8p0FCN+Y1Vp6/DUa+x6YM+ZzDbRgjkOz2Di+PfWdjqfter6fMBVBgcpT/HYTxMDptAJllq8w36jT3EuCncMT7DPIMYubG8oMvq3VdpzciPiEQZtxpM+Uenx/2dSFqjFMUaQMWGZERY6Wx01waSf2HDiQ6TSd4K4LyB0eAaly0jN+oEAqJCgy37eEGzuwYxDAFlBpM6JYSrIt3xRkW646HK9MxZYeyQRr6A6yWdv0YhfizVHxNstVkwcGDKQGlBk3tfMM+YV19TRzD22WfS6froEwizIdWyDO8uw8h4WNiGQDodIweMTZLpZIU180S5JfPB/fbZE4J9/JT0kzMwUATshzvknwpaa96JtDmETnOMpNMk/TiU5/R40p8G4NfzYMK8KJxBYCQu5sT81uq/xro+CprdNQR6IUhDXUtEPzTr2jmXNevxsuQce6A56CQMbaMT4c/DM6XyTAOp3strqToeymN6d7pop4ECzYg+gQDjDbgmbowSWIj1AEIJuzYz+AsiTj9WZskOKBydJRuafUgXw/L5ZQYmGEj0RlhcPZJHDaSaGI0CGWMgzaj5XqCz8dh5IelGI1O+H64QJPeVWx3LjE/WlGQoncYNw2ELQe9/OGeo2YzCsilDbGiDJCUaBeL3LT+m0RXunt9SdUyTYh6AUL+kFEfAtjJrjqGweSJjr6KSTubhsANLA20fplcdmDk+HH1xJNYgHf5nR5qIUUZey/EzBR53AZi+BOBcCFklCehPGtrDZ243kqEU+vDYWxgpj5wUpo5mJJ+26BMI+/fHWXABj4IPhw6wtpLO5qrHEzzmaQDdDmAHgGCC5vIq0jNv8P88cd5Yk1DBcNSfJZ01YKX8HZgWHwZjLzIwW52JRher1kCL2V2WrHyMUq7DUa/TU/UHp8e9wuztmcCgOwHsQwC3c5CktQbS1BoUyH8OywQCOmUgWXKKJWlJKM+pHDvbCsDveRsxTkWdQAj0uqFGI/4mLgPmtp9qmu+pesrpcd+gkczoE4oRQ/o9AJzXcvwsgAv+s+J8V7rj+kjX1SfZZXDttCGUMBDdbHoQBl7AI+KKqBOIlL69Bt2RpeXpWWtxGZHXVHPS67EuBXiPgeRT/HUiAhhkTHDM+NURS25qJOu3sNX9LgAjMXK5lZbMrwXzDJc1M4+Y1xuaOKVpT9QJZH7LiSoGThoSCfMT5emZiy8nkRTigE9KbDKQ1HwUuX6jrFni9wYfPauLekr322cnR7J+BPzOmAdBmyosmZ8OyLWyZGYysA3GdsIqC1qOnY06gfT5ok8aTJpATDtdlswHTmC24e0/V1p2dqU1a2nMLuZNmhH3otNIBG1is3kXDB9U0hKzrlW60rKzDXfKyXmJ5dbML+yfOtXQm6EstP8FwUi0sAaiLRVWx0/8iZYB4UrPXCeJXIDRHVB6NMzCDx+7xzvGjPHhXTACCZ84A8avJWkvL/Ace7N/I8nOi1kgXA/GTQDmAvw9p6f620Yzj8TFcQxQoKfCpSjWJllrtwNY7idptdPjdhjJsyI98x5wQB1CEmgbE35v4oRX53kOf2A7tDI96wrJcDL4BgJuBWDxanpKYcOJDkPlsWY+BtAXAyhPHRhPEfFLPVI7WdhyvKVycl6ir7PrKg1yGQMlAGcFkN+p856ZGYHcvDmsAunzFT/PoCeC/Pcu9J5MX0LvPUoDnIiOvEAqrI4KgC8yoZyYD+vAqYWemvcGSrvfPjvZLE1LwPxAr8D98qTT4/68kXLswLT4sdbEN0K4l6sR/3rNdRyADx0sBiKQsuQcu4jTawFYgixPD0I4UCTQ0gJP1Z5w9uewv5Oe76l+0mV13AYgmDVGAoArY8BZSgZQQIwlAEHrFU0ngDoQWsDoQG/4tw067AAbd2WZXzSadDne7q6A4070ht8Hc2puQ7BXpQ7Ago5jDeXWzC8SKNhrXEMRxxPhFkfY1yDv77B4veZVAM7i8iIJwFV9d0HNBzAbvQGcAdiY3yxort4dyEOdHvchEN8fLUaY76neCuZHh/ep/BdKSlofiZwjcm9VYfvRxoP27I9rujyAwG+nuFyREOKeYK78dzZV/3eFNXMcQN+KhooUNFevd1kd4wCsHIbH1ZKZPpH/t9cuBfqPlelZc3qvYAIkdMmS631m1BU2nLjAgKhIz7w+YmEfCxuOv0W6XADwm6rvG5p6v+lsrNof7L87PdXfZtB/IYyBeiF4EfK8Z+ZqEB6L8KMOeb1mZ0GdO6gocUm61JmvkcQ3SxJSCNM3zLr2IAC4bFkLiemPEY2LKmiteceEpDwAzyoFDIpORPc6m9wPh+7eVP1MEpYitKDJsHAbturOJvddBP4sgIthzp4Z+GWbp3NR3y0swQ0qjTVHSJOvM6N2QZN7L5i7AKTswLR4lvITYOyNeODgPM/hNqfHvQ6QS0A4pvTwAdwsxOKCpqqw+ewLmtx7TUjMBONhAJ0j7m55qp/WIT8CcCnC88WoIwLSOd/jvi8SH9QhYOdY65ibidBDhM5hi6x1empeKWhy5wrQMjC2GzxU6k8LQLG++JdEOAjm1QUed878xuMHIjIoNbu/Lnu0qSB8A8bCQD40SgM4gTEXQ77Kc6Gn5j2np3qlhJZJvUcAzQFm0QPGdgaKnB73x/I9NZWRapxWT+efGbwRUrzcJ5iRocI2MwWILwRzHkCzwbiagVTqfTOxDUA7GA0gPk1Eb+qEiguNM6sCPQRypWZcwyZtyMMmARwO5KtFu8c7xiTpPEvo4iNMcgYgpgA8AYAdhDRmxBMwhoGLBLQycIFAbiLp7hFyV2HDiQvDbe8ya861GusLQXwdg6aDMAnAWDAYhHYwmgGcBeM0Ed6AGWXB+vb+OIHZcR6bOV9IuVACGQSaDnAqei+i6ATQDuCvBJzUiSvIh4OD3QQZKvvTstPi2Jde0FrzTmV61pz8pqrXKyxZzoLmKldFumPO/wOPbtMEUcVTlwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAxOC0wNy0wNlQxNjo1Nzo1NCswMDowMMhbOIcAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMTgtMDctMDZUMTY6NTc6NTQrMDA6MDC5BoA7AAAAAElFTkSuQmCC
      mediatype: image/png
  customresourcedefinitions:
    owned:
      - name: acicontainersoperators.aci.ctrl
        displayName: AciContainersOperator
        kind: AciContainersOperator
        version: v1alpha1
        channel: stable
        description: Aci Containers Operator
        resources:
          - version: apps/v1
            kind: Deployment
          - version: v1
            kind: Pod
    required: []
  install:
    strategy: deployment
    spec:
      permissions: []
      clusterPermissions:
        - serviceAccountName: aci-containers-operator
          rules:
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterroles
                - clusterrolebindings
              verbs:
                - '*'
            - apiGroups:
                - ''
              resources:
                - nodes
                - namespaces
                - configmaps
                - secrets
                - pods
                - services
                - serviceaccounts
                - serviceaccounts/token
                - endpoints
                - events
              verbs:
                - '*'
            - apiGroups:
                - networking.k8s.io
              resources:
                - networkpolicies
              verbs:
                - list
                - watch
                - get
            - apiGroups:
                - apps
              resources:
                - deployments
                - replicasets
                - daemonsets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - aci.ctrl
              resources:
                - acicontainersoperators
                - acicontainersoperators/status
                - acicontainersoperators/finalizers
              verbs:
                - '*'
            - apiGroups:
                - aci.snat
              resources:
                - snatpolicies
                - snatglobalinfos
                - rdconfigs
              verbs:
                - list
                - watch
                - get
            - apiGroups:
                - aci.snat
              resources:
                - nodeinfos
              verbs:
                - create
                - update
                - list
                - watch
                - get
            - apiGroups:
                - '*'
              resources:
                - '*'
              verbs:
                - '*'
      deployments:
        - name: aci-containers-operator
          spec:
            progressDeadlineSeconds: 600
            replicas: 1
            revisionHistoryLimit: 10
            selector:
              matchLabels:
                name: aci-containers-operator
                network-plugin: aci-containers
            strategy:
              type: Recreate
            relatedImages:
              - name: aci-containers-operator
                image: quay.io/noiro/aci-containers-operator@sha256:0db556fc8f188159fbb18797d8fcbd96303176d7803acaaf6bf604de8dcc0fd0
              - name: acc-provision-operator
                image: quay.io/noiro/acc-provision-operator@sha256:0fc4c11704dd26a3b10e73cbffca34addc1a968e7b55032533717c70696db2ab
            template:
              metadata:
                annotations:
                  scheduler.alpha.kubernetes.io/critical-pod: ''
                creationTimestamp: null
                labels:
                  name: aci-containers-operator
                  network-plugin: aci-containers
                name: aci-containers-operator
                namespace: aci-containers-system
              spec:
                containers:
                  - env:
                      - name: SYSTEM_NAMESPACE
                        value: aci-containers-system
                      - name: ACC_PROVISION_FLAVOR
                        value: openshift-4.7-openstack
                    image: quay.io/noiro/aci-containers-operator@sha256:0db556fc8f188159fbb18797d8fcbd96303176d7803acaaf6bf604de8dcc0fd0
                    imagePullPolicy: Always
                    name: aci-containers-operator
                    resources: {}
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    volumeMounts:
                      - mountPath: /usr/local/etc/aci-containers/
                        name: aci-operator-config
                      - mountPath: /usr/local/etc/acc-provision/
                        name: acc-provision-config
                  - env:
                      - name: ANSIBLE_GATHERING
                        value: explicit
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: ACC_PROVISION_FLAVOR
                        value: openshift-4.7-openstack
                      - name: ACC_PROVISION_INPUT_CR_NAME
                        value: accprovisioninput
                    image: quay.io/noiro/acc-provision-operator@sha256:0fc4c11704dd26a3b10e73cbffca34addc1a968e7b55032533717c70696db2ab
                    imagePullPolicy: Always
                    name: acc-provision-operator
                    resources: {}
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                dnsPolicy: ClusterFirst
                hostNetwork: true
                restartPolicy: Always
                schedulerName: default-scheduler
                securityContext: {}
                serviceAccount: aci-containers-operator
                serviceAccountName: aci-containers-operator
                terminationGracePeriodSeconds: 30
                tolerations:
                  - effect: NoSchedule
                    operator: Exists
                volumes:
                  - configMap:
                      items:
                        - key: spec
                          path: aci-operator.conf
                      name: aci-operator-config
                    name: aci-operator-config
                  - configMap:
                      items:
                        - key: spec
                          path: acc-provision-operator.conf
                      name: acc-provision-config
                    name: acc-provision-config
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
