# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: infoscale-vtas/infoscale-dr-webhook-cert
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: dns.infoscale.veritas.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: infoscale-dr-webhook-service
          namespace: infoscale-vtas
          path: /convert
      conversionReviewVersions:
      - v1
  group: infoscale.veritas.com
  names:
    kind: DNS
    listKind: DNSList
    plural: dns
    shortNames:
    - vxdns
    singular: dns
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.domain
      name: domain
      type: string
    - jsonPath: .status.dnsState
      name: State
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: DNS is the Schema for the DNSs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DNSSpec defines the desired state of DNS
            properties:
              cleanRRKeys:
                description: Set to 1 if you want to clean up all the existing DNS
                  records for the configured keys before adding new records Default
                  0
                type: boolean
              createPTR:
                description: Attribute to control if DNS online should create PTR
                  records for each RR of type A or AAAA. Default 0
                type: boolean
              dnsResOperation:
                description: User/Orchestrator initiated operation on DNS resource.
                  This operations will help in updating DNS Endpoints. Default "none"
                enum:
                - none
                - probe
                - online
                - offline
                type: string
              domain:
                description: Domain Name For DNS
                type: string
              iState:
                description: Intended state
                enum:
                - OFFLINE
                - FAULTED
                - ONLINE
                - INIT
                type: string
              offDelRR:
                description: Attribute to control if DNS offline should remove all
                  records defined by ResRecord Default 0
                type: boolean
              refreshInterval:
                description: This attribute represents the time interval in seconds
                  after which the DNS agent attempts to refresh the resource records
                  (RRs) on the DNS servers.
                format: int32
                type: integer
              resRecord:
                additionalProperties:
                  type: string
                description: "An association of DNS resource record value Specify
                  the key values in map format resRecord: \tkey1: value1 \tkey2: value2"
                type: object
              stealthMasters:
                description: The list of primary master name servers in the domain.
                items:
                  type: string
                type: array
              tsigKeyFile:
                description: Path for the file containing private TSIG key, required
                  for secure DNS updates. Configure only for UNIX based DNS server
                type: string
              ttl:
                description: Time to Live value, in seconds for DNS entries in the
                  zone Default 86400
                format: int32
                type: integer
              useGSSAPI:
                description: Set to 1 if the DNS server that you have configured is
                  a Windows DNS server and only if it accepts secure dynamic updates.
                  Default 0
                type: boolean
            required:
            - domain
            - resRecord
            type: object
          status:
            description: DNSStatus defines the observed state of DNS
            properties:
              dnsState:
                description: DNS state
                enum:
                - OFFLINE
                - FAULTED
                - ONLINE
                - INIT
                type: string
              groupid:
                description: Service group name for this DNS CR
                type: string
            required:
            - dnsState
            - groupid
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
