# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-prometheus-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redhat-marketplace-prometheus-operator
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-prometheus-operator
  namespace: openshift-redhat-marketplace
