# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: redhat-marketplace-prometheus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redhat-marketplace-prometheus
subjects:
- kind: ServiceAccount
  name: redhat-marketplace-prometheus
  namespace: openshift-redhat-marketplace
