apiVersion: v1
data:
  RELATED_IMAGE_CERTGEN: quay.io/cilium/certgen:v0.1.17@sha256:07959f3125dae659ab9036c14df046e2536f7a4f6c92dabda837388b0344dc74
  RELATED_IMAGE_CILIUM: quay.io/isovalent/cilium:v1.14.20-cee.1@sha256:42d7f944f8fc029782e5b7f10bcca98906ea67d227fd979655bcc6351de3170b
  RELATED_IMAGE_CILIUM_OPERATOR: quay.io/isovalent/operator-generic:v1.14.20-cee.1@sha256:364b0c687d9e3fc7740f421d342c00cf951c4b4786d06b51b952881ffe47ea36
  RELATED_IMAGE_CLUSTERMESH: quay.io/isovalent/clustermesh-apiserver:v1.14.20-cee.1@sha256:d4c6c587b252e8e721f06816b3aefa72113324aef9fb91247720d36ae8deabbc
  RELATED_IMAGE_CLUSTERMESH_ETCD: quay.io/coreos/etcd:v3.5.4@sha256:a67fb152d4c53223e96e818420c37f11d05c2d92cf62c05ca5604066c37295e9
  RELATED_IMAGE_ETCD_OPERATOR: quay.io/cilium/cilium-etcd-operator:v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
  RELATED_IMAGE_HUBBLE_ENTERPRISE: quay.io/isovalent/hubble-enterprise:v1.11.6@sha256:eb60d59d1fb1b136855829274b31805c4206f8d050c3bf068e63a552576c1b38
  RELATED_IMAGE_HUBBLE_ENTERPRISE_METADATA: quay.io/isovalent/hubble-enterprise-metadata:current@sha256:71cbb44a41b60ab64c6eae99f819796868a57234a5ff210598bd23b73b3b02c7
  RELATED_IMAGE_HUBBLE_ENTERPRISE_OPERATOR: quay.io/isovalent/hubble-enterprise-operator:v1.11.6@sha256:38253c2e17a8b2e88a226f0976c9cf4a00445212e2886e6f07cbb3a52757324f
  RELATED_IMAGE_HUBBLE_EXPORT: quay.io/isovalent/hubble-export-stdout:v1.0.4@sha256:a0ff77efa890478f18f5deeba2cd1e2dfd6c5c77981adac57b14d7734de71ff1
  RELATED_IMAGE_HUBBLE_EXPORT_FLUENTD: quay.io/isovalent/hubble-export-fluentd:v1.8.1@sha256:ce0cce63a8473d5ae73872fc65d82c54f2875511bb03f0bc8ee8480148c43ee1
  RELATED_IMAGE_HUBBLE_EXPORT_S3: quay.io/isovalent/hubble-export-s3:v1.0.2@sha256:518daea1074d260d824c3e03a93ab6b2a7a5f4c22b8e07938770add8257f4a52
  RELATED_IMAGE_HUBBLE_RBAC: quay.io/isovalent/hubble-rbac:v1.5.2@sha256:29309837e2246a1b6849d7a09d01ceebfdb43fa0ade973d14584f0e52b856b95
  RELATED_IMAGE_HUBBLE_RELAY: quay.io/isovalent/hubble-relay:v1.14.20-cee.1@sha256:caabdaae81ea8fdd73614d5d262e14995dd5a1c7bef9fff9005ee9d84dda482b
  RELATED_IMAGE_HUBBLE_UI_BE: quay.io/isovalent/hubble-ui-enterprise-backend:v1.2.2@sha256:4258f7e0bff24ff1e0b214f62b37097032b6426ba28edd3dfc4f451a34de0110
  RELATED_IMAGE_HUBBLE_UI_FE: quay.io/isovalent/hubble-ui-enterprise:v1.2.2@sha256:3e03a58f6eea5d2df195f42ee2817f7b28fa20bbe140f5086937eee8da1b8d56
  RELATED_IMAGE_HUBBLE_UI_OAUTH: quay.io/isovalent/oauth2-proxy:7.6.0@sha256:fc7046dee1a204163e68a6d9a42fec200b02129493a7d166f899dd12e2763364
  RELATED_IMAGE_NODEINIT: quay.io/cilium/startup-script:c54c7edeab7fde4da68e59acd319ab24af242c3f@sha256:a9d0f451353f1b2f29ed3868e230ecfae10150eab9fd521de67adb3c8ca9c33a
  RELATED_IMAGE_PREFLIGHT: quay.io/isovalent/cilium:v1.14.20-cee.1@sha256:42d7f944f8fc029782e5b7f10bcca98906ea67d227fd979655bcc6351de3170b
kind: ConfigMap
metadata:
  labels:
    name: cilium-ee-olm
  name: cilium-ee-olm-overrides
  namespace: cilium
