apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
        image: drbd9-rhel9
        match:
        - digest: sha256:c49ea53f169140c95054a357b479733bc445206439c1d59c62a1d36c91ded88e
          image: drbd9-rhel7
          osImage: Red Hat Enterprise Linux Server 7\.
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:c49ea53f169140c95054a357b479733bc445206439c1d59c62a1d36c91ded88e
          image: drbd9-rhel7
          osImage: CentOS Linux 7
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.2.15
      drbd-reactor:
        digest: sha256:95a2422d55394bcc322c5ce9c85e234b055d8c9976a69102ba5e12f7c24a311d
        image: drbd-reactor
        tag: v1.10.0
      drbd-shutdown-guard:
        digest: sha256:aa725af17193260429c10f7fc62712d943caf7ea68e789c58b58263985c27407
        image: drbd-shutdown-guard
        tag: v1.1.1
      ha-controller:
        digest: sha256:2bd0351429c466d921fc1d0cfc1b3122c67ebbc905e901369132b2c358f88d33
        image: linstor-k8s-ha-controller
        tag: v1.3.1
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:de3445f5bcc643e1b9d7c4e880fd289ca05dee300120d3b0d7a83498de91a79f
        image: linstor-affinity-controller
        tag: v1.3.0
      linstor-controller:
        digest: sha256:4aaa87ec39e261be7c46834e2a25d8c306688fc7b2b6c793bb09929996406b08
        image: linstor-controller
        tag: v1.32.3
      linstor-csi:
        digest: sha256:bd6181c265153b2eacf2536085fc93f33a21c243e44e69c89be47c4803ecf773
        image: linstor-csi
        tag: v1.10.1
      linstor-satellite:
        digest: sha256:1cff883efa5694babc51987a343c68bbe844427ca23d3744266679697d6b2cc9
        image: linstor-satellite
        tag: v1.32.3
      nfs-server:
        digest: sha256:a882baabb54182ac92e5fb66fcf15ee010c5235cfff89dba114dc2861820f179
        image: nfs-server
        tag: v1.10.1
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:ca1cd5129f245f363cdac2053c2f57f0ea67a5dd3649c92ed5b9ac49dfb87979
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:7212ede4dc7b6ecdf70029c3e19204424f40fb4af8795b8078fb41f88eb935be
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:20a1421a9d07970596f61e095d0edc8c9cc94ba12b7a680fbd079915aadd658c
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:2415d46464161df830d6c117433e9e07d25c2a63132ff9d563262f5923a1d8e4
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:3d93e9a0dee4341a9865c7dcd05c85214544b8a59b505eedbda0b09e72cb9a8f
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:8f7754782720186ec4a06c4341ba692dd2a691cd4c08ab5ff5f4e0309a0b7081
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:ac3963bfd4246da386b82d810a348e9d42a9e4b746acaf4dbcbe0766643cc2fa
        image: csi-external-health-monitor-controller
        tag: v0.16.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
