apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/version: 25.3.0
    stackable.tech/vendor: Stackable
  name: commons-operator-configmap
