apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:9d2e7e4336b0f97de65e08d95b89318b928f7685cd68c48e576bfc41c84d7a20
        image: drbd9-rhel9
        match:
        - digest: sha256:24a9a3d894668f142751611621fb17d567e4f6b385557784b2d19cf09936352c
          image: drbd9-rhel7
          osImage: Red Hat Enterprise Linux Server 7\.
          precompiled: true
        - digest: sha256:eb091a38c6811391f27df0b22c34cfe7df5ad69bcbe8ec37075edc50d732aeea
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:9d2e7e4336b0f97de65e08d95b89318b928f7685cd68c48e576bfc41c84d7a20
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:0e8baeab42e33c543cbdc784f4ff6559ce90ac0fab35c8f599440b8c79de0ffa
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:9d2e7e4336b0f97de65e08d95b89318b928f7685cd68c48e576bfc41c84d7a20
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:eb091a38c6811391f27df0b22c34cfe7df5ad69bcbe8ec37075edc50d732aeea
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:24a9a3d894668f142751611621fb17d567e4f6b385557784b2d19cf09936352c
          image: drbd9-rhel7
          osImage: CentOS Linux 7
          precompiled: true
        - digest: sha256:eb091a38c6811391f27df0b22c34cfe7df5ad69bcbe8ec37075edc50d732aeea
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:eb091a38c6811391f27df0b22c34cfe7df5ad69bcbe8ec37075edc50d732aeea
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:9d2e7e4336b0f97de65e08d95b89318b928f7685cd68c48e576bfc41c84d7a20
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:0e8baeab42e33c543cbdc784f4ff6559ce90ac0fab35c8f599440b8c79de0ffa
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:eb091a38c6811391f27df0b22c34cfe7df5ad69bcbe8ec37075edc50d732aeea
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:9d2e7e4336b0f97de65e08d95b89318b928f7685cd68c48e576bfc41c84d7a20
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:0e8baeab42e33c543cbdc784f4ff6559ce90ac0fab35c8f599440b8c79de0ffa
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:eb091a38c6811391f27df0b22c34cfe7df5ad69bcbe8ec37075edc50d732aeea
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:9d2e7e4336b0f97de65e08d95b89318b928f7685cd68c48e576bfc41c84d7a20
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:0e8baeab42e33c543cbdc784f4ff6559ce90ac0fab35c8f599440b8c79de0ffa
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.2.16
      drbd-reactor:
        digest: sha256:95a2422d55394bcc322c5ce9c85e234b055d8c9976a69102ba5e12f7c24a311d
        image: drbd-reactor
        tag: v1.10.0
      drbd-shutdown-guard:
        digest: sha256:16793f5aa10b46b198806c9198216fbd1aaec31269c28adea7e526dd17ff6f57
        image: drbd-shutdown-guard
        tag: v1.1.2
      ha-controller:
        digest: sha256:13bc9273fe4b752aaa9a0aa0add2c4261589f80fae2d367ab36728b8abc93d0e
        image: linstor-k8s-ha-controller
        tag: v1.3.2
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:de3445f5bcc643e1b9d7c4e880fd289ca05dee300120d3b0d7a83498de91a79f
        image: linstor-affinity-controller
        tag: v1.3.0
      linstor-controller:
        digest: sha256:4aaa87ec39e261be7c46834e2a25d8c306688fc7b2b6c793bb09929996406b08
        image: linstor-controller
        tag: v1.32.3
      linstor-csi:
        digest: sha256:051356c6c77fa5201125205bebd7bb915acf971945f5efdee2f30113e81d6e84
        image: linstor-csi
        tag: v1.10.5
      linstor-satellite:
        digest: sha256:1cff883efa5694babc51987a343c68bbe844427ca23d3744266679697d6b2cc9
        image: linstor-satellite
        tag: v1.32.3
      nfs-server:
        digest: sha256:5291967796205ad3d590cecd371dc41be4e57aab6d16a2dbb81d1c50330e5635
        image: nfs-server
        tag: v1.10.5
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:dc3467f43afb7207907d449c9f77cea3fc6f445497ffa875eec7d2389b28af76
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:4900006e6a4308a5e1124ab220bebb2844742f2a67d379ee4b628a82650291de
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:d1441ca3d11dde0da6f275567fadbf055d93db7fbc95a7b7b6e99b0f7f01d7e5
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:810a335ecb8e3d9779b8cdc355a764e50126fa69b6edfd2ce21cb692136fa97f
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:7d73b42253343784f1d2716cebb4071a2a081dd64a8ca3be74ded04606d9c36c
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:98cbc5588e6e7d708ae1527f11dfd9f6c801ef27878f06d82d2d9b1b2cad0578
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:ac3963bfd4246da386b82d810a348e9d42a9e4b746acaf4dbcbe0766643cc2fa
        image: csi-external-health-monitor-controller
        tag: v0.16.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
