apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-triliovault-config
  labels:
    app.kubernetes.io/instance: k8s-triliovault-config
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-triliovault
    app.kubernetes.io/part-of: k8s-triliovault
data:
  metadataJobResources: |-
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 10Mi
  dataJobResources: |-
    limits:
      cpu: 1500m
      memory: 5120Mi
    requests:
      cpu: 100m
      memory: 800Mi
  tvk: |-
    name: tvk-instance
