# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-triliovault-dex
    app.kubernetes.io/instance: k8s-triliovault-dex
    app.kubernetes.io/managed-by: k8s-triliovault
    app.kubernetes.io/name: k8s-triliovault
    app.kubernetes.io/part-of: k8s-triliovault
  name: k8s-triliovault-dex
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: telemetry
      port: 5558
      targetPort: telemetry
  selector:
    app: k8s-triliovault-dex
  type: NodePort
