apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: feppgpool2s.fep.fujitsu.io
spec:
  group: fep.fujitsu.io
  names:
    kind: FEPPgpool2
    listKind: FEPPgpool2List
    plural: feppgpool2s
    singular: feppgpool2
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: FEPPgpool2 is the Schema for the feppgpool2s API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of FEPPgpool2
            properties:
              clientAuthMethod:
                description: Client authentication method
                enum:
                - scram
                - SCRAM
                - md5
                type: string
              count:
                default: 2
                description: The number of FEP Pgpool2 containers to create.
                minimum: 1
                type: integer
              customhba:
                description: Congfiguration in pool_hba.conf.
                type: string
              customlogsize:
                default: 100Mi
                description: Log output persistent volume size
                pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                x-kubernetes-int-or-string: true
              customparams:
                description: the parameter set in Pgpool-II
                type: string
              custompcp:
                description: Configuration in pcp.conf
                type: string
              customsslcacert:
                description: Contents of the CA root certificate in PEM format
                type: string
              customsslcert:
                description: Contents of public x 509 client Certificate.
                type: string
              customsslkey:
                description: Contents of secret key used for the client certificate.
                type: string
              fepVersion:
                description: Use the specified version of the FEPPgpool2 image.
                maximum: 18
                minimum: 14
                type: integer
              fepclustername:
                default: new-fep
                description: Input FEPCluster name to connect to.
                type: string
              image:
                description: FEP Pgpool2 container image to use
                type: string
              imagePullPolicy:
                description: Pull policy for fep pgpool2 image
                type: string
              limits:
                description: Resource limit for feppgpool2 container
                properties:
                  cpu:
                    default: 400m
                    description: The number of CPUs (limit) to allocate to resources.limits.cpu.
                    pattern: ^(([0-9]+(\.[0-9]+)?)|(\.[0-9]+))(m|[Ee][-+]?[0-9]+)?$
                    x-kubernetes-preserve-unknown-fields: true
                  memory:
                    default: 512Mi
                    description: Memory size (limit) to allocate to resources.limits.memory.
                    pattern: ^(([0-9]+(\.[0-9]+)?)|(\.[0-9]+))(([kmKMGTPE])|([KMGTPE]i)|([Ee][+-]?([0-9]+)))?$
                    x-kubernetes-preserve-unknown-fields: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              requests:
                description: Resource request for feppgpool2 container
                properties:
                  cpu:
                    default: 200m
                    description: The number of CPUs (requests) to allocate to resources.requests.cpu.
                    pattern: ^(([0-9]+(\.[0-9]+)?)|(\.[0-9]+))(m|[Ee][-+]?[0-9]+)?$
                    x-kubernetes-preserve-unknown-fields: true
                  memory:
                    default: 256Mi
                    description: Memory size (request) to allocate for resources.requests.memory.
                    pattern: ^(([0-9]+(\.[0-9]+)?)|(\.[0-9]+))(([kmKMGTPE])|([KMGTPE]i)|([Ee][+-]?([0-9]+)))?$
                    x-kubernetes-preserve-unknown-fields: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              scram:
                properties:
                  pgpoolkeySecret:
                    description: Secret name storing the key to use in encryption/decryption
                    type: string
                  userinfoSecret:
                    description: User name added independently and secret name describing
                      password for the user
                    type: string
                type: object
              serviceport:
                default: 9999
                description: TCP port for connecting to FEP Pgpool2 container.
                type: integer
              statusport:
                default: 9898
                description: TCP port for connecting to PCP process.
                type: integer
              storageclassname:
                description: Storageclass of log output
                type: string
            required:
            - limits
            - requests
            type: object
          status:
            description: Status defines the observed state of FEPPgpool2
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
