apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata: {creationTimestamp: null, name: kcosuserrolemappings.keycloak.org}
spec:
  group: keycloak.org
  names: {kind: KCOSUserRoleMapping, listKind: KCOSUserRoleMappingList, plural: kcosuserrolemappings,
    singular: kcosuserrolemapping}
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KCOSUserRoleMapping is the Schema for the KCOSUserRoleMapping
          API.
        properties:
          apiVersion: {description: 'APIVersion defines the versioned schema of this
              representation of an object. Servers should convert recognized schemas
              to the latest internal value, and may reject unrecognized values. More
              info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
            type: string}
          kind: {description: 'Kind is a string value representing the REST resource
              this object represents. Servers may infer this from the endpoint the
              client submits requests to. Cannot be updated. In CamelCase. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds',
            type: string}
          metadata: {type: object}
          spec:
            description: KCOSUserRoleMappingSpec defines the desired state of KCOSUserRoleMapping.
            properties:
              clientRoles:
                additionalProperties:
                  items: {type: string}
                  type: array
                description: Client roles to be associated with the user
                type: object
              errorIfMissingClientRoles: {description: 'Treat as an error if client
                  roles referred by the mapping are missing in Keycloak. Otherwise,
                  missing roles are ignored.', type: boolean}
              errorIfMissingRealmRoles: {description: 'Treat as an error if realm
                  roles referred by the mapping are missing in Keycloak. Otherwise,
                  missing roles are ignored.', type: boolean}
              realmRoles:
                description: Realm roles to be associated with the user
                items: {type: string}
                type: array
              realmSelector:
                description: Selector for looking up KeycloakRealm Custom Resources.
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key: {description: key is the label key that the selector
                            applies to., type: string}
                        operator: {description: 'operator represents a key''s relationship
                            to a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.', type: string}
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items: {type: string}
                          type: array
                      required: [key, operator]
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties: {type: string}
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
              username: {description: Username., type: string}
            required: [username]
            type: object
          status:
            description: KCOSUserRoleMappingStatus defines the observed state of KCOSUserRoleMapping.
            properties:
              clientRoles:
                additionalProperties:
                  items: {type: string}
                  type: array
                description: Client roles associated with the user
                type: object
              message: {description: Human-readable message indicating details about
                  current operator phase or error., type: string}
              phase: {description: Current phase of the operator., type: string}
              ready: {description: True if all resources are in a ready state and
                  all work is done., type: boolean}
              realmRoles:
                description: Realm roles associated with the user
                items: {type: string}
                type: array
            required: [clientRoles, message, phase, ready, realmRoles]
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames: {kind: '', plural: ''}
  conditions: null
  storedVersions: null
