# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-triliovault-proxy-ca-bundle
  labels:
    app: k8s-triliovault-proxy-secret
    app.kubernetes.io/part-of: k8s-triliovault
    app.kubernetes.io/name: k8s-triliovault
    app.kubernetes.io/instance: k8s-triliovault-proxy-ca-bundle
    app.kubernetes.io/managed-by: k8s-triliovault
    config.openshift.io/inject-trusted-cabundle: "true"
data:
