# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: v1
kind: Secret
metadata:
  name: k8s-triliovault-web-backend-tvkconfigs
  labels:
    app.kubernetes.io/instance: k8s-triliovault-web-backend-tvkconfigs
    app.kubernetes.io/managed-by: k8s-triliovault
    app.kubernetes.io/name: k8s-triliovault
    app.kubernetes.io/part-of: k8s-triliovault
type: Opaque
