# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: policies.triliovault.trilio.io
spec:
  group: triliovault.trilio.io
  names:
    kind: Policy
    listKind: PolicyList
    plural: policies
    singular: policy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: policy
      type: string
    - jsonPath: .spec.default
      name: default
      type: string
    - jsonPath: .spec.[?(@.retentionConfig)]
      name: configuration
      priority: 10
      type: string
    - jsonPath: .spec.[?(@.timeoutConfig)]
      name: configuration
      priority: 10
      type: string
    - jsonPath: .spec.[?(@.cleanupConfig)]
      name: configuration
      priority: 10
      type: string
    - jsonPath: .spec.[?(@.scheduleConfig)]
      name: configuration
      priority: 10
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Policy is the Schema for the policies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PolicySpec defines the desired state of Policy
            properties:
              cleanupConfig:
                description: CleanupConfig field defines the configuration for Cleanup
                  policies
                properties:
                  backupDays:
                    description: BackupDays is the age of backups to be cleaned
                    format: int
                    minimum: 0
                    type: integer
                required:
                - backupDays
                type: object
              default:
                description: Default field states if the current type of policy is
                  default across the TV application
                type: boolean
              retentionConfig:
                description: RetentionConfig field defines the configuration for Retention
                  policies
                properties:
                  dateOfMonth:
                    description: DateOfMonth is Date of the month to maintain monthly
                      backup/restore resources
                    format: int
                    maximum: 28
                    minimum: 1
                    type: integer
                  dayOfWeek:
                    description: DayOfWeek is Day of the week to maintain weekly backup/restore
                      resources
                    enum:
                    - Monday
                    - Tuesday
                    - Wednesday
                    - Thursday
                    - Friday
                    - Saturday
                    - Sunday
                    type: string
                  latest:
                    description: Latest is the max number of latest backups to be
                      retained
                    format: int
                    minimum: 1
                    type: integer
                  monthOfYear:
                    description: MonthOfYear is the month of the backup to retain
                      for yearly backups
                    enum:
                    - January
                    - February
                    - March
                    - April
                    - May
                    - June
                    - July
                    - August
                    - September
                    - October
                    - November
                    - December
                    type: string
                  monthly:
                    description: Monthly is max number of backups to be retained in
                      a month
                    format: int
                    minimum: 1
                    type: integer
                  weekly:
                    description: Weekly is max number of backups to be retained in
                      a week
                    format: int
                    minimum: 1
                    type: integer
                  yearly:
                    description: Yearly is max number of backups to be retained in
                      a year
                    format: int
                    minimum: 1
                    type: integer
                type: object
              scheduleConfig:
                description: ScheduleConfig field defines the configuration for Schedule
                  policies
                properties:
                  schedule:
                    items:
                      type: string
                    type: array
                required:
                - schedule
                type: object
              timeoutConfig:
                description: TimeoutConfig field defines the configuration for timeout
                  policies
                type: object
              type:
                description: 'Type is a field of Policy spec, which defines the policy
                  type containing only 3 values: Retention, Timeout, Cleanup.'
                enum:
                - Timeout
                - Retention
                - Cleanup
                - Schedule
                type: string
            required:
            - type
            type: object
          status:
            description: PolicyStatus defines the observed state of Policy
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
