apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units:\n    - unit: &unitUri\n      \
    \  name: \"uri\"\n        regex: \"^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\\\\
    ?([^#]*))?(#(.*))?\"\n        examples:\n          - \"ldap://[2001:db8::7]/c=GB?objectClass?one\"\
    \n        comment: \"Specified in https://tools.ietf.org/html/rfc3986#appendix-B\"\
    \n\nproperties:\n  - property:\n      propertyNames:\n        - name: \"networkaddress.cache.ttl\"\
    \n          kind:\n            type: \"file\"\n            file: \"security.properties\"\
    \n      datatype:\n        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n\
    \        - fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n   \
    \     - name: \"namenode\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for successfully resolved domain names.\"\n      description:\
    \ \"TTL for successfully resolved domain names.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.ttl\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"security.properties\"\n      datatype:\n     \
    \   type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n        -\
    \ fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n        - name:\
    \ \"datanode\"\n          required: true\n      asOfVersion: \"0.0.0\"\n     \
    \ comment: \"TTL for successfully resolved domain names.\"\n      description:\
    \ \"TTL for successfully resolved domain names.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.ttl\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"security.properties\"\n      datatype:\n     \
    \   type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n        -\
    \ fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n        - name:\
    \ \"journalnode\"\n          required: true\n      asOfVersion: \"0.0.0\"\n  \
    \    comment: \"TTL for successfully resolved domain names.\"\n      description:\
    \ \"TTL for successfully resolved domain names.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"namenode\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for domain names that cannot be resolved.\"\n      description:\
    \ \"TTL for domain names that cannot be resolved.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"datanode\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for domain names that cannot be resolved.\"\n      description:\
    \ \"TTL for domain names that cannot be resolved.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"journalnode\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for domain names that cannot be resolved.\"\n      description:\
    \ \"TTL for domain names that cannot be resolved.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"dfs.namenode.name.dir\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"hdfs-site.xml\"\n      datatype:\n        type:\
    \ \"string\"\n        unit: *unitUri\n      roles:\n        - name: \"namenode\"\
    \n          required: false\n        - name: \"datanode\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n      description: \"Determines where on\
    \ the local filesystem the DFS name node should store the name table(fsimage).\
    \ If this is a comma-delimited list of directories then the name table is replicated\
    \ in all of the directories, for redundancy.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"dfs.datanode.data.dir\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"hdfs-site.xml\"\n      datatype:\n        type:\
    \ \"string\"\n        unit: *unitUri\n      roles:\n        - name: \"namenode\"\
    \n          required: false\n        - name: \"datanode\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n      description: \"Determines where on\
    \ the local filesystem an DFS data node should store its blocks. If this is a\
    \ comma-delimited list of directories, then data will be stored in all named directories,\
    \ typically on different devices. Directories that do not exist are ignored.\"\
    \n\n  - property:\n      propertyNames:\n        - name: \"dfs.replication\"\n\
    \          kind:\n            type: \"file\"\n            file: \"hdfs-site.xml\"\
    \n      datatype:\n        type: \"integer\"\n        min: \"1\"\n        max:\
    \ \"512\"\n      defaultValues:\n        - fromVersion: \"0.0.0\"\n          value:\
    \ \"3\"\n      roles:\n        - name: \"namenode\"\n          required: true\n\
    \        - name: \"datanode\"\n          required: true\n      asOfVersion: \"\
    0.0.0\"\n      description: \"Default block replication. The actual number of\
    \ replications can be specified when the file is created. The default is used\
    \ if replication is not specified in create time.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"fs.defaultFS\"\n          kind:\n            type: \"file\"\
    \n            file: \"core-site.xml\"\n      datatype:\n        type: \"string\"\
    \n        unit: *unitUri\n      roles:\n        - name: \"namenode\"\n       \
    \   required: false\n        - name: \"datanode\"\n          required: false\n\
    \      asOfVersion: \"0.0.0\"\n      description: \"The name of the default file\
    \ system. A URI whose scheme and authority determine the FileSystem implementation.\
    \ The uri's scheme determines the config property (fs.SCHEME.impl) naming the\
    \ FileSystem implementation class. The uri's authority is used to determine the\
    \ host, port, etc. for a filesystem.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"dfs.namenode.http-address\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"hdfs-site.xml\"\n      datatype:\n        type:\
    \ \"string\"\n      roles:\n        - name: \"namenode\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n      description: \"The address and the\
    \ base port where the dfs namenode web ui will listen on.\"\n\n  - property:\n\
    \      propertyNames:\n        - name: \"dfs.datanode.ipc.address\"\n        \
    \  kind:\n            type: \"file\"\n            file: \"hdfs-site.xml\"\n  \
    \    datatype:\n        type: \"string\"\n      roles:\n        - name: \"datanode\"\
    \n          required: false\n      asOfVersion: \"0.0.0\"\n      description:\
    \ \"The datanode ipc server address and port.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"dfs.datanode.address\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"hdfs-site.xml\"\n      datatype:\n        type:\
    \ \"string\"\n      roles:\n        - name: \"datanode\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n      description: \"The datanode server\
    \ address and port for data transfer.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"dfs.datanode.http.address\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"hdfs-site.xml\"\n      datatype:\n        type:\
    \ \"string\"\n      roles:\n        - name: \"datanode\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n      description: \"The datanode http\
    \ server address and port.\"\n\n  - property:\n      propertyNames:\n        -\
    \ name: \"dfs.journalnode.http-address\"\n          kind:\n            type: \"\
    file\"\n            file: \"hdfs-site.xml\"\n      datatype:\n        type: \"\
    string\"\n      roles:\n        - name: \"journalnode\"\n          required: false\n\
    \      asOfVersion: \"0.0.0\"\n      description: \"The address and port the JournalNode\
    \ HTTP server listens on. If the port is 0 then the server will start on a free\
    \ port.\"\n\n  - property:\n      propertyNames:\n        - name: \"dfs.journalnode.https-address\"\
    \n          kind:\n            type: \"file\"\n            file: \"hdfs-site.xml\"\
    \n      datatype:\n        type: \"string\"\n      roles:\n        - name: \"\
    journalnode\"\n          required: false\n      asOfVersion: \"0.0.0\"\n     \
    \ description: \"The address and port the JournalNode HTTPS server listens on.\
    \ If the port is 0 then the server will start on a free port.\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: hdfs-operator
    app.kubernetes.io/name: hdfs-operator
    app.kubernetes.io/version: 25.11.0
    stackable.tech/vendor: Stackable
  name: hdfs-operator-configmap
