apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: app-insights-operator
  name: app-insights-operator-scc-privileged-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: randoli-kube-state-metrics
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-otel-collector
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-prometheus-node-exporter
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-rok-vector
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-rok-vector-agent
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-rok-kubescape
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-rok-kubescape-operator
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-rok-kubescape-storage
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-rok-kubevuln
  namespace: randoli-agents
