apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
        image: drbd9-rhel9
        match:
        - digest: sha256:c49ea53f169140c95054a357b479733bc445206439c1d59c62a1d36c91ded88e
          image: drbd9-rhel7
          osImage: Red Hat Enterprise Linux Server 7\.
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:c49ea53f169140c95054a357b479733bc445206439c1d59c62a1d36c91ded88e
          image: drbd9-rhel7
          osImage: CentOS Linux 7
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:d74695bcc87c55b4a24bb8c52dadf7153505e834160b0a2923053f2203f831bc
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:e4a110d678ea944d6863f24262f297f1f92de3ed89a6d44aebff72a66037cac9
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:28d424cd652fd1cd880324f59b21c3adfb2e9f793563f57643d3ab09cf22543e
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.2.15
      drbd-reactor:
        digest: sha256:95a2422d55394bcc322c5ce9c85e234b055d8c9976a69102ba5e12f7c24a311d
        image: drbd-reactor
        tag: v1.10.0
      drbd-shutdown-guard:
        digest: sha256:aa725af17193260429c10f7fc62712d943caf7ea68e789c58b58263985c27407
        image: drbd-shutdown-guard
        tag: v1.1.1
      ha-controller:
        digest: sha256:2bd0351429c466d921fc1d0cfc1b3122c67ebbc905e901369132b2c358f88d33
        image: linstor-k8s-ha-controller
        tag: v1.3.1
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:de3445f5bcc643e1b9d7c4e880fd289ca05dee300120d3b0d7a83498de91a79f
        image: linstor-affinity-controller
        tag: v1.3.0
      linstor-controller:
        digest: sha256:4aaa87ec39e261be7c46834e2a25d8c306688fc7b2b6c793bb09929996406b08
        image: linstor-controller
        tag: v1.32.3
      linstor-csi:
        digest: sha256:b4366e7d89e4041338cac272f628ae78f3773391f20f494188df38de2d79d19d
        image: linstor-csi
        tag: v1.10.2
      linstor-satellite:
        digest: sha256:1cff883efa5694babc51987a343c68bbe844427ca23d3744266679697d6b2cc9
        image: linstor-satellite
        tag: v1.32.3
      nfs-server:
        digest: sha256:4811a59fa485a58555652299eb6fa4a6129de643ae61b872aae35337751c5dd7
        image: nfs-server
        tag: v1.10.2
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:d18dcbf74a23ed86c6052f56d758071e135a5aae17c44d96f2ebbf98f757c270
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:29b8447c74db78823ba2477fab7ec5d0f7503af63776afb7671b47da82d56286
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:14b8f0dc9b907c8736f65104fbcc365c8b7d09f80a56982590722c674d854956
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:0609a49d7b24d9c3e3aa94c7c0bfa2a8f316bf8b05a1470f39704b749a511ef5
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:e621929148d7c1909e40cbd63ce4d2e14223114ec8020631e55b516b6ebd4b10
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:086fd2d35fdf27a47b601f8448f9dc604e31b1c47d0c0a47a6a4d5add158e41f
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:ac3963bfd4246da386b82d810a348e9d42a9e4b746acaf4dbcbe0766643cc2fa
        image: csi-external-health-monitor-controller
        tag: v0.16.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
