apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  labels:
    redhat.marketplace.com/name: redhat-marketplace-operator
  name: remoteresources3s.marketplace.redhat.com
spec:
  group: marketplace.redhat.com
  names:
    kind: RemoteResourceS3
    listKind: RemoteResourceS3List
    plural: remoteresources3s
    singular: remoteresources3
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RemoteResourceS3 is the Schema for the remoteresources3s API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RemoteResourceS3Spec defines the desired state of RemoteResourceS3
            properties:
              auth:
                description: Auth provides options to authenticate to a remote location
                properties:
                  hmac:
                    description: Hmac is the credentials to access the storage location.
                    properties:
                      accessKeyId:
                        description: AccessKeyID is a unique identifier for an AWS
                          account and is used by AWS to look up your Secret Access
                          Key
                        type: string
                      accessKeyIdRef:
                        description: AccessKeyIDRef holds reference information to
                          an AccessKeyID stored in a secret on your cluster
                        properties:
                          valueFrom:
                            description: ValueFrom is the pointer to the secret key
                              ref
                            properties:
                              secretKeyRef:
                                description: SecretKeyRef is the pointer to the secret
                                  key ref
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must
                                      be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info:
                                      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                      TODO: Add other useful fields. apiVersion, kind,
                                      uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its
                                      key must be defined
                                    type: boolean
                                required:
                                - key
                                type: object
                                x-kubernetes-map-type: atomic
                            type: object
                        type: object
                      secretAccessKey:
                        description: SecretAccessKey is used by AWS to calculate a
                          request signature. Your SecretAccessKey is a shared secret
                          known only to you and AWS
                        type: string
                      secretAccessKeyRef:
                        description: SecretAccessKeyRef holds reference information
                          to an SecretAccessKey stored in a secret on your cluster
                        properties:
                          valueFrom:
                            description: ValueFrom is the pointer to the secret key
                              ref
                            properties:
                              secretKeyRef:
                                description: SecretKeyRef is the pointer to the secret
                                  key ref
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must
                                      be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info:
                                      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                      TODO: Add other useful fields. apiVersion, kind,
                                      uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its
                                      key must be defined
                                    type: boolean
                                required:
                                - key
                                type: object
                                x-kubernetes-map-type: atomic
                            type: object
                        type: object
                    type: object
                  iam:
                    description: Iam is the credentials for Iam auth.
                    properties:
                      apiKey:
                        description: APIKey is the API Key used to authenticate to
                          your IBM Cloud Object Storage instance
                        type: string
                      apiKeyRef:
                        description: APIKeyRef holds reference information used to
                          locate a secret which contains your IBM COS api key
                        properties:
                          valueFrom:
                            description: ValueFrom is the pointer to the secret key
                              ref
                            properties:
                              secretKeyRef:
                                description: SecretKeyRef is the pointer to the secret
                                  key ref
                                properties:
                                  key:
                                    description: The key of the secret to select from.  Must
                                      be a valid secret key.
                                    type: string
                                  name:
                                    description: 'Name of the referent. More info:
                                      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                      TODO: Add other useful fields. apiVersion, kind,
                                      uid?'
                                    type: string
                                  optional:
                                    description: Specify whether the Secret or its
                                      key must be defined
                                    type: boolean
                                required:
                                - key
                                type: object
                                x-kubernetes-map-type: atomic
                            type: object
                        type: object
                      grantType:
                        description: GrantType determines what authentication flow
                          will be used to generate an access token. GrantType for
                          IAM will usually be " "urn:ibm:params:oauth:grant-type:apikey""
                        type: string
                      responseType:
                        description: ResponseType specifies which grant type your
                          application is requesting. ResponseType for IAM will usually
                          be "cloud_iam"
                        type: string
                      url:
                        description: URL is the auth endpoint. URL for IAM will usually
                          be "https://iam.cloud.ibm.com/identity/token"
                        type: string
                    type: object
                type: object
              requests:
                description: Requests array contains information regarding the location
                  of your remote resource
                items:
                  description: Request holds requests that populate the Requests array
                  properties:
                    message:
                      description: Message of the request
                      type: string
                    optional:
                      description: Optional if downloading or applying a child resource
                        fails, RemoteResource will stop execution and report error
                        to .status. You can allow execution to continue by marking
                        a reference as optional.
                      type: boolean
                    options:
                      description: Options is the configurable options for the request
                      properties:
                        headers:
                          additionalProperties:
                            additionalProperties:
                              type: string
                            description: Header allows you to provide additional information
                              with your request
                            type: object
                          description: Headers of the request
                          type: object
                        uri:
                          description: URI of the request
                          type: string
                        url:
                          description: URL of the request
                          type: string
                      type: object
                    statusCode:
                      description: Status of the request
                      type: integer
                  type: object
                type: array
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: RemoteResourceS3Status defines the observed state of RemoteResourceS3
            properties:
              conditions:
                description: Conditions represent the latest available observations
                  of an object's state
                items:
                  description: "Condition represents an observation of an object's
                    state. Conditions are an extension mechanism intended to be used
                    when the details of an observation are not a priori known or would
                    not apply to all instances of a given Kind. \n Conditions should
                    be added to explicitly convey properties that users and components
                    care about rather than requiring those properties to be inferred
                    from other observations. Once defined, the meaning of a Condition
                    can not be changed arbitrarily - it becomes part of the API, and
                    has the same backwards- and forwards-compatibility concerns of
                    any other part of the API."
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      description: ConditionReason is intended to be a one-word, CamelCase
                        representation of the category of cause of the current status.
                        It is intended to be used in concise output, such as one-line
                        kubectl get output, and in summarizing occurrences of causes.
                      type: string
                    status:
                      type: string
                    type:
                      description: "ConditionType is the type of the condition and
                        is typically a CamelCased word or short phrase. \n Condition
                        types should indicate state in the \"abnormal-true\" polarity.
                        For example, if the condition indicates when a policy is invalid,
                        the \"is valid\" case is probably the norm, so the condition
                        should be called \"Invalid\"."
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              razee-logs:
                description: RazeeLogs is the logs from the controller
                properties:
                  error:
                    additionalProperties:
                      type: string
                    description: Log is a line of log from the controller
                    type: object
                type: object
              touched:
                description: Touched is if the status has been touched
                type: boolean
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
