apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: object-store-operator-tls
  creationTimestamp: null
  name: object-store-operator
spec:
  ports:
  - name: http
    port: 4221
    targetPort: 0
  selector:
    aistor.min.io/name: object-store-operator
    operator: leader
  type: ClusterIP
status:
  loadBalancer: {}
