---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: infoscale-vtas/infoscale-dr-webhook-cert
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: globalclustermemberships.infoscale.veritas.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: infoscale-dr-webhook-service
          namespace: infoscale-vtas
          path: /convert
      conversionReviewVersions:
      - v1
  group: infoscale.veritas.com
  names:
    kind: GlobalClusterMembership
    listKind: GlobalClusterMembershipList
    plural: globalclustermemberships
    shortNames:
    - gcm
    singular: globalclustermembership
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.localClusterName
      name: Cluster Name
      type: string
    - jsonPath: .status.phase
      name: Cluster State
      type: string
    - jsonPath: .status.globalClusterStatus
      name: Cluster State Deprecated
      type: string
    - jsonPath: .status.globalClusterProtocol
      name: Protocol
      type: string
    - jsonPath: .status.peerClusterLinkState
      name: Peer Link State
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: GlobalClusterMembership is the Schema for the globalclustermemberships
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GlobalClusterMembershipSpec defines the desired state of
              GlobalClusterMembership
            properties:
              backupClusterScopeCRD:
                description: Include Cluster-scoped Custom resources (CRDs) in drplan
                  backup, Default value is true
                type: boolean
              counterMissTolerance:
                description: Every 60 seconds, tries to heartbeat with peer clusters.
                  If heartbeat missed more than CounterMissTolerance times, then move
                  to FAULTED state. Default value is 5.
                maximum: 10
                minimum: 3
                type: integer
              datarepRefreshStatusFrequency:
                description: Refresh data replication status after specified minutes.
                  Default is 10 minutes.
                maximum: 30
                minimum: 5
                type: integer
              globalClusterOperation:
                description: 'User/Orchestrator initiated operation on Global Cluster
                  Membership. Default value is "none", idle state. "localbuild: User
                  seeding cluster membership, validating local copy of GCM.'
                enum:
                - none
                - localbuild
                type: string
              globalClusterProtocol:
                description: Protocol represents behavior of the cluster. Cluster
                  can support multiple protocols. Please see the controller logs for
                  list of supported protocols.
                type: integer
              globalMemberClusters:
                description: Details of Member Cluster(s)
                items:
                  properties:
                    clusterID:
                      description: Cluster ID
                      maxLength: 16
                      type: string
                    drControllerAddress:
                      description: Address Used For Communicating With Peer Clusterâ€™s
                        DR Controller
                      type: string
                    drControllerPort:
                      description: 'Port Used For DR Controller. Default: 14155'
                      type: string
                  required:
                  - clusterID
                  - drControllerAddress
                  type: object
                type: array
              localClusterName:
                description: Out Of MemberCluster(s), Specify Local Cluster Name
                maxLength: 16
                type: string
              maximumMetadataCopies:
                description: Application metadata backup maximum copies per DR plan.
                  Default value is 5.
                maximum: 20
                minimum: 5
                type: integer
              metadataBackupInterval:
                description: Application metadata backup sync frequency to DR site(s)
                  in minutes. Default value is 15.
                maximum: 60
                minimum: 5
                type: integer
            required:
            - globalMemberClusters
            - localClusterName
            type: object
          status:
            description: GlobalClusterMembershipStatus defines the observed state
              of GlobalClusterMembership
            properties:
              globalClusterProtocol:
                description: Protocol represents behavior of the cluster. Cluster
                  can support multiple protocols. Please see the controller logs for
                  list of supported protocols.
                type: integer
              licenseCRCreationTimestamp:
                description: Details of licensing CR creation time
                maxLength: 100
                type: string
              peerClusterLinkState:
                additionalProperties:
                  description: Possible peer link states
                  enum:
                  - UNKNOWN
                  - DISCOVER
                  - HB_ALIVE
                  - CONNECTED
                  - HB_DOWN_CONNECTED
                  - FAULTED
                  - EXITING
                  - EXITED
                  type: string
                description: Map of MemberCluster and PeerLinkState
                type: object
              phase:
                description: State of Global Cluster Membership
                enum:
                - UNKNOWN
                - DISCOVER_WAIT
                - ADMIN_WAIT
                - RUNNING
                - EXITING
                - EXITED
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
