apiVersion: v1
data:
  properties.yaml: "---\nversion: 0.1.0\nspec:\n  units: []\nproperties: []\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: opensearch-operator
    app.kubernetes.io/name: opensearch-operator
    app.kubernetes.io/version: 25.11.0
    stackable.tech/vendor: Stackable
  name: opensearch-operator-configmap
