apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"app.joget.com/v1alpha1","kind":"JogetDX8","metadata":{"name":"example-joget"},"spec":{"size":1}}]'
    capabilities: Seamless Upgrades
    categories: Application Runtime,Developer Tools
    certified: 'true'
    containerImage: registry.connect.redhat.com/joget/joget-dx8-operator@sha256:0fe3194771d9ab11e6a3b7f17beed3aabcf8a1bc1864083ca991a9458ab1b884
    createdAt: '2023-06-23 12:59:59'
    description: No-code/low-code application platform to visually build, run and
      maintain apps
    marketplace.openshift.io/support-workflow: https://marketplace.redhat.com/en-us/support
    support: Joget, Inc
  creationTimestamp: null
  name: joget-dx8-openshift-operator.v0.0.7
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Joget DX 8 on JBoss EAP 7
      displayName: Joget DX 8 on JBoss EAP 7
      kind: JogetDX8
      plural: JogetDX8
      singular: JogetDX8
      name: jogetdx8.app.joget.com
      version: v1alpha1
  description: "Joget DX is the next generation open source no-code / low-code application\
    \ platform that combines the best of Rapid Application Development, Business Process\
    \ Automation and Workflow Management. \nJoget DX empowers business users, non-coders\
    \ or coders with a single platform to easily build, deliver, monitor and maintain\
    \ enterprise applications.\n\nThis operator installs a Joget DX cluster running\
    \ on JBoss EAP 7.\n\n### Features\n* Build full-fledged apps e.g. CRM, HR, Healthcare,\
    \ etc\n* Drag and drop forms, lists, UI\n* Add workflow to automate processes\n\
    * Extend via plugins\n* Apps are mobile optimized and cloud ready\n* Download\
    \ ready-made apps from the Joget Marketplace\n\n### Before You Start\nDeploy a\
    \ [MySQL](https://docs.openshift.com/online/pro/using_images/db_images/mysql.html)\
    \ or [MariaDB](https://docs.openshift.com/online/pro/using_images/db_images/mariadb.html)\
    \ database.\n\n### Post Deployment\nAccess the service URL and complete the one-time\
    \ [Database Setup](https://dev.joget.org/community/display/DX7/Setting+Up+Database)\n\
    \n### More Information\nMore information about Joget DX on JBoss EAP 7 is available\
    \ in the [Joget Knowledge Base](https://dev.joget.org/community/display/DX8/Automated+Deployment+on+Red+Hat+OpenShift+with+the+Joget+Operator)\n"
  displayName: Joget DX 8 Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAWIAAAFiCAYAAADMXNJ6AAAACXBIWXMAABcSAAAXEgFnn9JSAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAIyhJREFUeNrsnU9220bWRys8mks97YmYFZhZgZAVmFmB4ck3Nb0C0yuIPO2JoR1IKwi1ghZXEGrSY2kF/vjshxiWJRJAvUJVAfeew8N0OqbJQuHih1d/8MuXL18cAADEY0YTAAAgYgCASXNCE0Dq/Ps/q/n+bd73z//v/y43tCKkzC/UiGFgqZ7t3xb6P+X9TF+Lxn92EfhrbPevB/3nnb6EO/33u728dxwtQMQwhgRbi7bQ91eZ/ZT7hqh3KmqR9B1HGRAxpCTdQoW7UPleTOSnbxty3pCiARFDDOkuMky4oXlsiFled3s5P9AsgIjBV7z164IW6Z2c/5EzqRkQMSDe+NyrlK9VzCRmQMQTF+9cpbvU91NaJUpiFilfMwiIiGE68l2odEtHjTfZtLyX8jXNgYhhfPItNfme0yJZ8NhIykgZEUOm8p2rfEvki5QBEcNw8j3T1LtylB3Gyr1KuaKmjIghLQEXmnzf0BqTQgb6LjUpM/sCEUOk9Ftq+qX0MG3q0sUlKRkRwzACXqh8Sb/wHLfuW9mioikQMdgLuNQEPNWFFs0d07ow1faSWnKlKZmyBSIGD/nWg29rN77yw62+11tPPug/fyXUHsJP9jZu/nOh73LHMaaFLXXZYs3yakQM3QW80lfOUrhtCParcHPZpF1LQM0tPBcjkPQVQkbEMF4BN3cdG/WevY2N7Qv3fc/l3KYKXjkG9hAxZC/g26Z4SVg/bJhUSzqH40hCRsSQkYBv3fdtHDccuVbHthZykYGYETIinuyJWrpvk/FTPEHr1VsbltSai1kGX1OdySFCXjHLAhFP5Ra2cunNgrh13/czIBmFvxOqpbxM7GL8qAGBaW+IeLSJ6DKxNHTTkC8nXby+UQu5SOgCLXdFaxaGIOIxpZ/1/vUO+UIHKaeSlOVOacUMC0Sc80lVujTqwLIqraLskKWUpQ+9TuDrUD9GxJQhesBGMOO6qxIhx97g6VFlXHFUEHHqJ4ycLB8ip1+2RhxvHytc/C1PpVxRcneFiFM9QaqIiUVuHSvm+U7uol9G7HMf9/1tzdFAxKmcENIZYwzG1VONKtLJpPtg6eJtDLXVdEz5CxFPLgXfNwRM+QGa/VGEHGNsgnSMiCeTgpnbCSkLWdLxkrszRDxEJ19oCh5yxy0EDLkI+VH76iVHABGH6tgyOPInAgaEfBRZOFRSOkPElh35TFPwUBPrSRUwBiHfq4w3tD4i9u28UoqQjjTU6riPjg1XIGyfLt2wsywYyEPEXh12yFIEe8LC0P1b5DjUXtiUKhBx5w46ZClCRppX3L5BxL4uJbAhVupJqWLJnGNE3KZjDjUrgjowpNTvCxXyEP2e/SoQ8cHOuFQJh75V4zYNUj0HpFSxHuAc+LTv/ytaHBE/1wFD14MZRYYczoW5puPQpTnZPGhJIEHEdceTFBy6RvbJfStFkIKBO8TvsFfF1EWsAxWSTkPWxUjBkPs5UgVOx1I3LqYs48mKWG+/rgNLmBQMpOP2vJ3qIN4kRTzAIg25wi9JwTDCdCzhJeTKvEnKeHIi1mk61wElzIwIGPs5FHpg+2p//pSIeLwdSA7u54B/xXvmBcOE7iol0IRaJj0pGU9GxIElzIohmKKMQw/kTebJ0ZMQcWAJU4qAqQs5ZKlCprcVYz+/Ri9i3dgk1FOVKUUAuOAD4KOX8ahFHHChBrMiAH4+30LOyx+1jEcr4oAS5rlcAPHOvVHKeEZH6MSNdgQkDPACOtvhbYCPlqS90eRNIk5cwmsXpibMblEA3c7FwoWZsz+6ZDwqEQecHfGW/VMBep2ToQbxRiXj2YgOeAgJy6DcH0gYoB86t36u4rTklabtUTAKEQeUsFxxrzmdALxkLKm1CCDjCx0Pyp7sSxNah/orkIRZKQdge76KOK0H0rNfDj3L/KAuAtyeyFV7joQBgqRjEeaV8ce+0UF6EnEECc/3byJLy0GASSynBBhpMs52UD1LEQdawYOEAfKX8e85rnjNtTSBhAEyR8sUH40/9lpLloh4gKsoEgYYh4zX+7f3hh95qjLOavVdViLW7fYsb2WQMEB8GcsOhpYDeOd614yIA0hYHl5ouecpEgZIR8alsYxf5TTHOAsRa83HslGRMMD4ZfxG76KTJ/lZEwFmSMhijTkSBkj2nJfQZVmCTH4mRQ6JuDKWMEkYIP1kfGv4kckP3iUtYr2tsHowIcuWAfJBxoSs9qY4dYkP3iUrYq0LWw7OlUgYIJtUbL1RkAzeJft8ySRrxHobIdI8N/pI9hMGyJAA+xn/keKOiqkm4spQwldIGCDbZHynydjMLbpPDSI+cgW0rAvf5L49HgAy/ipjq2fgnTrbqbDjE7FxXVhqS0gYYBwyFnl+Mvq4i9S2zUymRmw8X1hmSCx42jLAuNh74trwjvm3VAbwU0rEa2c3X3iJhAFGSensZlIkM784CRHr447eGX3c+xz3IwWA4+i0tlLven051wAYneilCeOpajI4t6S7Aowb4wcGR18CnUIiXhtJ+N4xOAcwlWRcObvBuyp2iSKqiI1LEkv2kACYlIxlqqtFvTh6iSKaiPUKVBl93HuWLwNMEilFWtSL32kwnFwiXjm7uvAl/RFgkql4py6xoIr1O6KIWBdufDD4KLkSlnRHgEnLWAR6Y/BR57EWesRKxFYJlrowADgNZPcGn/Mhxl4Ug4tYp51cGHzUJ+YLA4Cm4gfDu+Nq1CLWATqLNCxXvjXdDwAaMpZgZjGl7UIfVjzaRCzytNhXtKQkAQAvOMaiRHE55NziwUSsA3QWc4YpSQDAS6nYqkQhM7oGewL0kImYkgQADCFjCWoWJYrVUAN3g4hYJ0pbDNBRkgCANqydf4nidKjgN1Qirgw+44aSBAC0TMUS2CxKC2+0rJq3iHW6mu8KOhZuAEBXGcsm8hYLPYKv3A0qYh11tIj2a0oSANCDlfPfi+Ii9D4UswEawTcNb9lLAgB6puKdUaJdh/yewUSsadiiRrOiOwGAh4xFor4DdxdaZs0uEYtAfRdvMEAHAFY+SjYVBxExaRgAEkvFMnB36/kx56FS8UnCafgjT2JOH53wLi+5+Dan+RRP/tNFxz4hAyxPN/uX//2grw0PA4AeXvqvQSqurL+Y+cNDNQ3vPEUsJ+GcmRLJyLZoiLYW78LZ7Bviw72eFJf0FWjZl6W/vPH8mLe6B3LSidgiDTNdLV66XTx5nSf8leW7yQMGZCnqyvrkgFGyNhDxyjoVh0jED54ivt+fUHP6y2BJd6FlhNSl24arfd8pObJwpN/LdDbfDch+t5xIcGL8A0uLNExXCSre+nUxwp8oy1Ef9Om+AIcc4+uqtft5HCSNRLw/CXaeqYo0bF9qkM6y1PfTifz0P3SUHOClc0NE6vvczN+sBoxPDH9YaXBrSxr2Pw4LFa+8Xk20GeTWExHDsT7iO561ckZ74Jgl4r0ANp63u6RhP/mWKt9zWoRUDIOl4l8tptmeGIrAt+ZIGu5edlg6m/08xkhBKoYBUnFp4S6rlXW+gyP3TD1qLeBS7z7+3r/+RMIvsqAJ4BA6Rdb3Ym0yMHxiIAaZ6O87L4/d1Y6n37Um4FNaBMCMtae/TiUc+QZJi0Rcev55WUVHGj6eft8gYQDzVLzbv13FTsUWNWLfL8Hy1J/vMOrRWMoOAOG59EzFr2SczGcqm1ci1gUCvrIgDX9ry7mug5cr9Ack7A0DddA2FYtAfXdm8wqkvqWJ0vPPX019h7WGgCk/IGKIm4p9WOrd7LAiNhqkm2wafkbAYAdbqELXVCwXbp+neEiAWvb9wz414qXnb99O8ekbjRkQyDcMt/poHIA+qfhPzwpBr3DpU5pYGfxoEjBYcmUQEGC6+N6hX2jQGiYR61/ms4+BTFmbRA2vMQviA/08GNKf1jztG3yQ2Vv78/XKMygt+4TMvom49PzN11OYsiablbvvsyAgXApeIGFIJBX3cmOvTX8Mtrv8bczPG9NpfZVjClpIbjQF89w6sD5/B/fbSY8v6fskh+1YTx4t2YiAL+jOwZD5nisEDAGxGLTrNIY26/mXxIz+qUp47b4NxCHhcAKWx9MUSBgC4zt+1XnAuHNpwiC2/zqmOZ6UIYJzryWIiqaAAc/rjWeo6lSeOOn45XzLEjdjkbDOhhA5vKbbBkFmQlwyJxgiUXmKWFJxaxF3LU0UkSN/KhKWRt4h4WDIQNwCCUNEBi1PdCpN7AUkhveZP/yvnKetkYIHKUOUU1xxCUme79ee53rrMuxJhy8195TwTeYSXqqE2ZQnTBmCBRmQYir2EXHrxR1dasRF5KhPCh4nsiBjxZ7UkKiIP3v8+aKtiLvUiJcGPyo3CUtD3iHhIMh0NBlZLpEwpIj2yxuPj2jtjS4i9knEt7mdbHsJy5XsL8e0NGukDPGW+cCQUSr28UirAHvS8sNEwqexfszAAp7r931FHzTnk/tWCyYBQy5sPP980cZ/sw4fFu2qMqCE67l/SNiWrZYhqAVDVuish62niG0SsaeI73NYxKGliHd0PVOYDZHPnaAMSsuCrfr9KQ8aUh4mWFLyuUOWB4vOjzmwrYgvPH8EpYjpIYMcDMSl2+8XGrAKFe95hz8rb7cq5moCYhY/+GxlK21cHfoPji7o0PrwXx5f4g99HlSKnbHQRmZusG0KLlM95hOX71KlsHS2g9D3KprLsV5492334OEJeUhy6ZuIC8/fsEm0YeWy/ienpykMxqWZfMsA8m1yrolxpSW+MQpZPNZ3Guvi2H/QJhFvPEoTMm2tSKxjSg1MOgvPjbNNRCxNTquflyrgGNuybrU/3I2oPX2D28HtHdokYp8DuUmsMeeOerA11ILTChkrFXDM+e9yfm2k9DciGfu6rHAHxstmLW5rRlGW0N/C1DQ7pBYs9f8lEo4fMPQJ4TstEaSwCOlUZTwfQxvrBeXR4yMOuvRYIi48v/wmkY4qCeEzp6wZt5qCdzRF9Du8tUu3zHaq368cUSruWycufETsk4i3iXTWteMpypZ8ZJ9gBNyB+Yia3kfEF7FEvEmgwyJh21LEkgE5BNyRMc0xvvM8fouXaubHljj71FM3kTttiYRNSxFzJBxPwFoD/jsjCT/q3dNqLMfBoP8vOidiXeyQ5ZWQmrApn8Z0MmUm4HoWhLxyWXQkUxllemg10kHcW9d/Jll3EXuWJR5jDeQgYVPe8vTkaBJeaRkiFwHLmNDlBPrL3dAinueWhnWKGhvM2NxWsl9wnD5cP14nl32wb1TAm4kcIp9zYvBEvInQgRf697JvhH+yKZFwtBBxkcHXlQu1LE5YT3AKo895cSrlpudKNodEfBHpy/bpxPVz5ZCwv4QLFmgM3nelBJHDFqyj39znGBJQdPc5n1S8aSVi7Rw+DH2VlB/Gijk/ZBCCVXLDSjiXOvBU6r9d2qOvb9qL2LMs4Ya8rdVpPUjYj6Pb9IFpny20DJF6v73V8sOGo/bTHX/fYzd/7l+GEPF2wA4t8mAXNSRMGcK4T2gCZpzA/o5/0UXEZ5G+ZJdOLT+IaWpIOBcJl5qCUy5DXLlpDsB1Re4Q+i4W65SIC8/YPkSy4HYJCVOGQMAx8BlHeXZa4izAlxziYPJ4IyScuoDrZcl/JSxhEfCv0heQcHt8SzbPbS/8UiL2mbq2C9zB1y6PuZZIeJoCzmFZsgzCrWLXgBtPjq6fHj13hxeS/fMkaXmPPIh47/ovujlrK2If7gIeODlgbOSDhFOVsLTt2qW7Ku5eBXwdqX0K9+OTo/tcqF43Pk/eZHKACPl6YDHvPI7zT1PYTl5oLJ/Y/hDoIJ65A48aASQcUcCFCjjlO7XB95FuiFeWbYcqz7zS17v931ev+BtixsfO43gHT8Qhp66lnDRS5wYJBxGN3EZfuv6bhQ9VhhikBqxhaamvwg1fmpG/T6azvtl/l9BzoH3ac95GxD5ziEOlYTmw7zj1e18ckbC9cOS+OOUy2aMK+DpwW8xVvKVLa1BS0upfKuQQF6LgIvaZQ3wXqNNXnP69T0aWLdv2x7VLf3/gT5oGQ5YJ6+T7OvFDJkL+e/+drUszpmK3Lk2EOPCpT4JPmSXTkszkI4lPTuSUy2Ny97MKdTuud6ZLl+dq1g9as04hmFy0EXGRUOcvHEuYe6ci9ggw64OpL8iQO5/LEINxWnoo9ZX7GI0IcCPH1FfGcm557sIWNBFvDDsAJYn+3PN4IxMBr136c9aD1EA1/ZYZlB66IhfU65QCZwgRW7JyzJLoS0kT9BZQLhu0P2oZojL87Wfad8Z+7l1Ird/gDkKOwWnPti6ad6zWsyYsb4dYuNGPK0oSvfucnJg5lMJuNAU/GP/2pZvOeMxq/7t9N7j3eX7d0UTc+0AYCoCSRH/WNMFoBWw6JS2j8ksITrU8kcQisZMET4ylYy8JnzS8oxlGJ2DBbEpaJjNAJkWKNWKewkzbhRRwbinwXlPwxvN314tQSgT8la3BncXOox9JP9w8K2KDZ9X5niQM0Pl1LJ6oMK7bcO8UrMm/FjDz8W2n+pndfT5NxD4DdfcGV+w1/aQ3FU0wmttw7xScYeklNDLNr0r1AaiWpQnfq0Pqy0ZTZ0MTjOI23CsFT3wA7jmyeP7eSWInDvS83aIs8c8c4FWmKdBrRoQOcq8Q8Pfygwo4i31WUhmsYz8JPyYr4cYGNCKhV5n+jN7zgpkB8QNblW+V2xc/SeBEmjvqWNA//ea+COH9XhyXHX97Do9jGrr8UOW8kCmFRLymH3mzmcKPbCzBLTNOv83b56JLSWmiK+AOtV+lCXiX+485iXxikYZtKCZQeshh79sgEqb++wP3DQGPZp/t2ImYATo4JJ/SjW/3L+dajOKPqPRiKeB1jvXfpEXcuM0Ef0aRlBobj49dPoX0/2ai0/OhmMjv78KtXrhG/eDgmImYgQZjieXYWXXeazkx+ciFc7f/7Xdju5gaC3g9lZ0EY4sYbNszx9Qw1/eXbtUlKb4a4fE6Rb4IOKqIde4jadg4ZT3dbDoHtOZXefSlhTv8wNviwP8nf+7Qsv4F/RQBjzkRk4bDUImYpvTU5hYzD4Kd2FpWOZT05z0vEPLnprJAI+gDT6co4rMOnfeVgxCca7pc0hSDXAQGl4cO6i16yP/YhWHIMolM35MyWsXTZJ4XsU+SaivXkmYPyuv9ySodnHYep/wfXIQFPEcuAM0w9tJ/I99b7l52PLzgiIjlNs/yEdHPHEy5IrOAIzxv6umBUypTQBIXgOsJNYvZ/u2zgb84KW3AZCwJ5EgdEwD647N/+x0ing5SM/5LShV6NwIAafAQTMQ6leil/69wbNUXizeajtcIGSA9nhPx1uPzzkjDySLzYT/sX39rQi5oEgAvzELNybHIbJSUzxyDdKklZBnQk41U6mlEPHgUoBs+d/h3x0Qc4grBvNZ0O9I7eTWkvJEXsy0AwvH0/HpOxDvXf3I3Ih6BlPUuZqtSliv3HYkZ4Ie7/IXl570kYssvLHJ+zaHLjleusUhH55dvVcw7fX9gZRRMFJ85xNs2IvahIA1PR84NQQu3+v5V0O77Sqp/LvCsqAJE/JWHNiKWhPPB8AuXHLNJcPHk/bm7o6f/6tE9v/3lgzv8ZOpdyzs35A+h8ClNtBKx2ZfTsgQb/MBLHNqT16Sc1WHJ/ta1nzG06fAV7jp8LheOaSTiuzYi3nmeWJQlIEe6BIZgO5V13OvltmMK6zLg2uUC8jDBwVzTwbpfvnz58lxn+OLxmb/VB2X/OdeOgToA+M5jywtClwvHJsLvuPS42//96SD3S6UJmVPad7LymUr4DAkDwDN3zW3vKNr640PujfLSXhM7j88s9J2yBADAE56b8vmSiH3qPfMnQgYAgB6J2Gd565xEDADwLLddRLzx+IvkacIiYZ5+CwDwI7uhErFQ0t4AAB4iNpgTyGwJAICfueuSiIUtbQYAECkRH/oDAADQj5eqDbOuERoAAHrx4pL0QyLe0G4AAGbs+oiYRAwAYMddZxHrM5UeaTsAgEgiVja0HQCAP4ceK3ZMxJQnAAD8OTgdmEQMABCeOx8Rk4gBAPzZ9BaxDtixwg4AIJaI23wAAAAc5PHYQ2HbiJjyBABAoDRMIgYAyEHEGqnvaUsAgHiJWLimLQEAOvPYZn/3tiLe0J4AAJ1pFWIRMQBAOFq5s5WImU8MABBZxF0iNgAAfGV7bP4wIgYASCANdxKxjvwxjQ0AoB2VuYi7Gh4AYMK0mrbWV8SUJwAAjF3ZScR7w8uH8/gkAIBYIiYVAwAc5VFDKyIGAMghDfcSMeUJAIDIIiYVAwC8SOeyBCIGAIichnuLWI3P4g4AgB+5HEzEpGIAgJ+477KIw0rEl7Q7AMA/VH3/YG8R665CbI0JAOAp4hPPv1hS8WfaHwCe4bblf7fT1zFkX/S2t/67p1tQ/vs/q7P92+KF/369f114/NabtltehhDxtcr4lD4HkAz3B8R2THp3KrxD3OnDIrJCv/Pm6b8/IuguLuzNie8P2/8I+QJv6PsAZslx0zIJZinEBFl5hkkZpKuiiVi5RMQAz4q1KdBmEt353MZCEBH7UPl+AW8Ry3SNfSqWjnfB8YQJ3fY/fT30nboE8di7q3T+pdX4Im58EUQMY5PtppFqSbHjZO35568s+sUvX758sbqyyJc557hCpsLdqWw3NMuk0rDvrK/fLfrMieHvklT8gcMLCUv3Tl9y4jDQBb5peGt14bYUsQza+Y4+Aljw2BAu0oWX0rDvHbzZ6mKz0oT+OPli7zjMEEG8tXQ3DJpBC1ftPEUsU9bmVt/nxPj3IWIYihvEC2NIw+YiltHD/Y+8cswrBnukxnut4mXnP/BhbXAHViUr4saPRMRgKd+K1AtGaXhtkYatxxxMa8SNH1shY/BIG7V8NzQHGHpJ9pTYOb8JBdI/59YiPgn0m0nF0Cf9Sr+5ZoYDBPSS76yuyxD9M0giJhVDB2R5/Jr0C4HT8Hz/9rfB3do8hIhPAv52UjEgYEiFyuAzLkPdrc1C/Wpdf33F8YdnBCzLQgskDAOl4cL574UjaTjY4+FOArcBqRhqpAa8YuoZkIYHTMSkYmjwaf9aIGGIkIYlDPpOV5NVdOuQ3/NkgLaQ/SeWjj0opog8XLZkDjBEkvDc+W/6Xt/ZB2UW+i/QOH9Jt5hkCi6QMESkMgiAW9/HIKWSiJ2KuHTsVzwFZFBjNUTnBTiQhuUu3OJhFashvm+wecTPNIyI+DNdZNTIgNySFAyRJWyxgk642ffl5RDfeTZU42hCuqWbjBapBy+QMCRA5WzGpFZDfeHZwA20oo+MVsIFS5MhgTQsCfa1wUd9HPIZhYOKWNPSJ7oLEgYIIOEzZzNnWEpsg04wmEVor7X7NqADSBjAEpGwSUli6D49uIj1B1KiyJ9HJAwJpWFxikVJ4ibGwqMYiZiBu3GwRMKQiIQXzmbRxWOskDiL2H6lo0SRK5/YsAcSQoKdRUliPeQAXRIi1h/Mirv8eHQDLPkEaJmGxSGvDD5KVtBF81HMROx0I40t3SkrLilJQCISlqlqVk+NL2P+llkC7VnSpbJKw9zFQAoSlrpwZfRxH2MvRIouYm2Aj3StLOB5cpCChOv5whZ14W3oLS5zScR1iYJZFOlT0QSQAFZ14cdU7shnCTVu6ZhFkTTMlIAE0rBML7N66s86lb1RZgmd5DvHQo+U4Y4FYku42L/9adWfY86SSDkR1ws9buhyScKuahBTwjI4Z7XiTe68lyn9vlmCbV66b5tuQFowSAexJGw5OPfVMakNOicnYm2gJd0PAJSNsxmcEz6l+BDbFBNxPaXtPf0PYPJpuDKUsExVS3IcapbqAdBCOvVigOlKWBxgNUMiubpwFiJWSke9GGCKEpZz/53hRy5jbeiTvYgb9WLmF8enoAlgQAlbPmj4Y+pz4FNPxHW9mPnF8TmjCSBDCd+ksIQ5exGrjCvHs+5i84omgMASlrnClossZGfHMoffPsvlIOloJ6u74p4oBa0AASUs5QOrucJf95HIZZOqWWbHa+nYvzgmiBhykPBXV6Syj8ToRMzgHSIGJNyCt7ltUPXLly9fcj14/6UbR+Ff7EkMCUv4U6qLNkaTiBvJWG453tKVo8Dyc0hVwlc5SjhbEauMK2SMiCFLCZcBJCzLl8tc22SW8wFVGV/RtQflte6GBdBXwp+tJewyH7+Y5X5g9SqIjIelpAnAQ8KWyBYIRe7jFrMxHGBkPDisdISuEr4MIOGvG/mMYfB4NqJjvXLMMR6KcxZ3QAcJV852A59awkVOc4UnIWK9KhbIeDBKmgCOCPhs/xJRvjH+6FFJWMhyHvGxg+9sd/SHl/k15a0FIep5KNPTqgDn4egkPKpETDKOArVieE7CRaAwNEoJjzIRk4wHRU6MOSvtoHHeycX5z0B9bZQSHmUiJhkPiswFLWkG0HpwhYQRMTKOA+UJJFwvV34T4ONHL+HRi/iJjHkQaRjOdaI+TFPCSxeuBDgJCQujrRG/0GmqQFftqXO/P1nmNMPkJCyLNN6F6lMusz2FETEyToE/9ifNNc0wiXMo1NS0mq0bwbLlLsym1ol0OfR7TidzqBVPQ8JynDdImERs1aFEyJ85tUz5PbcnI0Dr8+VMU/DrgH/NVc5bWZKI+yVj6VS/Ox67ZMmaJhilhGVAbhdYwp+mKuFJJ+JGJ5N6l9Q2zznlSMUweAoW3mowmiyzqXc2HZUVGTPX2IZLmmAUEi4HSMGPeuGupt7ek0/ETzqfdAhmVJBwpnwOzDUFXwT+qyT4lFOZnkYi7paOJQXwHDx/1jRBlhKW43Y3gIRlcVWBhEnExzpkiCfMkooh1f5eaAoeYpzk475fcKFGxK07J7u3+SEroxbszJZ0H5+7YcoQQv1Yow0tj4j7dNaQyzjHDukn3ZCxHrBfb1XCO1ofEft03KUmB0oV3VMQ+xWnJeCVvobqyzI/mFWXR2CwrgW6h4LUjW9pjU7Iyc50tjQkXLpvA3EfBpKwXIT/QMIk4lAdeq2dGdrDs+3iClj67JALliSwLLkTQsShOzer8TqemPuTsqAZRi9gScHr/bHmLggRD9bRhx7wyB2WPo9XwAILNBBx1I4vSa8iHR+FzePDhoKhB+GaMDsGEZOOM4IT1rbfzbXfxVqWTwpGxKTjDGE6m135QV4XEY8jtWBEnPyJIimFmRXPczXlfWc9028t4JgX+ltNwTuOCiLO5cSpIqaWlGHgrl0fkpLXMnL6rZEl6yueS4iIcz2Z5ES6dJQrmmz3J/SCZjjYZ+pXCqs5P0ofpqSEiMeQbGKOaqfIe2qMSctXuNEUTBkCEY/qZJu7uKPcKSEDPospn+SJyvfrHYsKeEM3RcRjPgHltlzS4NTrxzf7k305sQux/N7ChX8OXB+kDrxmH2lEPDUhF5qQpyzk0Q7caUmqaMg31XECuTu5ZI43Ip66kEsXZ1lqKilsFBvIa+ItGq/Uj+ej3pkxEIeIASHnt2etSnehr0LfcxmIRcCIGFoKWcQ0pcc0JfmMOxVuLd2mfHOc/YKAETH0kEDhplVDHlzGOnB6pq/Fk/exXAjvVcAVAkbE4CcLSchTmfbWfBKKiMN3U5larjWSbKdQ/tlq+q04ixAx2N4ml46FIXCYGxXwhqZAxBBWyrWQX9Ea4L7XfytWwiFiGF7IddkitdVZMAy3Kt+KpkDEEF/IKe3UBWGRwbeK9IuIIW0pzxtSpnQxDqT0cK3y3dAciBjykvJChSxiZivOPOV7zT7AiBjGJeV6ty+SMvIFRAyRpTx3ae8ENiVkvu/GfSs78CBORAwTFnMt5YK0PEjq3Wjy3TDgBogYXkrLtZQXiNlMvBsVL6kXEDF0FvNZQ8ryzvS4w0ip4U7Fe4d4ARFDKDnXu5A1X1NcUFJL906lu6F3ACKGmHKeu28b6khqrjfakf89hmlzsoLtoSHdHUkXEDHkmKCbW0zW0hZilzpkpdpO/7lOtHe1eNk6EhAxTE3YxZN/VRh99K4hW6eJdkeLAyIGAAA3owkAABAxAMCk+X8BBgAX/nT9i5comwAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: joget-dx8-openshift-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: joget-dx8-openshift-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: joget-dx8-openshift-operator
            spec:
              containers:
              - env:
                - name: ANSIBLE_DEBUG_LOGS
                  value: "True"
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: joget-dx8-openshift-operator
                - name: RELATED_IMAGE_JOGET
                  value: quay.io/joget/joget-dx8-eap7@sha256:e3942b7e258de18d97d5b5794d24b2b982e83823729975d621d2782d551d92da
                image: registry.connect.redhat.com/joget/joget-dx8-operator@sha256:0fe3194771d9ab11e6a3b7f17beed3aabcf8a1bc1864083ca991a9458ab1b884
                imagePullPolicy: Always
                name: operator
                resources: {}
                #volumeMounts:
                #- mountPath: /tmp/ansible-operator/runner
                #  name: runner
              serviceAccountName: joget-dx8-openshift-operator
              #volumes:
              #- emptyDir: {}
              #  name: runner
      permissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - routes
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - joget-dx8-openshift-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ''
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - app.joget.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: joget-dx8-openshift-operator
      clusterPermissions:
      - rules:
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          - rolebindings
          - clusterroles
          - clusterrolebindings
          verbs:
          - "*"
        serviceAccountName: joget-dx8-openshift-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - lowcode
  - appdev
  - workflow
  - automation
  links:
  - name: Joget
    url: https://www.joget.com
  maintainers:
  - email: info@joget.com
    name: Joget, Inc
  maturity: alpha
  provider:
    name: Joget, Inc
  relatedImages:
    - name: joget-dx8-openshift-operator
      image: registry.connect.redhat.com/joget/joget-dx8-operator@sha256:0fe3194771d9ab11e6a3b7f17beed3aabcf8a1bc1864083ca991a9458ab1b884
    - name: joget-dx8-eap7
      image: quay.io/joget/joget-dx8-eap7@sha256:e3942b7e258de18d97d5b5794d24b2b982e83823729975d621d2782d551d92da
  version: 0.0.7
status:
  certsLastUpdated: null
  certsRotateAt: null
  lastTransitionTime: null
  lastUpdateTime: null
