apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units: []\n\nproperties:\n  - property:\n\
    \      propertyNames:\n        - name: \"networkaddress.cache.ttl\"\n        \
    \  kind:\n            type: \"file\"\n            file: \"security.properties\"\
    \n      datatype:\n        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n\
    \        - fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n   \
    \     - name: \"node\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for successfully resolved domain names.\"\n      description:\
    \ \"TTL for successfully resolved domain names.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"node\"\n          required: true\n      asOfVersion: \"0.0.0\"\n \
    \     comment: \"TTL for host names that cannot be resolved.\"\n      description:\
    \ \"TTL for host names that cannot be resolved.\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nifi-operator
    app.kubernetes.io/name: nifi-operator
    app.kubernetes.io/version: 25.7.0
    stackable.tech/vendor: Stackable
  name: nifi-operator-configmap
