apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: bonree-operator
    app.kubernetes.io/version: 1.1.0
  name: bonree-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: server-port
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: bonree-operator
status:
  loadBalancer: {}
