apiVersion: v1
data:
  kove_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMDCCAragAwIBAgIUaKHMbTToafnoXHkU+tTMN8SKBMowCgYIKoZIzj0EAwMw
    ZjELMAkGA1UEBhMCVVMxETAPBgNVBAgMCElsbGlub2lzMRAwDgYDVQQHDAdDaGlj
    YWdvMRswGQYDVQQKDBJLb3ZlIEhvbGRpbmdzLCBJbmMxFTATBgNVBAMMDEtvdmUg
    Um9vdCBDQTAeFw0yNTA2MTcyMzQ1MjRaFw0zNTA2MTgyMzQ1MjRaMGYxCzAJBgNV
    BAYTAlVTMREwDwYDVQQIDAhJbGxpbm9pczEQMA4GA1UEBwwHQ2hpY2FnbzEbMBkG
    A1UECgwSS292ZSBIb2xkaW5ncywgSW5jMRUwEwYDVQQDDAxLb3ZlIFJvb3QgQ0Ew
    djAQBgcqhkjOPQIBBgUrgQQAIgNiAAQXxWT+f7POt0dDGGEl064p+XuqCnL7bp+d
    OUWfT25A1jM+dG+CWpdSI8mwGFrj3BJwZaRyBrvsOFNHvYh4C1fJfTRlxag6ZRkI
    aywaCK3Wc7ygU/g8R6z11IajC1mMsY+jggEjMIIBHzAMBgNVHRMEBTADAQH/MB0G
    A1UdDgQWBBT3quw6yw3BysS/2udblEu04toQLjCBowYDVR0jBIGbMIGYgBT3quw6
    yw3BysS/2udblEu04toQLqFqpGgwZjELMAkGA1UEBhMCVVMxETAPBgNVBAgMCEls
    bGlub2lzMRAwDgYDVQQHDAdDaGljYWdvMRswGQYDVQQKDBJLb3ZlIEhvbGRpbmdz
    LCBJbmMxFTATBgNVBAMMDEtvdmUgUm9vdCBDQYIUaKHMbTToafnoXHkU+tTMN8SK
    BMowDgYDVR0PAQH/BAQDAgGGMBwGA1UdEQQVMBOBEXNlY3VyaXR5QGtvdmUuY29t
    MBwGA1UdEgQVMBOBEXNlY3VyaXR5QGtvdmUuY29tMAoGCCqGSM49BAMDA2gAMGUC
    MQCyulfif6KwetgtWcaowE+Z3TAdq8IjCd1NS0lz5JHAyuqB+4B4iiQSJHAzyPxw
    GkYCMDqnnD2PFieBi0PhkhOZr263ufh56hqCW2qqx9zb4PNGt2jEmXWLCGVrKFgQ
    7+cbFA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGKTCCBBGgAwIBAgIJAK2ICJ+pPnFMMA0GCSqGSIb3DQEBCwUAMIGDMQswCQYD
    VQQGEwJVUzERMA8GA1UECAwISWxsaW5vaXMxEDAOBgNVBAcMB0NoaWNhZ28xFjAU
    BgNVBAoMDUtvdmUgSU8sIEluYy4xFTATBgNVBAMMDEtvdmUgUm9vdCBDQTEgMB4G
    CSqGSIb3DQEJARYRc2VjdXJpdHlAa292ZS5uZXQwHhcNMTUwNzIzMTgwNzMyWhcN
    MjUwNzIzMTgwNzMyWjCBgzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCElsbGlub2lz
    MRAwDgYDVQQHDAdDaGljYWdvMRYwFAYDVQQKDA1Lb3ZlIElPLCBJbmMuMRUwEwYD
    VQQDDAxLb3ZlIFJvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXNlY3VyaXR5QGtvdmUu
    bmV0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2UgFF2f+OBjbN2Qv
    7zahoVGVRyhyiun4Na8cXmw3co/J/rSQ7ral9cZraT6scmply7wOPEUDGMu999dy
    MP5ASS8YZUrhJzfgUANutXxYHmqzeTD4QmP9PJC+uytEnq6xy4MlMjkfVHVLEbRh
    kJs1/PJS09Ze0ka6UCOMoj3sMCJ0+jTZj/D3T5TIAga+ttOYQ/wjNsIbqalMybmN
    9SPkZHD/mw1MZOgJSD4CT18/5TZyabIIDSBPVOF+emh4r3vxDllcDhvDZgxwijr2
    whMULLjnFWTc3VFa5n+SbH7o3IO4NlNxHHcOMj2tOTGsWhUQ7cW46B52iWaTPD7b
    udCJvxVeRAGIRcMzXG0mLBoGkVu7/lxjQFsgVeX0D8nhfeAsqLJ6x1ESfw1F6bdY
    ISLkVKABT8KR3njoH0b5ibphsrrXqceQxWB82mhxfK+cTXticJLx2VXldxEQDV4b
    SVQ8JKLd3Mar9bDl/QDgmMNeQq1UI+wWteW0QnDZsV2AXVuNbRj67BkSt1fY4byb
    bYP2Z16XusQkosv3rawHV9JVjlgQUb3YyoYeKBRf2mqB4CWmN/aAqo6f4Ns56Q05
    UvIB6t7oi1EBsOwUmN4EfKB3hmlz0cr+5w4uINKlD55CJ+9izsQ4bXEuqSsa5lzk
    0nl+VVKAqJPe1PYycbFK79Q9kl0CAwEAAaOBnTCBmjAdBgNVHQ4EFgQU2JhQcNz+
    vosKpErvZ5OXK9cJ+IQwHwYDVR0jBBgwFoAU2JhQcNz+vosKpErvZ5OXK9cJ+IQw
    DAYDVR0TBAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwHAYDVR0RBBUwE4ERc2VjdXJp
    dHlAa292ZS5uZXQwHAYDVR0SBBUwE4ERc2VjdXJpdHlAa292ZS5uZXQwDQYJKoZI
    hvcNAQELBQADggIBAFp8pngs1Kg1aQjO3ZdSXusMDwvFNQyxEF1WRriOc6XcAOwP
    U/qjhvi8eBhi0cpBwgNITDBbKqAq5BYIQ5VEN8pp7ellzFLlOvZl5R/QEzSVFsI/
    M86ds6H4swHs8QA4SnFFDBLHRg9W19luMS4lAX+XGy8Js9lHrc/Sm/+D+hpJ+d4d
    9e5EbDuTCB9omH7wRV+1nPCGCX6d1aJoxDZNKK8VFy+UxLaNY3vstzrmblFr7Hy8
    W+rSBvXEb+5S/F9N92MH9FniY33neN1AnsgesYQQQYBiK6XuwTY6Olw25oeSOjJ/
    6/VTfiu6wA2YKqpnDHOeGEZ9v8/ksKDqiOsTPZc6VRE/+xfk/0EhRAtObzYMW97/
    LLZfHJ3LRCSL92g6rupDKOt/na8r95cGOv6NtnfFDiCJiJBAfvtUEm8PrJxFXRJs
    QOgkXgdl1Ej6IY4beh35DSazVDR17cpaBArkdHpdBdnc9NMux9e0uN7JwCp5sXXp
    7fispvtyss5VMb2L5a6KH+Nkj/jJ7iaJ0QIynd0OMUgHPoTYozMkQZ0RJ00y7Mhl
    8jZRw8T1Iz5iJSkhPUP7wCd2AQfwoU9Tf4SWmHlKYUDhhthFoj7Wu/suiGETgdRY
    PXfHAQ5qZaBy5DjyUgnfarZW4NfFGF+1GLhAk0I3preOiVFiNX5USa75u4ys
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kove-operator-kove-ca
