---
catalog_templates:
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: commons-operator.v25.7.0
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: commons-operator.v25.7.0
  - template_name: v4.20.yaml
    channels: [stable]
