# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  creationTimestamp: null
  name: sriovvrbclusterconfigs.sriovvrb.intel.com
spec:
  group: sriovvrb.intel.com
  names:
    kind: SriovVrbClusterConfig
    listKind: SriovVrbClusterConfigList
    plural: sriovvrbclusterconfigs
    shortNames:
    - vrbcc
    singular: sriovvrbclusterconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: SriovVrbClusterConfig is the Schema for the SriovVrbClusterConfigs
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SriovVrbClusterConfigSpec defines the desired state of SriovVrbClusterConfig
            properties:
              acceleratorSelector:
                description: Selector describes target accelerator for this spec
                properties:
                  deviceID:
                    type: string
                  driver:
                    pattern: (pci-pf-stub|pci_pf_stub|igb_uio|vfio-pci)
                    type: string
                  maxVirtualFunctions:
                    type: integer
                  pciAddress:
                    pattern: ^[a-fA-F0-9]{4}:[a-fA-F0-9]{2}:[01][a-fA-F0-9]\.[0-7]$
                    type: string
                  vendorID:
                    type: string
                type: object
              drainSkip:
                description: Skips drain process when true; default false. Should
                  be true if operator is running on SNO
                type: boolean
              nodeSelector:
                additionalProperties:
                  type: string
                description: Selector describes target node for this spec
                type: object
              physicalFunction:
                description: Physical function (card) config
                properties:
                  bbDevConfig:
                    description: BBDevConfig is a config for PF's queues
                    properties:
                      vrb1:
                        description: VRB1BBDevConfig specifies variables to configure
                          ACC200 with
                        properties:
                          downlink4G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          downlink5G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          fftLut:
                            description: FFTLutParam specifies variables required
                              to use custom fft bin file
                            properties:
                              fftChecksum:
                                description: SHA-1 checksum of .tar.gz SRS-FFT File
                                pattern: ^([a-fA-F0-9]{40})?$
                                type: string
                              fftUrl:
                                description: Path to .tar.gz SRS-FFT file
                                pattern: ^((http|https)://.*\.tar\.gz)?$
                                type: string
                            required:
                            - fftChecksum
                            - fftUrl
                            type: object
                          maxQueueSize:
                            maximum: 1024
                            minimum: 1024
                            type: integer
                          numVfBundles:
                            maximum: 64
                            minimum: 1
                            type: integer
                          pfMode:
                            enum:
                            - false
                            type: boolean
                          qfft:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          uplink4G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          uplink5G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                        required:
                        - downlink4G
                        - downlink5G
                        - numVfBundles
                        - qfft
                        - uplink4G
                        - uplink5G
                        type: object
                      vrb2:
                        properties:
                          downlink4G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          downlink5G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          fftLut:
                            description: FFTLutParam specifies variables required
                              to use custom fft bin file
                            properties:
                              fftChecksum:
                                description: SHA-1 checksum of .tar.gz SRS-FFT File
                                pattern: ^([a-fA-F0-9]{40})?$
                                type: string
                              fftUrl:
                                description: Path to .tar.gz SRS-FFT file
                                pattern: ^((http|https)://.*\.tar\.gz)?$
                                type: string
                            required:
                            - fftChecksum
                            - fftUrl
                            type: object
                          maxQueueSize:
                            maximum: 1024
                            minimum: 1024
                            type: integer
                          numVfBundles:
                            maximum: 64
                            minimum: 1
                            type: integer
                          pfMode:
                            enum:
                            - false
                            type: boolean
                          qfft:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          qmld:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          uplink4G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                          uplink5G:
                            properties:
                              aqDepthLog2:
                                maximum: 12
                                minimum: 1
                                type: integer
                              numAqsPerGroups:
                                maximum: 64
                                minimum: 1
                                type: integer
                              numQueueGroups:
                                maximum: 32
                                minimum: 0
                                type: integer
                            required:
                            - aqDepthLog2
                            - numAqsPerGroups
                            - numQueueGroups
                            type: object
                        required:
                        - downlink4G
                        - downlink5G
                        - numVfBundles
                        - qfft
                        - qmld
                        - uplink4G
                        - uplink5G
                        type: object
                    type: object
                  pfDriver:
                    description: PFDriver to bound the PFs to
                    pattern: (pci-pf-stub|pci_pf_stub|igb_uio|vfio-pci)
                    type: string
                  vfAmount:
                    description: VFAmount is an amount of VFs to be created
                    minimum: 1
                    type: integer
                  vfDriver:
                    description: VFDriver to bound the VFs to
                    type: string
                required:
                - bbDevConfig
                - pfDriver
                - vfAmount
                - vfDriver
                type: object
              priority:
                description: Higher priority policies can override lower ones.
                type: integer
            required:
            - physicalFunction
            type: object
          status:
            description: SriovVrbClusterConfigStatus defines the observed state of
              SriovVrbClusterConfig
            properties:
              lastSyncError:
                type: string
              syncStatus:
                description: Indicates the synchronization status of the CR
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
