---
apiVersion: v1
data:
  properties.yaml: |
    version: 0.1.0
    spec:
      units:
        - unit: &unitDirectory
            name: "directory"
            regex: "^/|(/[\\w-]+)+$"
            examples:
              - "/tmp/xyz"
        - unit: &unitPort
            name: "port"
            regex: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"

    properties:
      - property: &tickTime
          propertyNames:
            - name: "tickTime"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "integer"
            min: "1"
          recommendedValues:
            - fromVersion: "0.0.0"
              value: "3000"
          roles:
            - name: "server"
              required: true
          asOfVersion: "0.0.0"
          comment: "ZK only checks whether the value is 0, all other values (including negative ones) are considered valid, we disallow negative values here, see QuorumPeerConfig.java"
          description: "The basic time unit in milliseconds used by ZooKeeper. It is used to do heartbeats and the minimum session timeout will be twice the tickTime."

      - property: &dataDir
          propertyNames:
            - name: "dataDir"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
            unit: *unitDirectory
          defaultValues:
            - value: "/tmp/zookeeper"
          recommendedValues:
            - value: "/stackable/data"
          roles:
            - name: "server"
              required: true
          asOfVersion: "0.0.0"
          comment: "See QuorumPeerConfig.java"
          description: "The location where ZooKeeper will store the in-memory database snapshots and, unless specified otherwise, the transaction log of updates to the database. Note: Be careful where you put the transaction log. A dedicated transaction log device is key to consistent good performance. Putting the log on a busy device will adversely affect performance."

      # Role required "true" is only correct if more than one zookeeper instances is used.
      - property: &initLimit
          propertyNames:
            - name: "initLimit"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "integer"
            min: "1"
          recommendedValues:
            - value: "5"
          roles:
            - name: "server"
              required: true
          asOfVersion: "0.0.0"
          comment: "ZK only checks whether the value is 0, all other values (including negative ones) are considered valid, we disallow negative values here, see QuorumPeerConfig.java"
          description: "Amount of time, in ticks (see `tickTime`), to allow followers to connect and sync to a leader. Increased this value as needed, if the amount of data managed by ZooKeeper is large."

      # Role required "true" is only correct if more than one zookeeper instances is used.
      - property: &syncLimit
          propertyNames:
            - name: "syncLimit"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "integer"
            min: "1"
          recommendedValues:
            - value: "2"
          roles:
            - name: "server"
              required: true
          asOfVersion: "0.0.0"
          comment: "ZK only checks whether the value is 0, all other values (including negative ones) are considered valid, we disallow negative values here, see QuorumPeerConfig.java"
          description: "Amount of time, in ticks (see `tickTime`), to allow followers to sync with ZooKeeper. If followers fall too far behind a leader, they will be dropped. In other words: The number of ticks that can pass between sending a request and getting an acknowledgment before a follower is dropped."

      ##########################
      # Ports
      ##########################
      - property: &clientPort
          propertyNames:
            - name: "clientPort"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "integer"
            unit: *unitPort
            min: "1024"
            max: "65535"
          defaultValues:
            - value: "2181"
          roles:
            - name: "server"
              required: false
          asOfVersion: "0.0.0"
          description: "The plaintext port to listen on for client connections."

      - property: &secureClientPort
          propertyNames:
            - name: "secureClientPort"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "integer"
            unit: *unitPort
            min: "1024"
            max: "65535"
          roles:
            - name: "server"
              required: false
          asOfVersion: "0.0.0"
          description: "The secure port to listen on for secure client connections using TLS/SSL."

      - property: &adminServerPort
          propertyNames:
            - name: "admin.serverPort"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "integer"
            unit: *unitPort
            min: "1024"
            max: "65535"
          defaultValues:
            - value: "8080"
          roles:
            - name: "server"
              required: true
          asOfVersion: "0.0.0"
          description: "The port the embedded Jetty server listens on."

      ##########################
      # Quorum TLS
      ##########################
      - property: &sslQuorum
          propertyNames:
            - name: "sslQuorum"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "bool"
          defaultValues:
            - value: "false"
          recommendedValues:
            - value: "true"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "Enables encrypted quorum communication."

      - property: &sslQuorumClientAuth
          propertyNames:
            - name: "ssl.quorum.clientAuth"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          allowedValues:
            - "none"
            - "want"
            - "need"
          defaultValues:
            - value: "need"
          recommendedValues:
            - value: "need"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.7"
          description: "Specifies options to authenticate ssl connections from other quorum members."

      - property: &sslQuorumHostNameVerification
          propertyNames:
            - name: "ssl.quorum.hostnameVerification"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "bool"
          recommendedValues:
            - value: "true"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.7"
          description: "Specifies whether the hostname verification is enabled in quorum TLS negotiation process. Disabling it only recommended for testing purposes."

      - property: &sslQuorumKeyStoreLocation
          propertyNames:
            - name: "ssl.quorum.keyStore.location"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
            unit: *unitDirectory
          defaultValues:
            - value: "/stackable/tls/quorum"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "Specifies the file path to a Java keystore containing the local credentials to be used for quorum TLS connections."

      - property: &sslQuorumKeyStorePassword
          propertyNames:
            - name: "ssl.quorum.keyStore.password"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "The password to unlock the quorum keystore."

      - property: &sslQuorumTrustStoreLocation
          propertyNames:
            - name: "ssl.quorum.trustStore.location"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
            unit: *unitDirectory
          defaultValues:
            - value: "/stackable/tls/quorum"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "Specifies the file path to a Java truststore containing the local credentials to be used for quorum TLS connections."

      - property: &sslQuorumTrustStorePassword
          propertyNames:
            - name: "ssl.quorum.trustStore.password"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "The password to unlock the quorum truststore."

      ##########################
      # Client TLS
      ##########################
      - property: &sslClientAuth
          propertyNames:
            - name: "ssl.clientAuth"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          allowedValues:
            - "none"
            - "want"
            - "need"
          defaultValues:
            - value: "need"
          recommendedValues:
            - value: "need"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.7"
          description: "Specifies options to authenticate ssl connections from clients."

      - property: &sslHostNameVerification
          propertyNames:
            - name: "ssl.hostnameVerification"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "bool"
          recommendedValues:
            - value: "true"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.7"
          description: "Specifies whether the hostname verification is enabled in client TLS negotiation process. Disabling it only recommended for testing purposes."

      - property: &sslKeyStoreLocation
          propertyNames:
            - name: "ssl.keyStore.location"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
            unit: *unitDirectory
          defaultValues:
            - value: "/stackable/tls/client"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "Specifies the file path to a Java keystore containing the local credentials to be used for client TLS connections."

      - property: &sslKeyStorePassword
          propertyNames:
            - name: "ssl.keyStore.password"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "The password to unlock the client keystore."

      - property: &sslTrustStoreLocation
          propertyNames:
            - name: "ssl.trustStore.location"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
            unit: *unitDirectory
          defaultValues:
            - value: "/stackable/tls/client"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "Specifies the file path to a Java truststore containing the remote credentials to be used for client TLS connections."

      - property: &sslTrustStorePassword
          propertyNames:
            - name: "ssl.trustStore.password"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          roles:
            - name: "server"
              required: false
          asOfVersion: "3.5.5"
          description: "The password to unlock the client truststore."
      ##########################
      # Common TLS
      ##########################
      - property: &authProviderX509
          propertyNames:
            - name: "authProvider.x509"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          roles:
            - name: "server"
              required: false
          asOfVersion: "0.0.0"
          description: "Used for secure client authentication."

      - property: &serverCnxnFactory
          propertyNames:
            - name: "serverCnxnFactory"
              kind:
                type: "file"
                file: "zoo.cfg"
          datatype:
            type: "string"
          roles:
            - name: "server"
              required: false
          asOfVersion: "0.0.0"
          description: "This should be set to NettyServerCnxnFactory in order to use TLS based server communication."
kind: ConfigMap
metadata:
  name: zookeeper-operator-configmap
  labels:
    app.kubernetes.io/name: zookeeper-operator
    app.kubernetes.io/instance: zookeeper-operator
    app.kubernetes.io/version: "23.4.0"
