---
catalog_templates:
  - template_name: template.yaml
    channels: ["stable"]
    skips:
      - kubecost-operator.v3.0.0
      - kubecost-operator.v3.0.1
      - kubecost-operator.v3.0.2
      - kubecost-operator.v3.0.3
      - kubecost-operator.v3.0.4
      - kubecost-operator.v3.0.5
      - kubecost-operator.v3.0.6
      - kubecost-operator.v3.1.0
      - kubecost-operator.v3.1.1
      - kubecost-operator.v3.1.2
