apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units: []\nproperties:\n  - property:\
    \ &credentialsSecret\n      propertyNames:\n        - name: \"credentialsSecret\"\
    \n          kind:\n            type: \"env\"\n      datatype:\n        type: \"\
    string\"\n      roles:\n        - name: \"node\"\n          required: true\n \
    \     asOfVersion: \"0.0.0\"\n      description: \"The secret where the Superset\
    \ credentials are stored.\"\n  - property: &rowLimit\n      propertyNames:\n \
    \       - name: \"ROW_LIMIT\"\n          kind:\n            type: \"file\"\n \
    \           file: \"superset_config.py\"\n      datatype:\n        type: \"integer\"\
    \n      defaultValues:\n        - fromVersion: \"0.0.0\"\n          value: \"\
    50000\"\n      recommendedValues:\n        - fromVersion: \"0.0.0\"\n        \
    \  value: \"50000\"\n      roles:\n        - name: \"node\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n      description: \"Row limit when requesting\
    \ chart data. Corresponds to ROW_LIMIT\"\n  - property: &webserverTimeout\n  \
    \    propertyNames:\n        - name: \"SUPERSET_WEBSERVER_TIMEOUT\"\n        \
    \  kind:\n            type: \"file\"\n            file: \"superset_config.py\"\
    \n      datatype:\n        type: \"integer\"\n      defaultValues:\n        -\
    \ fromVersion: \"0.0.0\"\n          value: \"60\" # 1 min\n      recommendedValues:\n\
    \        # The default timeout of Superset is 60s which is way to low when querying\
    \ \"big data\" systems.\n        # Especially Trino queries often take longer.\n\
    \        # see [the Superset docs](https://superset.apache.org/docs/frequently-asked-questions#why-are-my-queries-timing-out).\n\
    \        - fromVersion: \"0.0.0\"\n          value: \"300\" # 5 min\n      roles:\n\
    \        - name: \"node\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      description: \"Maximum number of seconds a Superset request can take before\
    \ timing out. This settings effect the maximum duration a query to an underlying\
    \ datasource can take. If you get timeout errors before your query returns the\
    \ result you can need to increase this timeout. Corresponds to SUPERSET_WEBSERVER_TIMEOUT\"\
    \n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: superset-operator
    app.kubernetes.io/name: superset-operator
    app.kubernetes.io/version: 25.7.0
    stackable.tech/vendor: Stackable
  name: superset-operator-configmap
