apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units:\n    - unit: &unitNodeEnvironment\n\
    \        name: \"node_environment\"\n        regex: \"^[a-z][a-z0-9_]*[a-z0-9]$\"\
    \n        examples:\n          - \"a1_2_3b\"\n    - unit: &unitMemory\n      \
    \  name: \"memory\"\n        regex: \"(^\\\\p{N}+)(?:\\\\s*)((?:b|k|m|g|t|p|kb|mb|gb|tb|pb|B|K|M|G|T|P|KB|MB|GB|TB|PB)\\\
    \\b$)\"\n        examples:\n          - \"1024b\"\n          - \"1024kb\"\n  \
    \        - \"500m\"\n          - \"1g\"\n\n###################################################################################################\n\
    # node.properties\n###################################################################################################\n\
    properties:\n  - property:\n      propertyNames:\n        - name: \"networkaddress.cache.ttl\"\
    \n          kind:\n            type: \"file\"\n            file: \"security.properties\"\
    \n      datatype:\n        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n\
    \        - fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n   \
    \     - name: \"coordinator\"\n          required: true\n      asOfVersion: \"\
    0.0.0\"\n      comment: \"TTL for successfully resolved domain names.\"\n    \
    \  description: \"TTL for successfully resolved domain names.\"\n\n  - property:\n\
    \      propertyNames:\n        - name: \"networkaddress.cache.ttl\"\n        \
    \  kind:\n            type: \"file\"\n            file: \"security.properties\"\
    \n      datatype:\n        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n\
    \        - fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n   \
    \     - name: \"worker\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for successfully resolved domain names.\"\n      description:\
    \ \"TTL for successfully resolved domain names.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"coordinator\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      comment: \"TTL for domain names that cannot be resolved.\"\n      description:\
    \ \"TTL for domain names that cannot be resolved.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"worker\"\n          required: true\n      asOfVersion: \"0.0.0\"\n\
    \      comment: \"TTL for domain names that cannot be resolved.\"\n      description:\
    \ \"TTL for domain names that cannot be resolved.\"\n\n\n  - property: &nodeEnvironment\n\
    \      propertyNames:\n        - name: \"node.environment\"\n          kind:\n\
    \            type: \"file\"\n            file: \"node.properties\"\n      datatype:\n\
    \        type: \"string\"\n        unit: *unitNodeEnvironment\n      roles:\n\
    \        - name: \"coordinator\"\n          required: true\n        - name: \"\
    worker\"\n          required: true\n      asOfVersion: \"0.0.0\"\n\n###################################################################################################\n\
    # config.properties\n###################################################################################################\n\
    \  - property: &coordinator\n      propertyNames:\n        - name: \"coordinator\"\
    \n          kind:\n            type: \"file\"\n            file: \"config.properties\"\
    \n      datatype:\n        type: \"bool\"\n      defaultValues:\n        - fromVersion:\
    \ \"0.0.0\"\n          value: \"false\"\n      roles:\n        - name: \"coordinator\"\
    \n          required: true\n        - name: \"worker\"\n          required: true\n\
    \      asOfVersion: \"0.0.0\"\n\n  - property: &nodeSchedulerIncludeCoordinator\n\
    \      propertyNames:\n        - name: \"node-scheduler.include-coordinator\"\n\
    \          kind:\n            type: \"file\"\n            file: \"config.properties\"\
    \n      datatype:\n        type: \"bool\"\n      defaultValues:\n        - fromVersion:\
    \ \"0.0.0\"\n          value: \"false\"\n      roles:\n        - name: \"coordinator\"\
    \n          required: true\n      asOfVersion: \"0.0.0\"\n\n  - property: &httpServerHttpPort\n\
    \      propertyNames:\n        - name: \"http-server.http.port\"\n          kind:\n\
    \            type: \"file\"\n            file: \"config.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"1024\"\n        max: \"65535\"\n  \
    \    defaultValues:\n        - fromVersion: \"0.0.0\"\n          value: \"8080\"\
    \n      roles:\n        - name: \"coordinator\"\n          required: false\n \
    \       - name: \"worker\"\n          required: false\n      asOfVersion: \"0.0.0\"\
    \n\n  - property: &httpServerHttpsPort\n      propertyNames:\n        - name:\
    \ \"http-server.https.port\"\n          kind:\n            type: \"file\"\n  \
    \          file: \"config.properties\"\n      datatype:\n        type: \"integer\"\
    \n        min: \"1024\"\n        max: \"65535\"\n      defaultValues:\n      \
    \  - fromVersion: \"0.0.0\"\n          value: \"8443\"\n      roles:\n       \
    \ - name: \"coordinator\"\n          required: false\n        - name: \"worker\"\
    \n          required: false\n      asOfVersion: \"0.0.0\"\n\n  - property: &queryMaxMemory\n\
    \      propertyNames:\n        - name: \"query.max-memory\"\n          kind:\n\
    \            type: \"file\"\n            file: \"config.properties\"\n      datatype:\n\
    \        type: \"string\"\n        unit: *unitMemory\n      defaultValues:\n \
    \       - fromVersion: \"0.0.0\"\n          value: \"50GB\"\n      roles:\n  \
    \      - name: \"coordinator\"\n          required: true\n        - name: \"worker\"\
    \n          required: true\n      asOfVersion: \"0.0.0\"\n\n  - property: &queryMaxMemoryPerNode\n\
    \      propertyNames:\n        - name: \"query.max-memory-per-node\"\n       \
    \   kind:\n            type: \"file\"\n            file: \"config.properties\"\
    \n      datatype:\n        type: \"string\"\n        unit: *unitMemory\n     \
    \ roles:\n        - name: \"coordinator\"\n          required: false\n       \
    \ - name: \"worker\"\n          required: false\n      asOfVersion: \"0.0.0\"\n\
    \n  - property: &httpServerAuthenticationType\n      propertyNames:\n        -\
    \ name: \"http-server.authentication.type\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"config.properties\"\n      datatype:\n       \
    \ type: \"string\"\n      roles:\n        - name: \"coordinator\"\n          required:\
    \ false\n      asOfVersion: \"0.0.0\"\n\n###################################################################################################\n\
    # jvm.config\n###################################################################################################\n\
    \n###################################################################################################\n\
    # log.properties\n###################################################################################################\n\
    \n  - property: &ioTrino\n      propertyNames:\n        - name: \"io.trino\"\n\
    \          kind:\n            type: \"file\"\n            file: \"log.properties\"\
    \n      datatype:\n        type: \"string\"\n      defaultValues:\n        - fromVersion:\
    \ \"0.0.0\"\n          value: \"INFO\"\n      allowedValues:\n        - \"INFO\"\
    \n        - \"DEBUG\"\n        - \"WARN\"\n        - \"ERROR\"\n      roles:\n\
    \        - name: \"coordinator\"\n          required: true\n        - name: \"\
    worker\"\n          required: true\n      asOfVersion: \"0.0.0\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: trino-operator
    app.kubernetes.io/name: trino-operator
    app.kubernetes.io/version: 25.7.0
    stackable.tech/vendor: Stackable
  name: trino-operator-configmap
