apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: systems.operator.ionir.com
spec:
  group: operator.ionir.com
  names:
    kind: System
    listKind: SystemList
    plural: systems
    singular: system
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: System installs Ionir service in the cluster
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: SystemSpec defines the desired state of System
              properties:
                control:
                  description: Stop/start Ionir service
                  enum:
                    - stop
                    - start
                  type: string
                extraParameters:
                  description: Array of extra parameters
                  items:
                    type: string
                  type: array
                imageRegistry:
                  description: Registry for Ionir images
                  type: string
                ionirLicense:
                  description: Ionir license key
                  type: string
                profile:
                  description: Ionir's cluster profile. Select 'minimal' for 3 workers cluster and 'scaled' for 5 workers or more
                  enum:
                    - minimal
                    - scaled
                  type: string
                tag:
                  description: Ionir deployment tag
                  type: string
              required:
                - profile
              type: object
            status:
              description: SystemStatus defines the observed state of System
              properties:
                generation:
                  description: Current handled generation
                  format: int64
                  type: integer
                lastError:
                  description: Last error message
                  type: string
                progress:
                  description: Progress
                  type: integer
                spec:
                  description: Current handled spec
                  properties:
                    control:
                      description: Stop/start Ionir service
                      enum:
                        - stop
                        - start
                      type: string
                    extraParameters:
                      description: Array of extra parameters
                      items:
                        type: string
                      type: array
                    imageRegistry:
                      description: Registry for Ionir images
                      type: string
                    ionirLicense:
                      description: Ionir license key
                      type: string
                    profile:
                      description: Ionir's cluster profile. Select 'minimal' for 3 workers cluster and 'scaled' for 5 workers or more
                      enum:
                        - minimal
                        - scaled
                      type: string
                    tag:
                      description: Ionir deployment tag
                      type: string
                  required:
                    - profile
                  type: object
                status:
                  description: Status
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
