apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "anzo.cambridgesemantics.com/v1",
          "kind": "Anzo",
          "metadata": {
            "name": "agent01"
          },
          "spec": {
            "nodeConfig": {
              "spec": {
                "replicas": 1,
                "selector": {
                  "matchLabels": {
                    "app": "anzo"
                  }
                },
                "serviceName": "anzo-agent01",
                "template": {
                  "metadata": {
                    "labels": {
                      "app": "anzo"
                    }
                  },
                  "spec": {
                    "containers": [
                      {
                        "image": "registry.connect.redhat.com/cambridgesemantics/anzo:5.3.1",
                        "name": "anzo",
                        "resources": {
                          "limits": {
                            "cpu": "4000m",
                            "memory": "12Gi"
                          },
                          "requests": {
                            "cpu": "4000m",
                            "memory": "12Gi"
                          }
                        }
                      }
                    ],
                    "serviceAccountName": "anzo-operator"
                  }
                }
              }
            },
            "role": "AnzoAgent"
          },
          "status": {}
        }
      ]
    capabilities: Basic Install
    categories: Big Data
    certified: "true"
    containerImage: registry.connect.redhat.com/cambridgesemantics/anzo-operator:2.0.1
    createdAt: 2022-01-18
    description: kubernetes operator for Anzo
    operators.operatorframework.io/builder: operator-sdk-v1.15.0+git
    operators.operatorframework.io/project_layout: unknown
    repository: ""
    support: Cambridge Semantics
  name: anzo-operator.v2.0.102
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Anzo is the Schema for the anzos API
      displayName: Anzo Operator
      kind: Anzo
      name: anzos.anzo.cambridgesemantics.com
      resources:
      - kind: Anzo
        name: anzo-cr
        version: v1
      - kind: ConfigMap
        name: k8s-configmap
        version: v1
      - kind: Deployment
        name: k8s-deployment
        version: v1
      - kind: Event
        name: k8s-event
        version: v1
      - kind: Pod
        name: k8s-pod
        version: v1
      - kind: PersistentVolumeClaim
        name: k8s-pvc
        version: v1
      - kind: ReplicaSet
        name: k8s-replicaset
        version: v1
      - kind: Secret
        name: k8s-secret
        version: v1
      - kind: Service
        name: k8s-service
        version: v1
      - kind: ServiceMonitors
        name: k8s-servicemonitor
        version: v1
      - kind: StatefulSet
        name: k8s-statefulset
        version: v1
      specDescriptors:
      - description: Resource Specification for Anzo
        displayName: Anzo Pod Spec
        path: nodeConfig
      - description: Role of Anzo CR
        displayName: Role
        path: role
      statusDescriptors:
      - description: Human readable message for current state of Anzo
        displayName: Message
        path: message
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:message
      - description: Current phase of Anzo, like Creating/Running/Failed
        displayName: Phase
        path: phase
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:phase
      - description: Number of ready serving pods in Anzo
        displayName: Ready Replicas
        path: readyReplicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:readyReplicas
      - description: Event reason for deployed Anzo
        displayName: Reason
        path: reason
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:reason
      version: v1
  description: |-
    The Anzo Operator provides the way to install and configure an anzo agent setup on Red Hat K8S environment.
    Currently, this is supported only through when deployed as an Anzo Agent as part of an Anzo Unstructured deployment.

    ### Installation
     Refer [installation instructions]( https://github.com/cambridgesemantics/csi-k8s-operator-anzo/blob/v2.0.1/README.md )

    ### Documentation

    You can find our documentation [here.]( https://docs.cambridgesemantics.com/anzo/userdoc/cloud-deployments.htm )

    ### Support

    We offer Support to our customers through [ Cambridge Semantics Customer Center ]( https://customercenter.cambridgesemantics.com/ ).
  displayName: Anzo Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAIAAACzY+a1AAAEwGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjE1MCIKICAgZXhpZjpQaXhlbFlEaW1lbnNpb249IjE1MCIKICAgZXhpZjpDb2xvclNwYWNlPSIxIgogICB0aWZmOkltYWdlV2lkdGg9IjE1MCIKICAgdGlmZjpJbWFnZUxlbmd0aD0iMTUwIgogICB0aWZmOlJlc29sdXRpb25Vbml0PSIyIgogICB0aWZmOlhSZXNvbHV0aW9uPSIzMDAuMCIKICAgdGlmZjpZUmVzb2x1dGlvbj0iMzAwLjAiCiAgIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiCiAgIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIKICAgeG1wOk1vZGlmeURhdGU9IjIwMjAtMTAtMjBUMTU6MDY6MDQtMDQ6MDAiCiAgIHhtcDpNZXRhZGF0YURhdGU9IjIwMjAtMTAtMjBUMTU6MDY6MDQtMDQ6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJwcm9kdWNlZCIKICAgICAgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWZmaW5pdHkgRGVzaWduZXIgKEp1bCAyOSAyMDIwKSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMC0xMC0yMFQxNTowNjowNC0wNDowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+4W9FmAAAAYNpQ0NQc1JHQiBJRUM2MTk2Ni0yLjEAACiRdZHPK8NhHMdfGyImkx0cHNbCadNQ4qJsCbWkmTJctu/23dQ2377fLS1X5aoocfHrwF/AVTkrRaTk5OBMXNDX57utJtnn6fN8Xs/7eT6fnufzgD2SUbJGvR+yubwengi456ML7sZnmnHRjgdnTDG0sZmZEDXt4w6bFW98Vq3a5/61lkTSUMDWJDyqaHpeeFI4tJrXLN4WdinpWEL4VNirywWFby09XuYXi1Nl/rJYj4SDYHcKu1O/OP6LlbSeFZaX053NFJTKfayXOJK5uVmJHvEuDMJMEMDNFOMEGaKfEZmH8DFAn6yoke8v5U+zIrmKzBpFdJZJkSaPV9SCVE9KVEVPyshQtPr/t6+GOjhQru4IQMOTab71QOMWfG+a5uehaX4fQd0jXOSq+SsHMPwu+mZV696HtnU4u6xq8R0434DOBy2mx0pSnbhdVeH1BFqj0HENzYvlnlX2Ob6HyJp81RXs7kGvnG9b+gFJEWfY7/NllgAAAAlwSFlzAAAuIwAALiMBeKU/dgAAD35JREFUeJztnXlwE9f9wN/q9CmfWL5tfOADn2DANrY5TBwbiFPDL5A0F1NIk5K0TElbJr/QyXTCL5kUQk2ahiQF2iQkBQLhqsFAAHP5wvi+5ANbvm35kCzbyLr294fC+mklrVYiA/Nm3mf8x763u0+r/ez7vmtBhF/hUYBBGc6TvgDMo4IVIg9WiDw8OJEW4JMeKH5Sl4JhSWnfcFn/CJU0UpgeKH47NeGxXxLGRsrrYYU4kCIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxU+eXQk+Sin86wfggEAADCr093qGSqRDvYqp0amVQQAYmfHIJHL6lD/5YFiPte2ytAtV35e3dIxMSlVTA1OzYR7iDKDfLOCfbOC/Rx4XJuKeiSF75ZU9SmnDNsEIHalJcZ4u7M89/uW+xc7+zgE4BCE4S/c3XVnagJh7cTfXiqdnFUbtt0dhAdy0qhdr54rsfEbGBEkctmzMsU0X0eSX9a07i+vn9ZoTfceqm11FfB3pSduSVjAIaxePpicVRdWNh6ulWj0eiqzfVzRPq44UieJ8XY/vC4r1N2V/WXbr7Cif+RfdRJa5r+fWcHy9LZxRXFnLy3Tgcd7MyWW+cQbPYOjMyrDttjZEd51pauf5aebJdbbwzSzS67ccbmsalDGcKJSrdldUnWho3f/U6nBIheGI+Uqde5/LvZMTlk6oGVUnnvs4ic56TlhgSwv2/62sLCykZZz+X5f3fCY3QUCAD64U3P5ft+jlPDzcqROkv1tEbM/itK+4eyjRd82dlg6QE+Sb126A/vzdBSmBfisjwz2d3WiMidnNVvO36gZYnsn7VRYMzR2o2fQNH9veT3LEghgJuaQAGwvvtMyKrfvqn5ezrVLd5dUqbQ6Wr6Hg3BFsF9msK9IKKDtmtZo/3i1wlIwKKxsvNY9YNh25vN2ZyRXby049T9Pfbk28+6vCoo254a6zdXg927eY9nJsTOQFlY2mM2/1j1wb3B0sZ+3fcUCAGY02lfOlVx8PtfbycHWc5+aHwAIQACCAIAgCI5hmwAEeLhBGHYBrZ4sau+hdQXhT5TNqN65dhfey+MQO5bGb4oJCxQ5G54+EgCpYuo/TR3/qGrWQ0X96WrF9ZfWuzsYCdbo9Z9Xtxi2CQC+WJu5OtSf2ksAkOzrVfxC3sZTPzbJJgAAVYOy823S/AUhVr+1PQobZRPwg0YAAN+Jv5bXHS/ItloIQ8Pfr5zeWnTz+w3ZAq6VvhlhXMpX+Sutfi4AYEaj/fWFWzR/yb5en+dlGLZJAP50tWJCNUvtjfF2/yQnfeE8o8aSACDUzeWd9KTcsKAdl0s7JiYN+cPTD/58o+rvT6fDB9cOjU2pNYbtbcnRsD8KkVCwZ0VKwckrhuTJ1i42Cu0JpAeMW8F3M5LhJ+5Wz1A59KNQlqAF0l/GRcDdubsDsl3XKh9puGQBuUq9+fRVKqAZWB4oPl6QTX2LM5LuS1CT7O/qdOa5HJo/mGRfr7ObcuZBlfhUa9cl40b9JtTuMIhZFuBDfVCPwmKvB8ZmhZIxRVFHD5UUOztuTYp6LTkaPmZvWZ2td39FsN97mYvgnOPN96nI83MxNDWz4eSVe4OjcOZTYQFHf7HKRcCncg7XGvW0/7YmzRXaaxYPB+Ffs5fBObRCWscUhg0uQST6eDEUNf/hiEKqmGJzG21W+Mldoyr4ZkqskMvdmhgFf8my/pE7vUPM5ZgG0m3J0Ztjw+CcPbeqH3GcANMlV+afuNw6ZtRXKogKPbQuSwhF7OHpB9VDc443Rs/PDPZlU/7TYYF54UFUsqxvWPFw/AoAoPqcOpJUqtX0k82h1ulUWjMjURq2KeySK8+2Samkt5PDi3ERAACRULA1KQo+cm95va0VkQDgo9VLF/vOdYVIALZfvE276fbRKJvIP3GpTzkNZ74SH/n3p9P5HKObUDlgNIRYGeLH/lNWQAfrSBKu7iFQb9PQYTGLjiRvP3z6E8RejjzrnRXbFH5ytxHuer2xKIb6jNeSo535c593d0B2Q2pm1EFhtjcj4HIPrc/ydZkbJE1rtK+eKxl7MGvucPOFmFLaN7zh5BVaIdsXx364eqnpfMrw9AycTBQzBT0aiT6exkU9oLbDPUTU9j7Lz/cPrV1y1U91NItd7bdBYe/k9MmWLirp7iB4NWEBlfRwEMJJAMDecptbRACA2NnxyPosATTl2Ds5va3opkanZziLgeLO3l+euUb1Bg28k560OyPZ7BMgezj1AwAQcDlhtsx10eYXZTNzCjODfOMe9lMqB2R7y+r0JrPbTbKJXdcqqeSKYFYBwAaFn1Y1wR3xl+Ii9SSpVGuovxfjIuDZ3pqhsR8tt2Rmh/YGksRe+9ekwTkV/SO7rtvTQT3W1Lmt6JbaWP8Hq5b8dslCS6e48OcadbVOP24hAJhlCKp2AACx81w44RDEX1bMTcAWVja+fLbkRs+gSqvTkWTP5NSe2zVrjxdTMwkrQ/zS2P2uMttx4eDUzLHmTjjn06qmT6uamM/aW1a3Zn4Ay3AHsyE6tHl04rN7zVTOsabOKE+31xfFsC/ks3vNe27XwDlcgijMSdsYPZ/hLLGL0bxr/ci42TGcWeqHx+FkpKcITqYF+GyMnn+q9adIdl06cF06wOdySJLU6o2eTw8H4b7sVJb3jW0t/Oxesx2hrFE2YTqXbcDqnP47y5No9+792zVXjcdzlgohAXj/VjXNH5/L+ee6TGZ/AIAFnm5wssaWWd9a44MjPNxoBxTmpO1cFg/naHR6mj9/V6ezm3LgWVNmWCmUzaiONlicvWVmX3m9adA3xdQFlyA+y10O9wL0JPmbi7dprZopWj2580rZQeMxpSOPdzR/VS7U6bdEgo8nvABypFYCt44MDChnvmlop5L+rk4iIX00ySWIP6QmfPPsKtNdAIBQN5fdGcmXX1gb4SEy3WsJVgq/qG6Z1dFne1nSMiov6jBTEdlECZFQ8NUzK+BvO6XWmM47w6i0um1FN48336eVc2JDNsvhHYcgnoVmTyZUs2zmiUgAdv5YroQerxmN9rSk2+yJ2aH+tDWp9ZHBxwuyb7+av31xrKejkM11UlhvCydUs/+ub6OSDjzu64timAVU9I/AP7y+r7x+bUQQl8VyqClhHqKDeRkvny1hU5UnZzVbzpfQpve8nRyOFaw2uxZoiZ3LEv7b0TOg/Gl0UdzZu7+8fsfSeB7H/FfQ6PUfldbdNF66kavUbxbf+aah/f9WLqH1VDU6veThZA0AQMDl/CN3OW14yh7rCv9Z0zoDrVa/HB+5Ky2R+ZSeyamMr85RIb59XHGuTVoQFWp0EGujq0L8381Ifv9WtdUjN5++arpgmRMWWCIdLGEcpBoIcHU21D+RkL9/Terzp69Ruz6uaLguHTyQkxZuEuJaRuU7Lpc2Whitl/eP5Hx3YUvigj+mJlCLU5JxBbxkH+PtQfOn0urOtkm7Fcq4eR554UHMLwNYUTg5q4bn+vhczm9Y9AmDRS6bYsO/gxY/95XXPxMZYukptsobi2KaZRNUX46CNjLpGFcAE76zvAZLIy3AhwqhWcF+r8RHfg21bdVDo6u/LVrk653o45ko9tKRZP3weN3IWO3QGOzDFB1JHq6VnJF0785Ifi4mTEeS59ul8AHxxhPoE6rZ1y/czggS54YFnmuTnpZ0H8zLYKijVhQeqWuD4/vmmDB46oSB3y1ZeKK5k6qIXXLlD5KuTTFzU6A2ySQA2Ju9rHNispaxf8i1NxaZ5c+Zixpk4/DquUanr+gfqWBch0nxm5fs63WkVkJbzBp7MPv7K+VfN7RPqNTdciW8a0arJaEb8nF5w9akqO+aOuqGxxPFnkmOXt82dmwxnjaBYfrOU2rNlzVz/TouQbyZYnFETMNQEeGcv1U0MD+tzDjwuEfWZ9FelqFhdy03izOfd/a5p3elJbJvpfIXhHy/MfsvWYt/fHHdcnMD85qhMZo/AMAPrd27S+5SwrvkyjXzA9RavVavF3K5m2PDaUsrNJgu7uuGdmq+DgDwi6hQeK7WKjuWxMH3VKqY+h7qKNrRufF1cTpsPPdGg0f8zK/F8jjEjqVxxS/kMSwWGghxczm0LutgXoZh0SPKy+3ExjWf52VYClr+rk6+Lk7U/flXXVtp37Bhm8/lSOVKAMCOpXFXuwdqhkaZH1zCr/AolXh7WfzbqQlU0rQLaOttZyhBo9PDlVLA5bKsQyqtjuqdEgSA5/IfaLWP8lYthyAsvcOp0enPt/cU3+8tkQ7CA1ORkL8qxH9dRHBOWIDZdwymNdoDlY1fVLfAX/aluIgPVi3lcYiqQdlzp64aBmyrQ/2PPrsKAHCnb/ir+ra3UhYunOdR1jd8oLJx35pUuPJ8XF7/ccXciy9MbeGjRyWGEvhcjq2vzxpgeFOWzdKMffC5nA3RoRuiQ0kAFCr10PQMhyB8nZ1chXzmu+TM5/3v8qTnY8Neu3DL8FqXj5PjR9nLDGel+M3buSz+w9JaAK1ALQ8Ua3T6927ec+RxSRK8l7WYOfjht7ltgwDA3UFAe7XJKmEeomciQwwK3R0EsHXuw9gzrpqlOjUrQ/zYr1Pif1PxmEgL8DFsdCuU1Iupap2OWuCN9nK3L+zhWviYSPL1EnA5ap1erdO/cq7krZSFbkLBaUk31YtZExpgX8lY4WNCyOVuSVjwZU0rAECuUtNWUcI9RG8stmEdDQYH0sfHuxnJ+ZFmXj8UOzseWpdl9SU5S+Ba+PjgczgH12asbQ86I5He6R3S6skQN5e1EUHbF8c68e0XgRU+VggA8iND8iNDdCTJIexauzEBK3wy2Lf0ZhbcFiIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIgxUiD1aIPFgh8mCFyIMVIg9WiDxYIfJghciDFSIPVog8WCHyYIXIY/Tfq5f2DYPy+id1KRiWUD8wY8BIYZnxzyhjkAAHUuTBCpEHK0Se/wdpyI/2ohmxmQAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - extensions
          resourceNames:
          - nfs-provisioner
          resources:
          - podsecuritypolicies
          verbs:
          - use
        - apiGroups:
          - anzo.cambridgesemantics.com
          resources:
          - anzos
          - anzos/finalizers
          verbs:
          - '*'
        serviceAccountName: anzo-operator
      deployments:
      - name: anzo-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: RELATED_IMAGE_ANZO
                  value: registry.connect.redhat.com/cambridgesemantics/anzo:5.3.1
                image: registry.connect.redhat.com/cambridgesemantics/anzo-operator:2.0.1
                imagePullPolicy: Always
                name: manager
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
              serviceAccountName: anzo-operator
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
        - apiGroups:
          - anzo.cambridgesemantics.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - anzo.cambridgesemantics.com
          resources:
          - anzos/finalizers
          verbs:
          - update
        - apiGroups:
          - anzo.cambridgesemantics.com
          resources:
          - anzos/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          - endpoints
          - events
          - persistentvolume
          - persistentvolumeclaims
          - pods
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - get
        - apiGroups:
          - policy
          resourceNames:
          - privileged
          resources:
          - podsecuritypolicies
          verbs:
          - use
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: anzo-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Big Data
  links:
  - name: Anzo Operator
    url: https://github.com/cambridgesemantics/csi-k8s-operator-anzo/blob/v2.0.1/README_openshift.md
  maintainers:
  - email: frank@cambridgesemantics.com
    name: Frank Schwichtenberg
  maturity: stable
  provider:
    name: Cambridge Semantics Inc.
  version: 2.0.1
