# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: grafanacloudlogforwarders.logs.grafana.com
spec:
  group: logs.grafana.com
  names:
    kind: GrafanaCloudLogForwarder
    listKind: GrafanaCloudLogForwarderList
    plural: grafanacloudlogforwarders
    singular: grafanacloudlogforwarder
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: GrafanaCloudLogForwarder is the Schema for the grafanacloudlogforwarders API
          properties:
            apiVersion:
              description: |
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: GrafanaCloudLogForwarderSpec defines the desired state of GrafanaCloudLogForwarder
              properties:
                apipassword:
                  description: Enter API key to authenticate clusterLogForwarder to loki datasource
                  type: string
                url:
                  description: URL to loki datasource
                  type: string
                username:
                  description: The username from the loki endpoint
                  type: string
              required:
                - apipassword
                - url
                - username
              type: object
            status:
              description: GrafanaCloudLogForwarderStatus defines the observed state of GrafanaCloudLogForwarder
              properties:
                secretName:
                  description: Sec
                  type: string
                secretNamespace:
                  type: string
              required:
                - secretName
                - secretNamespace
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
