---
apiVersion: v1
data:
  properties.yaml: |
    version: 0.1.0
    spec:
      units: []

    properties: []
kind: ConfigMap
metadata:
  name: opa-operator-configmap
  labels:
    app.kubernetes.io/name: opa-operator
    app.kubernetes.io/instance: opa-operator
    app.kubernetes.io/version: "23.4.1"
