---
# Source: listener-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: listener-operator-serviceaccount
  labels:
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    app.kubernetes.io/version: "0.0.0-dev"
