---
# Source: listener-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: listener-operator-clusterrolebinding
  labels:
    app.kubernetes.io/name: listener-operator
    app.kubernetes.io/instance: listener-operator
    app.kubernetes.io/version: "0.0.0-dev"
subjects:
  - kind: ServiceAccount
    name: listener-operator-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: listener-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
