# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: workloadmanagers.workloadmanager.nec.com
spec:
  group: workloadmanager.nec.com
  names:
    kind: WorkloadManager
    listKind: WorkloadManagerList
    plural: workloadmanagers
    singular: workloadmanager
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: WorkloadManager is the Schema for the workloadmanagers API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                enum:
                - workload-manager
                type: string
            type: object
          spec:
            properties:
              api_timeout:
                default: 3
                minimum: 1
                type: integer
              cluster_collection_size:
                default: 10737418240
                minimum: 1
                type: integer
              cluster_platform:
                default: EKS
                enum:
                - EKS
                - OpenShift
                - Kubernetes
                type: string
              common_config_log_level:
                default: INFO
                enum:
                - DEBUG
                - INFO
                - WARNING
                - ERROR
                - CRITICAL
                type: string
              db_startup_recheck_time:
                default: 5
                minimum: 0
                type: integer
              db_startup_wait_time:
                default: 60
                minimum: 1
                type: integer
              default_monitor_count:
                default: 10
                maximum: 1000
                minimum: 1
                type: integer
              default_monitor_interval:
                default: 60
                maximum: 86400
                minimum: 10
                type: integer
              default_repeat_interval:
                default: 1800
                maximum: 86400
                minimum: 60
                type: integer
              detail_collection_size:
                default: 10737418240
                minimum: 1
                type: integer
              detect_count:
                default: 1
                maximum: 10737418240
                minimum: 0
                type: integer
              detect_interval:
                default: 60
                maximum: 10737418240
                minimum: 1
                type: integer
              eks:
                properties:
                  cognito_client_id:
                    default: ""
                    type: string
                  cognito_client_secret:
                    default: ""
                    type: string
                  cognito_domain:
                    default: ""
                    type: string
                  cognito_region:
                    default: ""
                    type: string
                  cognito_user_pool_id:
                    default: ""
                    type: string
                  nginx_cert_arn:
                    type: string
                  prometheus_service_name:
                    type: string
                  prometheus_service_port:
                    maximum: 65535
                    minimum: 1
                    type: integer
                  prometheus_service_protocol:
                    default: https
                    enum:
                    - http
                    - https
                    type: string
                required:
                - nginx_cert_arn
                - prometheus_service_name
                - prometheus_service_port
                type: object
              event_collection_size:
                default: 10737418240
                minimum: 1
                type: integer
              expire_after_seconds:
                default: 31536000
                minimum: 1
                type: integer
              get_info_interval:
                default: 60
                minimum: 1
                type: integer
              get_info_ssc:
                default: "off"
                enum:
                - "on"
                - "off"
                type: string
              get_kubernetes_url_v10:
                default: "false"
                enum:
                - "true"
                - "false"
                type: string
              grafana_cooperation:
                default: "off"
                enum:
                - "on"
                - "off"
                type: string
              grafana_datasource:
                default: prometheus
                type: string
              grafana_node_additional_varlist:
                default: ""
                type: string
              grafana_node_dashboard_endpoint:
                default: https://changeit.nec.co.jp:443/d/wmnode/wm-node-dashboard
                type: string
              grafana_node_varname_datasource:
                default: datasource
                type: string
              grafana_node_varname_node:
                default: node
                type: string
              grafana_pod_additional_varlist:
                default: ""
                type: string
              grafana_pod_dashboard_endpoint:
                default: https://changeit.nec.co.jp:443/d/wmpod/wm-pod-dashboard
                type: string
              grafana_pod_varname_datasource:
                default: datasource
                type: string
              grafana_pod_varname_pod:
                default: pod
                type: string
              grafana_time_range_minutes:
                default: 60
                type: integer
              hidden_namespace:
                type: string
              image:
                type: string
              jaeger_endpoint:
                type: string
              jaeger_service_mapping:
                type: string
              jaeger_time_range_sec:
                default: 60
                minimum: 1
                type: integer
              kubernetes:
                properties:
                  ingress_host_name:
                    type: string
                  prometheus_service_name:
                    type: string
                  prometheus_service_port:
                    maximum: 65535
                    minimum: 1
                    type: integer
                  prometheus_service_protocol:
                    default: https
                    enum:
                    - http
                    - https
                    type: string
                required:
                - prometheus_service_name
                - prometheus_service_port
                type: object
              max_policy_fired_histories:
                default: 512
                minimum: 1
                type: integer
              mode:
                default: trial
                enum:
                - trial
                - product
                type: string
              node_cpu_usage_threshold:
                default: 80
                maximum: 100
                minimum: 0
                type: integer
              node_disk_usage_threshold:
                default: 100
                maximum: 10737418240
                minimum: 0
                type: integer
              node_memory_usage_threshold:
                default: 80
                maximum: 100
                minimum: 0
                type: integer
              node_network_usage_threshold:
                default: 55
                maximum: 10737418240
                minimum: 0
                type: integer
              node_selector:
                type: string
              openshift:
                properties:
                  use_ebs:
                    default: "n"
                    enum:
                    - "y"
                    - "n"
                    type: string
                  web_console_host:
                    type: string
                required:
                - web_console_host
                type: object
              policy_fired_histories_collection_max_size:
                default: 1073741824
                minimum: 1
                type: integer
              policy_fired_histories_expire_after_seconds:
                default: 31536000
                minimum: 1
                type: integer
              skip_action_interval:
                default: 600
                minimum: 1
                type: integer
              ssc_auth_by_secret:
                default: "false"
                enum:
                - "true"
                - "false"
                type: string
              ssc_event_collection_size:
                default: 1073741824
                minimum: 1
                type: integer
              use_auth:
                default: "true"
                enum:
                - "true"
                - "false"
                type: string
              use_pv:
                default: "false"
                enum:
                - "true"
                - "false"
                type: string
              user_authority_config_json:
                type: string
            required:
            - image
            type: object
          status:
            description: WorkloadManagerStatus defines the observed state of WorkloadManager
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
