---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: adm-agent-operator
  name: adm-agent-operator-admagent-viewer-role
rules:
- apiGroups:
  - netscaler.com
  resources:
  - admagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netscaler.com
  resources:
  - admagents/status
  verbs:
  - get
