apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units:\n    - unit: &unitPort\n     \
    \   name: \"port\"\n        regex: \"^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$\"\
    \n\n    - unit: &unitUrl\n        name: \"url\"\n        regex: \"^((https?|ftp|file)://)?[-a-zA-Z0-9+&@#}/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]\"\
    \n        examples:\n          - \"https://www.stackable.de/blog/\"\n\n    - unit:\
    \ &unitCapacity\n        name: \"capacity\"\n        regex: \"^[1-9]\\\\d*$\"\n\
    \n    - unit: &unitMilliseconds\n        name: \"milliseconds\"\n        regex:\
    \ \"^[1-9]\\\\d*$\"\n\nproperties:\n  - property:\n      propertyNames:\n    \
    \    - name: \"networkaddress.cache.ttl\"\n          kind:\n            type:\
    \ \"file\"\n            file: \"security.properties\"\n      datatype:\n     \
    \   type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n        -\
    \ fromVersion: \"0.0.0\"\n          value: \"30\"\n      roles:\n        - name:\
    \ \"broker\"\n          required: true\n      asOfVersion: \"0.0.0\"\n      comment:\
    \ \"TTL for successfully resolved domain names.\"\n      description: \"TTL for\
    \ successfully resolved domain names.\"\n\n  - property:\n      propertyNames:\n\
    \        - name: \"networkaddress.cache.negative.ttl\"\n          kind:\n    \
    \        type: \"file\"\n            file: \"security.properties\"\n      datatype:\n\
    \        type: \"integer\"\n        min: \"0\"\n      recommendedValues:\n   \
    \     - fromVersion: \"0.0.0\"\n          value: \"0\"\n      roles:\n       \
    \ - name: \"broker\"\n          required: true\n      asOfVersion: \"0.0.0\"\n\
    \      comment: \"TTL for domain names that cannot be resolved.\"\n      description:\
    \ \"TTL for domain names that cannot be resolved.\"\n\n  - property: &zookeeperConnect\n\
    \      propertyNames:\n        - name: \"zookeeper.connect\"\n          kind:\n\
    \            type: \"file\"\n            file: \"server.properties\"\n      datatype:\n\
    \        type: \"string\"\n        unit: *unitUrl\n      defaultValues:\n    \
    \    - fromVersion: \"0.0.0\"\n          value: \"localhost:2181\"\n      roles:\n\
    \        - name: \"broker\"\n          required: true\n      asOfVersion: \"0.0.0\"\
    \n      description: \"The zookeeper connection string\"\n\n  - property: &zookeeperTimeout\n\
    \      propertyNames:\n        - name: \"zookeeper.connection.timeout.ms\"\n \
    \         kind:\n            type: \"file\"\n            file: \"server.properties\"\
    \n      datatype:\n        type: \"integer\"\n        unit: *unitMilliseconds\n\
    \      defaultValues:\n        - fromVersion: \"0.0.0\"\n          value: \"18000\"\
    \n      roles:\n        - name: \"broker\"\n          required: true\n      asOfVersion:\
    \ \"0.0.0\"\n      description: \"Zookeeper connection timeout in milliseconds.\"\
    \n\n  - property: &opaAuthorizerClassName\n      propertyNames:\n        - name:\
    \ \"authorizer.class.name\"\n          kind:\n            type: \"file\"\n   \
    \         file: \"server.properties\"\n      datatype:\n        type: \"string\"\
    \n      defaultValues:\n        - fromVersion: \"0.0.0\"\n          value: \"\
    com.bisnode.kafka.authorization.OpaAuthorizer\"\n        - fromVersion: \"3.0.0\"\
    \n          value: \"org.openpolicyagent.kafka.OpaAuthorizer\"\n      roles:\n\
    \        - name: \"broker\"\n          required: false\n      asOfVersion: \"\
    0.0.0\"\n      description: \"OPA Authorizer class name\"\n\n  - property: &opaAuthorizerUrl\n\
    \      propertyNames:\n        - name: \"opa.authorizer.url\"\n          kind:\n\
    \            type: \"file\"\n            file: \"server.properties\"\n      datatype:\n\
    \        type: \"string\"\n        unit: *unitUrl\n      roles:\n        - name:\
    \ \"broker\"\n          required: false\n      asOfVersion: \"0.0.0\"\n      description:\
    \ \"OPA Authorizer URL\"\n\n  - property: &opaAuthorizerInitialCacheCapacity\n\
    \      propertyNames:\n        - name: \"opa.authorizer.cache.initial.capacity\"\
    \n          kind:\n            type: \"file\"\n            file: \"server.properties\"\
    \n      datatype:\n        type: \"integer\"\n        unit: *unitCapacity\n  \
    \    defaultValues:\n        - fromVersion: \"0.0.0\"\n          value: \"0\"\n\
    \      roles:\n        - name: \"broker\"\n          required: false\n      asOfVersion:\
    \ \"0.0.0\"\n      description: \"OPA Authorizer initial cache capacity\"\n\n\
    \  - property: &opaAuthorizerMaxCacheSize\n      propertyNames:\n        - name:\
    \ \"opa.authorizer.cache.maximum.size\"\n          kind:\n            type: \"\
    file\"\n            file: \"server.properties\"\n      datatype:\n        type:\
    \ \"integer\"\n        unit: *unitCapacity\n      defaultValues:\n        - fromVersion:\
    \ \"0.0.0\"\n          value: \"0\"\n      roles:\n        - name: \"broker\"\n\
    \          required: false\n      asOfVersion: \"0.0.0\"\n      description: \"\
    OPA authorizer max cache size\"\n\n  - property: &opaAuthorizerCacheExpireAfterSeconds\n\
    \      propertyNames:\n        - name: \"opa.authorizer.cache.expire.after.seconds\"\
    \n          kind:\n            type: \"file\"\n            file: \"server.properties\"\
    \n      datatype:\n        type: \"integer\"\n        unit: *unitCapacity\n  \
    \    defaultValues:\n        - fromVersion: \"0.0.0\"\n          value: \"0\"\n\
    \      roles:\n        - name: \"broker\"\n          required: false\n      asOfVersion:\
    \ \"0.0.0\"\n      description: \"The number of seconds after which the OPA authorizer\
    \ cache expires\"\n\n  - property: &logDirs\n      propertyNames:\n        - name:\
    \ \"log.dirs\"\n          kind:\n            type: \"file\"\n            file:\
    \ \"server.properties\"\n      datatype:\n        type: \"string\"\n      recommendedValues:\n\
    \        - value: \"/stackable/data/topicdata\"\n      roles:\n        - name:\
    \ \"broker\"\n          required: true\n      asOfVersion: \"0.0.0\"\n      description:\
    \ \"A comma separated list of directories under which to store log files\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: kafka-operator
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/version: 24.11.1
    stackable.tech/vendor: Stackable
  name: kafka-operator-configmap
