apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sources.triggermesh.com/v1alpha1",
          "kind": "AwsEventSources",
          "metadata": {
            "name": "awseventsources-sample"
          },
          "spec": {
            "adapters": {
              "awscloudwatch": {
                "image": "registry.connect.redhat.com/triggermesh/awscloudwatchsource@sha256:847b8546933d83c91cb7068609ad4dfbd87370da610bebb0ca6a1cc8efe0202c"
              },
              "awscloudwatchlogs": {
                "image": "registry.connect.redhat.com/triggermesh/awscloudwatchlogssource@sha256:962fe3695f53f7083adce89acaffbba8d01f4d8e91312adfa4ac3a13485cd179"
              },
              "awscodecommit": {
                "image": "registry.connect.redhat.com/triggermesh/awscodecommitsource@sha256:d3ab78147e535e224fcae5ede8ddfb8a269e343121105869213b78d257a3e1cb"
              },
              "awscognitoidentity": {
                "image": "registry.connect.redhat.com/triggermesh/awscognitoidentitysource@sha256:8da3202e7cff988c76878aa40e00796d9ac82748d39c6c0e66eb8def281766cf"
              },
              "awscognitouserpool": {
                "image": "registry.connect.redhat.com/triggermesh/awscognitouserpoolsource@sha256:09d6f609f7aee720bddb196702a0116e8dca785fbbf5337a97edee4bfd44cdb4"
              },
              "awsdynamodb": {
                "image": "registry.connect.redhat.com/triggermesh/awsdynamodbsource@sha256:168890a69107536cc8e7332e1ce4cf90f7427a8c4dca7520d5237da58b98a700"
              },
              "awskinesis": {
                "image": "registry.connect.redhat.com/triggermesh/awskinesissource@sha256:8b3984455cd08add91242fe5dedda6f234f644d80256ee42c407fc9fabfa8a4f"
              },
              "awsperformanceinsights": {
                "image": "registry.connect.redhat.com/triggermesh/awsperformanceinsightssource@sha256:a5aa8d5c568e41ddcc9b718507b77aff4a4db1586a07f658972da912eca09931"
              },
              "awssns": {
                "image": "registry.connect.redhat.com/triggermesh/awssnssource@sha256:e300042681697794716c6cf1a13e41c4e5b440ed513202b74db2b1aef1d9c8c6"
              },
              "awssqs": {
                "image": "registry.connect.redhat.com/triggermesh/awssqssource@sha256:34cc1484951328499246a98e6d2277c3554e22b390b17c34449af4eeba076153"
              }
            },
            "affinity": {},
            "fullnameOverride": "",
            "image": {
              "image": "registry.connect.redhat.com/triggermesh/aws-event-sources-controller@sha256:a806b330ed4ba33a2d3544210d5f40c1657509cf054530c9f6d38789e6b6d5c3",
              "pullPolicy": "IfNotPresent"
            },
            "imagePullSecrets": [],
            "nameOverride": "",
            "nodeSelector": {},
            "podAnnotations": {},
            "podSecurityContext": {},
            "rbac": {
              "create": true
            },
            "resources": {
              "requests": {
                "cpu": "20m",
                "memory": "20Mi"
              }
            },
            "securityContext": {},
            "serviceAccount": {
              "annotations": {},
              "create": true,
              "name": ""
            },
            "tolerations": []
          }
        }
      ]
    capabilities: Basic Install
    marketplace.openshift.io/remote-workflow: https://marketplace.redhat.com/en-us/operators/aws-sources-operator/pricing?utm_source=openshift_console
    marketplace.openshift.io/support-workflow: https://marketplace.redhat.com/en-us/operators/aws-sources-operator/support?utm_source=openshift_console
    operators.operatorframework.io/builder: operator-sdk-v1.13.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: aws-sources-operator.v0.4.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AwsEventSources
      name: awseventsources.sources.triggermesh.com
      version: v1alpha1
  description: |
    The TriggerMesh AWS Sources operator provides a collection of API's that enables to consume events that happen in your AWS services and send them to containers, microservices and functions running in your cluster.

    ## Prerequisites

    The TriggerMesh AWS Sources operator depends on the Knative API's provided by the Red Hat OpenShift Serverless operator. For more information, see the documentation on [Installing OpenShift Serverless](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.3/html/serverless_applications/installing-openshift-serverless-1).

    ## Supported Event Sources

    - **AWS CodeCommit event source**: Consume messages from a AWS CodeCommit repository and send them as CloudEvents to an arbitrary event sink.
    - **AWS Cognito Identity event source**: Consume messages from a AWS Cognito identity pool and send them as CloudEvents to an arbitrary event sink.
    - **AWS Cognito UserPool event source**: Consume messages from a AWS Cognito identity pool and send them as CloudEvents to an arbitrary event sink.
    - **AWS DynamoDB event source**: Consume messages from a AWS DynamoDB stream and send them as CloudEvents to an arbitrary event sink.
    - **AWS Kinesis event source**: Consume messages from a AWS Kinesis data stream and send them as CloudEvents to an arbitrary event sink.
    - **AWS SNS event source**: Subscribes to messages from a AWS SNS topic and send them as CloudEvents to an arbitrary event sink.
    - **AWS SQS event source**: Consume messages from a AWS SQS queue and sends them as CloudEvents to an arbitrary event sink.

    ## Installation

    See the documentation on [Installing TriggerMesh AWS Sources](https://github.com/triggermesh/aws-sources-operator/blob/master/README.md)

    ## Getting Started

    See the documentation on [Getting Started](https://github.com/triggermesh/aws-event-sources/blob/master/README.md)
  displayName: AWS Sources Operator
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MzUuNTUgNDMuNTQiPjxkZWZzPjxzdHlsZT4uY2xzLTF7ZmlsbDojMDA5NmRiO30uY2xzLTJ7aXNvbGF0aW9uOmlzb2xhdGU7fTwvc3R5bGU+PC9kZWZzPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTYwLjQ1LDIwQzU5LjU0LDMsMzUuNDUtNC4xNSwyNSwxMi43NGMtNi43Ni0zLTE0Ljg3LDEuNTYtMTUsOS4xMkMtMy40MywyMy4yMy00LjgzLDQzLjcsMTUsNDMuN2guNjZhNi45LDYuOSwwLDAsMSwuMTEtNC44SDEzLjY3Yy05LjUyLS4wNy0xMi0xMy44Ny42OC0xMi41OS0yLjMxLTcuNjIsNS43NS0xNCwxMi40NS04LjIyQzMyLjg2LDQsNTUuMjIsMy41NCw1Ni4yMywyMy43MWMxMi40NS44OCwxMi4wNiwxNC4wOSwzLDE1LjM0SDQ2LjQ4QTQuOTQsNC45NCwwLDAsMSw0Nyw0My43SDU5LjE4QzczLDQzLjQyLDc1LjUsMjIuOTMsNjAuNDUsMjBaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjAxIC0zLjExKSIvPjxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTM2LjE4LDI5LjM5bC4xMi0uMjJjMS4yNy0yLjI2LDYuMzEtMi40MSw4LjI5LS42MWE1LjcyLDUuNzIsMCwwLDAsMi4xLDEuODQsNSw1LDAsMSwwLDQuMTUtOSw1LjA3LDUuMDcsMCwwLDAtNi41NiwyLjQ2Yy0xLjQ3LDIuNjgtNy4xNSwxLjg2LTguMjUuNjdhNi4wNyw2LjA3LDAsMCwwLTIuNzMtMS45MkE0LjY5LDQuNjksMCwwLDAsMjcsMjcuNzJhNS4zMiw1LjMyLDAsMCwwLC41NSwxLjY5Yy41MiwxLjI0LTIsNi44My00LjYzLDcuMzJhNS43Myw1LjczLDAsMCwwLTIuNzMuNTYsNC45NCw0Ljk0LDAsMSwwLDQuNDUsOC44MmwuMTktLjFhNS4wNyw1LjA3LDAsMCwwLDItNi42OGMtMS4yNC0yLjc4LDIuNDYtNy4xOCw0LjU3LTcuMzFzNS44Miw0Ljg0LDQuNTUsNy4xNEE1LjA4LDUuMDgsMCwwLDAsMzcuNDMsNDZhNSw1LDAsMCwwLDUuMzItOC4zNCw1Ljc4LDUuNzgsMCwwLDAtMi42NS0uNzhjLTIuNTgtLjY5LTUuMjMtNC45My00LTcuMjJaTTQ5LDIzLjc5QTIuMTUsMi4xNSwwLDEsMSw0Ni44NCwyNmgwQTIuMTYsMi4xNiwwLDAsMSw0OSwyMy43OVpNMjIuNDMsNDRhMi4xNSwyLjE1LDAsMSwxLDIuMTUtMi4xNWgwQTIuMTQsMi4xNCwwLDAsMSwyMi40NSw0NFpNMzEuNiwyOC40YTEuNjEsMS42MSwwLDEsMSwxLjYtMS42MnYwQTEuNiwxLjYsMCwwLDEsMzEuNiwyOC40Wm04LjU4LDExLjMxQTIuMTUsMi4xNSwwLDEsMSwzOCw0MS44N2gwYTIuMTQsMi4xNCwwLDAsMSwyLjEzLTIuMTVaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjAxIC0zLjExKSIvPjxnIGNsYXNzPSJjbHMtMiI+PGcgY2xhc3M9ImNscy0yIj48cGF0aCBkPSJNOTAuMjcsMTAuN0g3OVY3LjJoMjYuNHYzLjVIOTQuMTFWNDAuOEg5MC4yN1oiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDEgLTMuMTEpIi8+PHBhdGggZD0iTTExMi41LDcuMkgxMjdjNC4xMiwwLDcuNDQsMS4yNSw5LjU1LDMuMzZhOS4yNyw5LjI3LDAsMCwxLDIuNTksNi42MnYuMWMwLDUuNTctMy44NCw4LjgzLTkuMTIsOS43OUwxNDAuMjksNDAuOGgtNC42NmwtOS43NC0xMy4wNmgtOS42VjQwLjhIMTEyLjVabTE0LjExLDE3LjEzYzUsMCw4LjY0LTIuNTksOC42NC02Ljkxdi0uMDljMC00LjEzLTMuMTctNi42My04LjU5LTYuNjNIMTE2LjI5VjI0LjMzWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMSAtMy4xMSkiLz48cGF0aCBkPSJNMTQ3LjU0LDcuMmgzLjc5VjQwLjhoLTMuNzlaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjAxIC0zLjExKSIvPjxwYXRoIGQ9Ik0xNTkuNjgsMjQuMDlWMjRjMC05LjIyLDYuNzctMTcuMzgsMTYuODUtMTcuMzhhMTcuNzIsMTcuNzIsMCwwLDEsMTIuNTMsNC40NkwxODYuNjEsMTRhMTQuMjgsMTQuMjgsMCwwLDAtMTAuMjMtMy44NWMtNy40NCwwLTEyLjc2LDYuMjktMTIuNzYsMTMuNzhWMjRjMCw4LDUuMTMsMTQsMTMuMjksMTRhMTUuODQsMTUuODQsMCwwLDAsOS43LTMuMzZWMjYuMjVIMTc2LjM4di0zLjRoMTMuODhWMzYuMjRhMjAuNCwyMC40LDAsMCwxLTEzLjQ5LDUuMTRDMTY2LjIxLDQxLjM4LDE1OS42OCwzMy43LDE1OS42OCwyNC4wOVoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDEgLTMuMTEpIi8+PHBhdGggZD0iTTE5Ny4zMSwyNC4wOVYyNGMwLTkuMjIsNi43Ny0xNy4zOCwxNi44NS0xNy4zOGExNy43MiwxNy43MiwwLDAsMSwxMi41Myw0LjQ2TDIyNC4yNCwxNEExNC4yNywxNC4yNywwLDAsMCwyMTQsMTAuMTJjLTcuNDQsMC0xMi43Nyw2LjI5LTEyLjc3LDEzLjc4VjI0YzAsOCw1LjEzLDE0LDEzLjI5LDE0YTE1Ljg0LDE1Ljg0LDAsMCwwLDkuNy0zLjM2VjI2LjI1SDIxNHYtMy40aDEzLjg3VjM2LjI0YTIwLjQsMjAuNCwwLDAsMS0xMy40OSw1LjE0QzIwMy44NCw0MS4zOCwxOTcuMzEsMzMuNywxOTcuMzEsMjQuMDlaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjAxIC0zLjExKSIvPjxwYXRoIGQ9Ik0yMzYuNDMsNy4yaDI0LjI5djMuNDVoLTIwLjVWMjIuMTNoMTguMzR2My40NUgyNDAuMjJWMzcuMzRIMjYxVjQwLjhIMjM2LjQzWiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMSAtMy4xMSkiLz48cGF0aCBkPSJNMjY4LjU5LDcuMkgyODNjNC4xMywwLDcuNDQsMS4yNSw5LjU1LDMuMzZhOS4yNyw5LjI3LDAsMCwxLDIuNTksNi42MnYuMWMwLDUuNTctMy44NCw4LjgzLTkuMTIsOS43OUwyOTYuMzgsNDAuOGgtNC42NUwyODIsMjcuNzRoLTkuNlY0MC44aC0zLjc5Wk0yODIuNywyNC4zM2M1LDAsOC42NC0yLjU5LDguNjQtNi45MXYtLjA5YzAtNC4xMy0zLjE2LTYuNjMtOC41OS02LjYzSDI3Mi4zOFYyNC4zM1oiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDEgLTMuMTEpIi8+PC9nPjxnIGNsYXNzPSJjbHMtMiI+PHBhdGggZD0iTTMwMi41Nyw3LjJoOGw4LjgzLDE0LjIxTDMyOC4yMSw3LjJoOFY0MC44aC03LjM0VjE4Ljg2bC05LjQ2LDE0LjM1aC0uMTlMMzA5LjgyLDE5VjQwLjhoLTcuMjVaIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLjAxIC0zLjExKSIvPjxwYXRoIGQ9Ik0zNDQuMjQsNy4yaDI1LjM0djYuNTdoLTE4djYuODJoMTUuODR2Ni41OEgzNTEuNTh2N2gxOC4yNFY0MC44SDM0NC4yNFoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDEgLTMuMTEpIi8+PHBhdGggZD0iTTM3NC4wOSwzNS45bDQuMzctNS4yM2MzLDIuNSw2LjE5LDQuMDgsMTAsNC4wOCwzLDAsNC44NS0xLjIsNC44NS0zLjE3di0uMDljMC0xLjg3LTEuMTUtMi44NC02Ljc3LTQuMjgtNi43Ny0xLjcyLTExLjEzLTMuNi0xMS4xMy0xMC4yN3YtLjA5YzAtNi4xLDQuODktMTAuMTMsMTEuNzYtMTAuMTNBMTkuNDQsMTkuNDQsMCwwLDEsMzk5LjY4LDExbC0zLjg0LDUuNTdjLTMtMi4wNy01LjkxLTMuMzEtOC43NC0zLjMxcy00LjMyLDEuMjktNC4zMiwyLjkydi4xYzAsMi4yMSwxLjQ0LDIuOTMsNy4yNSw0LjQyLDYuODIsMS43NywxMC42Niw0LjIyLDEwLjY2LDEwLjA4di4wOWMwLDYuNjgtNS4wOSwxMC40Mi0xMi4zNCwxMC40MkEyMS4zOSwyMS4zOSwwLDAsMSwzNzQuMDksMzUuOVoiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDEgLTMuMTEpIi8+PHBhdGggZD0iTTQwNy4xMiw3LjJoNy4zOVYyMC40OWgxMy42M1Y3LjJoNy4zOVY0MC44aC03LjM5VjI3LjMxSDQxNC41MVY0MC44aC03LjM5WiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMSAtMy4xMSkiLz48L2c+PC9nPjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - sources.triggermesh.com
          resources:
          - awseventsources
          - awseventsources/status
          - awseventsources/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: aws-sources-operator-controller-manager
      deployments:
      - name: aws-sources-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=aws-sources-operator
                env:
                - name: AWS_EVENT_SOURCES_CONTROLLER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/aws-event-sources-controller@sha256:a806b330ed4ba33a2d3544210d5f40c1657509cf054530c9f6d38789e6b6d5c3
                - name: AWSCODECOMMIT_CLOUDWATCHLOGS_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awscloudwatchlogssource@sha256:962fe3695f53f7083adce89acaffbba8d01f4d8e91312adfa4ac3a13485cd179
                - name: AWSCODECOMMIT_CLOUDWATCH_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awscloudwatchsource@sha256:847b8546933d83c91cb7068609ad4dfbd87370da610bebb0ca6a1cc8efe0202c
                - name: AWSCODECOMMIT_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awscodecommitsource@sha256:d3ab78147e535e224fcae5ede8ddfb8a269e343121105869213b78d257a3e1cb
                - name: AWSCOGNITOIDENTITY_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awscognitoidentitysource@sha256:8da3202e7cff988c76878aa40e00796d9ac82748d39c6c0e66eb8def281766cf
                - name: AWSCOGNITOUSERPOOL_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awscognitouserpoolsource@sha256:09d6f609f7aee720bddb196702a0116e8dca785fbbf5337a97edee4bfd44cdb4
                - name: AWSDYNAMODB_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awsdynamodbsource@sha256:168890a69107536cc8e7332e1ce4cf90f7427a8c4dca7520d5237da58b98a700
                - name: AWSKINESIS_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awskinesissource@sha256:8b3984455cd08add91242fe5dedda6f234f644d80256ee42c407fc9fabfa8a4f
                - name: AWSKINESIS_PERFORMANCEINSIGHTS_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awsperformanceinsightssource@sha256:a5aa8d5c568e41ddcc9b718507b77aff4a4db1586a07f658972da912eca09931
                - name: AWSSNS_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awssnssource@sha256:e300042681697794716c6cf1a13e41c4e5b440ed513202b74db2b1aef1d9c8c6
                - name: AWSSQS_ADAPTER_IMAGE
                  value: registry.connect.redhat.com/triggermesh/awssqssource@sha256:34cc1484951328499246a98e6d2277c3554e22b390b17c34449af4eeba076153
                image: gcr.io/triggermesh/aws-event-sources-operator@sha256:b99aae2ebbfe839d689f273704c0975fef3ad7a1e1f323add0f22036665dbf20
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: aws-sources-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: aws-sources-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - knative
  - serverless
  - aws
  - triggermesh
  links:
  - name: AWS Sources Operator
    url: https://github.com/triggermesh/aws-sources-operator/
  - name: AWS Sources Controller
    url: https://github.com/triggermesh/aws-event-sources/
  - name: Installation Guide
    url: https://github.com/triggermesh/aws-sources-operator/blob/master/README.md
  - name: Getting Started
    url: https://github.com/triggermesh/aws-event-sources/blob/master/README.md
  maintainers:
  - email: dev@triggermesh.com
    name: TriggerMesh Developers
  maturity: alpha
  minKubeVersion: 1.20.0
  provider:
    name: TriggerMesh Inc.
    url: https://www.triggermesh.com
  replaces: aws-sources-operator.v0.3.0
  version: 0.4.0
