apiVersion: v1
data:
  config.json: |
    {
      "scenarios": {
        "core": {
          "description": "The smallest set of components that support HM functions.",
          "components": [
            "pre-install-resources",
            "upm-cert-manager",
            "upm-trust-manager",
            "upm-istio",
            "upm-istio-gateway",
            "upm-beaco-filters",
            "upm-prometheus-operator",
            "upm-spire",
            "upm-ui",
            "cloud-native-postgres-dbaas",
            "pg4k-additional-controllers",
            "upm-alertmanager",
            "storage-location-operator",
            "pg4k-pgd-dbaas",
            "upm-prometheus",
            "upm-loki",
            "upm-api-stats-collector",
            "upm-beaco-ff-base",
            "upm-velero",
            "upm-beacon",
            "upm-loki-rule",
            "upm-thanos",
            "upm-api-gucs",
            "upm-image-library",
            "upm-fluent-bit",
            "upm-thanos-rule",
            "upm-dex",
            "beaconator-starlight",
            "upm-notification-system",
            "upm-cp-grafana",
            "upm-api-pnxt-metric",
            "upm-api-pnxt-pd"
          ]
        },
        "migration": {
          "description": "Components related to data migration.",
          "components": [
            "transporter-data-operator",
            "transporter-kafka-operator",
            "transporter-ui-service",
            "edb-migration-portal",
            "upm-migration-assessment",
            "transporter-rw-service",
            "edb-migration-copilot",
            "transporter-dp-provisioner",
            "transporter-dp-agent"
          ]
        },
        "ai": {
          "description": "AI functions related components.",
          "components": [
            "upm-kserve",
            "upm-langflow",
            "upm-mcp-proxy",
            "upm-griptape",
            "upm-ai-model-server"
          ]
        },
        "analytics": {
          "description": "Analytics related components.",
          "components": [
            "upm-spark-connect",
            "upm-beacon-analytics-cnpg-plugin",
            "upm-lakekeeper"
          ]
        }
      }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: edb-hcp-operator
    control-plane: edb-hcp-operator
  name: edb-hcp-operator-operator-config
