apiVersion: v1
data:
  minkms: |
    image: "quay.io/minio/aistor/minkms:RELEASE.2025-11-12T19-14-51Z"
  minkms-sidecar: |
    image: "quay.io/minio/aistor/minkms-sidecar:RELEASE.2025-12-17T18-33-52Z"
kind: ConfigMap
metadata:
  name: minkms-operator-default
