apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: open-liberty-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: open-liberty-operator
  name: openlibertydumps.apps.openliberty.io
spec:
  group: apps.openliberty.io
  names:
    kind: OpenLibertyDump
    listKind: OpenLibertyDumpList
    plural: openlibertydumps
    shortNames:
    - oldump
    - oldumps
    singular: openlibertydump
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Indicates if dump operation has started
      jsonPath: .status.conditions[?(@.type=='Started')].status
      name: Started
      type: string
    - description: Reason for dump operation failing to start
      jsonPath: .status.conditions[?(@.type=='Started')].reason
      name: Reason
      priority: 1
      type: string
    - description: Message for dump operation failing to start
      jsonPath: .status.conditions[?(@.type=='Started')].message
      name: Message
      priority: 1
      type: string
    - description: Indicates if dump operation has completed
      jsonPath: .status.conditions[?(@.type=='Completed')].status
      name: Completed
      type: string
    - description: Reason for dump operation failing to complete
      jsonPath: .status.conditions[?(@.type=='Completed')].reason
      name: Reason
      priority: 1
      type: string
    - description: Message for dump operation failing to complete
      jsonPath: .status.conditions[?(@.type=='Completed')].message
      name: Message
      priority: 1
      type: string
    - description: Indicates filename of the server dump
      jsonPath: .status.dumpFile
      name: Dump file
      type: string
    name: v1beta2
    schema:
      openAPIV3Schema:
        description: Day-2 operation for generating server dumps
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenLibertyDumpSpec defines the desired state of OpenLibertyDump
            properties:
              include:
                description: 'Optional. List of memory dump types to request: thread, heap, system.'
                items:
                  description: Defines the possible values for dump types
                  enum:
                  - thread
                  - heap
                  - system
                  type: string
                type: array
                x-kubernetes-list-type: set
              podName:
                description: The name of the Pod, which must be in the same namespace as the OpenLibertyDump CR.
                type: string
            required:
            - podName
            type: object
          status:
            description: Defines the observed state of OpenLibertyDump
            properties:
              conditions:
                items:
                  description: OperationStatusCondition ...
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    lastUpdateTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      description: OperationStatusConditionType ...
                      type: string
                  type: object
                type: array
                x-kubernetes-list-type: atomic
              dumpFile:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
