---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: contrail-system-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-system-role
subjects:
- kind: ServiceAccount
  name: contrail-system-serviceaccount
  namespace: contrail-system
