---
apiVersion: v1
kind: Service
metadata:
  annotations:
    infoscale.veritas.com/certificate: infoscale-dr-webhook-cert
  creationTimestamp: null
  name: infoscale-dr-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: infoscale-dr-manager
status:
  loadBalancer: {}
