---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-operator-deployer-manifests
data:
  stackable-secret-operator-scc.yaml: |
    ---
    apiVersion: security.openshift.io/v1
    kind: SecurityContextConstraints
    metadata:
      name: stackable-secret-operator-scc
      annotations:
        kubernetes.io/description: SCC for Stackable secret operator
    allowHostDirVolumePlugin: true
    allowHostIPC: false
    allowHostNetwork: false
    allowHostPID: false
    allowHostPorts: false
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: true # Needed because otherwise we get spec.template.spec.containers[0].volumeMounts.mountPropagation: Forbidden: Bidirectional mount propagation is available only to privileged containers
    allowedCapabilities: null
    defaultAddCapabilities: null
    fsGroup:
      type: RunAsAny
    groups: []
    priority: null
    readOnlyRootFilesystem: false
    requiredDropCapabilities:
    - MKNOD
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: MustRunAs
    supplementalGroups:
      type: RunAsAny
    users: []
    volumes:
    - downwardAPI
    - projected
    - hostPath
    - emptyDir

  tls.yaml: |
    ---
    # Source: secret-operator/templates/secretclasses.yaml
    apiVersion: secrets.stackable.tech/v1alpha1
    kind: SecretClass
    metadata:
      name: tls
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: "25.7.0"
    spec:
      backend:
        autoTls:
          ca:
            secret:
              name: secret-provisioner-tls-ca
              namespace: default
            autoGenerate: true

  csidriver.yaml: |
    ---
    # Source: secret-operator/templates/csidriver.yaml
    apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    metadata:
      name: secrets.stackable.tech
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: "25.7.0"
    spec:
      attachRequired: false
      podInfoOnMount: true
      fsGroupPolicy: File
      volumeLifecycleModes:
        - Ephemeral
        - Persistent

  storageclass.yaml: |
    ---
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: secrets.stackable.tech
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: "25.7.0"
    provisioner: secrets.stackable.tech

  daemonset.yaml: |
    ---
    # Source: secret-operator/templates/daemonset.yaml
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: secret-operator-daemonset
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: "25.7.0"
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: secret-operator
          app.kubernetes.io/instance: secret-operator
          stackable.tech/vendor: Stackable
      template:
        metadata:
          labels:
            app.kubernetes.io/name: secret-operator
            app.kubernetes.io/instance: secret-operator
            stackable.tech/vendor: Stackable
        spec:
          serviceAccountName: secret-operator-serviceaccount
          securityContext: {}
          containers:
            - name: secret-operator
              securityContext:
                privileged: true
                runAsUser: 0
              image: "quay.io/stackable/secret-operator@sha256:c4a10ffad1f336b7287758b57d01cb3a07572c33d389573776187181738663cd"
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              env:
                - name: CSI_ENDPOINT
                  value: /csi/csi.sock
                - name: PRIVILEGED
                  value: "true"
                # Operators need to know the node name they are running on, to e.g. discover the
                # Kubernetes domain name from the kubelet API.
                - name: KUBERNETES_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: csi
                  mountPath: /csi
                - name: mountpoint
                  mountPath: /var/lib/kubelet/pods
                  mountPropagation: Bidirectional
                - name: tmp
                  mountPath: /tmp
            - name: external-provisioner
              image: "quay.io/stackable/sig-storage/csi-provisioner@sha256:71f8465e35a67f4b96e4c4904e67ccac9bbb9ae347426afb8bbfaabd6709e983"
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              args:
                - --csi-address=/csi/csi.sock
                - --feature-gates=Topology=true
                - --extra-create-metadata
              volumeMounts:
                - name: csi
                  mountPath: /csi
            - name: node-driver-registrar
              image: "quay.io/stackable/sig-storage/csi-node-driver-registrar@sha256:89a09e870909deb6125393e30f3dbcd1e0769d3c112b58622419f5c6490b7a1b"
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              args:
                - --csi-address=/csi/csi.sock
                - --kubelet-registration-path=/var/lib/kubelet/plugins/secrets.stackable.tech/csi.sock
              volumeMounts:
                - name: registration-sock
                  mountPath: /registration
                - name: csi
                  mountPath: /csi
          volumes:
            - name: registration-sock
              hostPath:
                # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
                # see https://github.com/stackabletech/secret-operator/issues/229 for why this path should not be too long
                path: /var/lib/kubelet/plugins_registry
            - name: csi
              hostPath:
                path: /var/lib/kubelet/plugins/secrets.stackable.tech/
            - name: mountpoint
              hostPath:
                path: /var/lib/kubelet/pods/
            - name: tmp
              emptyDir: {}
