apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: registry.marketplace.redhat.com/cpopen/ds-operator@sha256:4a53892a469c6b9b751a4cc2449378bfb0b15bfe1f3c0dd5056eeaf1587c82a4
    alm-examples: "[\n  {\n    \"apiVersion\": \"ds.cpd.ibm.com/v1\",\n    \"kind\"\
      : \"DataStage\",\n    \"metadata\": {\n      \"name\": \"datastage\"\n    },\n\
      \    \"spec\": {\n      \"license\": {\n        \"accept\": false\n      },\n\
      \      \"fileStorageClass\": \"managed-nfs-storage\",\n      \"scaleConfig\"\
      : \"small\"\n    }\n  }\n]"
    capabilities: Seamless Upgrades
    cloudpakId: 49a42b864bb94569bef0188ead948f11
    cloudpakName: IBM DataStage Enterprise Plus Cartridge for IBM Cloud Pak for Data
    description: The IBM DataStage Operator is used to deploy IBM DataStage services
    features.operators.openshift.io/disconnected: 'false'
    features.operators.openshift.io/fips-compliant: 'false'
    features.operators.openshift.io/proxy-aware: 'false'
    features.operators.openshift.io/tls-profiles: 'false'
    features.operators.openshift.io/token-auth-aws: 'false'
    features.operators.openshift.io/token-auth-azure: 'false'
    features.operators.openshift.io/token-auth-gcp: 'false'
    operators.operatorframework.io/builder: operator-sdk-v1.4.2
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
    operatorframework.io/suggested-namespace: ibm-common-services
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    olm.skipRange: '>=1.0.0 <7.3.0'
    nss.operator.ibm.com/managed-operators: ibm-cpd-datastage-operator
  name: ibm-cpd-datastage-operator.v7.3.0
  namespace: placeholder
spec:
  relatedImages:
  - name: ds-operator
    image: registry.marketplace.redhat.com/cpopen/ds-operator@sha256:4a53892a469c6b9b751a4cc2449378bfb0b15bfe1f3c0dd5056eeaf1587c82a4
  - name: ds-canvas
    image: registry.marketplace.redhat.com/cp/cpd/ds-canvas@sha256:1b39e1d5d7c13451252250ceeb29b91c1e7ef3739fc17baf9958e1bf07c4c2fd
  - name: ds-cas-lite
    image: registry.marketplace.redhat.com/cp/cpd/ds-cas-lite@sha256:99fc418fb1a09ee6c45e90dfba47f73ea8e1da1b19f9f570d2a749b68118b7a3
  - name: ds-flows
    image: registry.marketplace.redhat.com/cp/cpd/ds-flows@sha256:001bf35df08cd397397c3fdd1ddbd7953cdf4bde06965427ae640e5608e60ddf
  - name: ds-nginx-proxy
    image: registry.marketplace.redhat.com/cp/cpd/ds-nginx-proxy@sha256:4604a076c837600cd4b3e29b31e22470915fe5b6b1191ae9401407f8620f2472
  - name: ds-migration
    image: registry.marketplace.redhat.com/cp/cpd/ds-migration@sha256:5f5faf7d15f46d79eea873c12ff631ed59bc55bc57f1f7aee9fd0a8f35fdd3cf
  - name: ds-assets
    image: registry.marketplace.redhat.com/cp/cpd/ds-assets@sha256:7015b410b947338dcafde98b68b95cb4199c08511ae46e733691e8fa835ad988
  - name: ds-px-compute
    image: registry.marketplace.redhat.com/cp/cpd/ds-px-compute@sha256:3f8133fcd904befa579b99d3a828fe737faf13ae14e842ed0408eeeee72de5fb
  - name: ds-px-runtime
    image: registry.marketplace.redhat.com/cp/cpd/ds-px-runtime@sha256:8b72cafe9de355634bc3218cc1dc701ffb376a29aecb5cd12a5719d43a1304bd
  - name: qs-ruleset
    image: registry.marketplace.redhat.com/cp/cpd/qs-ruleset@sha256:046eb99c8f1f37dd4cffa1c6c9a93aea50bb5d10a549aa12c3c90134d03c6d1c
  - name: ds-runtime
    image: registry.marketplace.redhat.com/cp/cpd/ds-runtime@sha256:3eecc54f26cd87870c201b5ade1d037d2733ccfda40fc1aedd9a2164e582275d
  - name: ds-dataservice
    image: registry.marketplace.redhat.com/cp/cpd/ds-dataservice@sha256:6c569c4687546a03a5f4e127acc13b219ce3efa057fbdfd55e96868e549c70cb
  - name: ds-metrics
    image: registry.marketplace.redhat.com/cp/cpd/ds-metrics@sha256:10492010b28f57f8badbc7cadbe15d1447269052b387d878c6d9ecbd2f62923b
  - name: ds-operator-catalog
    image: registry.marketplace.redhat.com/cpopen/ds-operator-catalog@sha256:ef03bb6ed647d92b9c84d34810376da7049aad88589eb2e35798d82a22f5b994
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DataStage
      name: datastages.ds.cpd.ibm.com
      description: 'Documentation: [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-datastage)
        License: [IBM DataStage Enterprise Cartridge for Cloud Pak for Data](https://ibm.biz/Bdahic),
        [IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data](https://ibm.biz/BdahsW)'
      version: v1
      specDescriptors:
      - description: You must read and accept the license terms to install the software
          IBM DataStage Enterprise Cartridge for Cloud Pak for Data(https://ibm.biz/Bdahic),
          IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data(https://ibm.biz/BdahsW).
        displayName: License
        path: license
      - description: Indicate that you read and accept the license.
        displayName: Accept license
        path: license.accept
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
        value:
        - false
      - description: Select the size for the DataStage installation.
        displayName: Size
        path: scaleConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:small
        - urn:alm:descriptor:com.tectonic.ui:select:medium
        - urn:alm:descriptor:com.tectonic.ui:select:large
      - description: The block storage class to use for install. Used for RWO PVCs.
        displayName: Block Storage Class
        path: blockStorageClass
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:StorageClass
      - description: The file storage class to use for install. Used for RWX PVCs.
        displayName: File Storage Class
        path: fileStorageClass
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:StorageClass
    - kind: PXRuntime
      name: pxruntimes.ds.cpd.ibm.com
      description: Documentation [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-datastage)
        License [IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data](https://ibm.biz/BdahsW)
      version: v1
  description: "# Introduction\nIndustry-leading batch and real-time data integration\
    \ service for data engineers to build trusted pipelines (ETL/ELT) for AI and operational\
    \ use cases across on-premises and hybrid cloud environments.\nWith DataStage,\
    \ you can design and run data flows that move and transform data anywhere, at\
    \ any scale.\nNo matter how complex your data landscape, DataStage can streamline\
    \ your data movement costs and increase productivity. DataStage offers:\n<ul><li>A\
    \ best-in-breed parallel processing engine that enables you to process your data\
    \ where it resides</li><li>Automated job design</li><li>Simple integration with\
    \ cloud data lakes, real-time data sources, relational databases, big data, and\
    \ NoSQL data stores</li></ul>\nThe DataStage service uses Cloud Pak for Data platform\
    \ connections and integration points, with services like Data Virtualization,\
    \ to simplify the process of connecting to and accessing your data.\n\nWith DataStage,\
    \ Data Engineers can use the simple user interface to build no-code/low-code data\
    \ pipelines. The interface offers hundreds of functions and connectors that reduce\
    \ development time and inconsistencies across pipelines. The interface also makes\
    \ it easy to collaborate with your peers and control access to specific analytics\
    \ projects.\nThe service also provides automatic workload balancing to provide\
    \ high performance pipelines that make efficient use of available compute resources.\n\
    \n## Details\nSee [Details](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=SSQNUZ_4.0/svc-welcome/dsent.html)\n\
    \n## Documentation\n\n[IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-datastage)\n\
    \n## Installing\nTo install the operator follow the the installation and configuration\
    \ instructions within the [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=datastage-installing).\n\
    \n## Prerequisites\n\n- OpenShift Version >= 4.6\n- IBM Cloud Pak for Data >=\
    \ 4.0.2\n- IBM Cloud Pak for Data Common Core Services (CCS) >= 2.0.2 (The DataStage\
    \ service automatically installs the CCS if they are not already installed.)\n\
    \n### Resources Required\n\nSee [Details](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=requirements-hardware)\n\
    \n## Configuration\n\nTo scale DataStage services, you can specify spec.scaleConfig\
    \ in the DataStage custom resource to small, medium, or large.\n\n## License\n\
    [IBM DataStage Enterprise Cartridge for Cloud Pak for Data](https://ibm.biz/Bdahic)\n\
    [IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data](https://ibm.biz/BdahsW)\n\
    \n## Limitations\n- Only the `x86-64` platform is supported by this operator.\n\
    - See [Limitations and known issues in DataStage](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=issues-datastage)\n\
    \n## SecurityContextConstraints Requirements\nCustom SecurityContextConstraints\
    \ definition:\n```\napiVersion: security.openshift.io/v1\nkind: SecurityContextConstraints\n\
    allowHostDirVolumePlugin: false\nallowHostIPC: false\nallowHostNetwork: false\n\
    allowHostPID: false\nallowHostPorts: false\nallowPrivilegeEscalation: true\nallowPrivilegedContainer:\
    \ false\nallowedCapabilities: null\ndefaultAddCapabilities: null\nfsGroup:\n \
    \ type: MustRunAs\nmetadata:\n  annotations:\n    include.release.openshift.io/self-managed-high-availability:\
    \ \"true\"\n    kubernetes.io/description: restrict denies access to all host\
    \ features and requires pods to be run with a UID, and SELinux context that are\
    \ allocated to the namespace.  This is the most restrictive SCC and it is used\
    \ by default for authenticated users.\n    release.openshift.io/create-only: \"\
    true\"\n  name: restrict\npriority: null\nreadOnlyRootFilesystem: false\nrequiredDropCapabilities:\n\
    - KILL\n- MKNOD\n- SETUID\n- SETGID\nrunAsUser:\n  type: MustRunAsRange\nseLinuxContext:\n\
    \  type: MustRunAs\nsupplementalGroups:\n  type: RunAsAny\nusers: []\nvolumes:\n\
    - configMap\n- downwardAPI\n- emptyDir\n- persistentVolumeClaim\n- projected\n\
    - secret\n```"
  displayName: IBM DataStage
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAABYlAAAWJQFJUiTwAAAGfklEQVR4nO1bW4gcRRS9tYkkmZfBB4RgyyohBFkkakR/1NkPv1RMfhTxsbOoiEvnZQgJGvIwhoRgXJeMJkjIdKJ+CMomYBAMspMfEYxmxATfZMMoUWJwM88VwSvV1d3TXV392u2uneAeGOip6WH6nKo691bVHZjFLGbxvwYJJK+oBQBYCwDLuU/KAHAEqkVNpoA5tY2AAIBEfxF6DcR432m3rjlcOdzjaPQWQFEp4ZKAOA8qxCqoFifipSpGbnULebJRROAF6BH+CiM/FoI8RR4AzoOiLoyXqgcoW/3VuWYc3e3WtQ/EArCej0KI3juaBF8XRASnIcJcVwub83zP0+E9Ygx3MHp9LSdSHhR1JVSLx+JnbQf266xMwtYsptZApwMOA6HPT4zPAaxrgSe4BWDE7KDk+6FarNjayqCox4xpYhdhAAASFaA2kil7fZYbmiwhkOUEjZ4XicDBLYmi8nftgGpxu/AXFZW2b5syGz9Ui8ERyoac2i4BQiHIGK8cmuNjgsz8ePj1qGdvyERuTbMEBAsCT6i4PIGDlwleNcita5SAQEFgjBoSWO8yRl8BnPPcxEofMfIz2vPr6yUALAicX6u9PX9QGB04iEywwkWBtbrh8eKw6cIbJr1vVcw8hchtuFICxAKb5w7T02r7U4Ngvu1Eh9ACjBh5gImFutsralAYBD01loDcxglmeHaHR6PnRzKD1hPYhrwlAgex0yrqmZBZoB1lqBb7k6af3fSXTp7w6S4SrTacHbTfm1vdygOSMXsUqB2YFyIVprk9i/9hUTG+kyiymy+vY3OecnGYm4u8DssXokaBanEcAO4wiAWhbCRKiS6Gsi//SYkPMxIINhG02r5r3eR1YGBKLPIABlMElhoPCByf5gfHZSyHs1suFQDR8CUzraWXRKvtXehB3iTMZ4NOeAtgghJU1HGXAJLcPrv1D4O8K63V6nuu8ybPbqsA8msHJ4IFmEFkt/1eYBHJlc9r9d03+JOn64Y3MxNB2WrXCpDdcZH1PBvq9t7X6ruCyYdFV6bCmZ2/0eyu1DGujtvXX7sxNvIUXTcCMrt+LQBCieVvYDc9rf7qoljJU3SVAJndVYfb20TQ6tvjJ0/RNQJk9lxg5J3znYqgNbYu9ievqHljc6aDkPsJXSFAZu/4M3TY2+K75faNLTcl0vMmZtwEM6+ffxwIFoHgP5zpaY1XkiVPMaMjIPPGL6sAcS8AaduG/TU0yWlsvjlx8hQzJkB6+OeH2H4iTrIWa9gfbWzqfU7Wc8yIAOmRnx4ExI2IMEmcpvdBY2PvGpnPIl2A9P4fHgDEIQAyqe/W0OnORBhtbLh1s+znkSpA+q3v7zV2chzDHhFONF9aslPms5iQJkD6wHd3AuJjANDmVnYnm+uW7JP1HDykCJA+eK4PAB82hz2DLsKp5pqlB2U8gxcSFyD9ztmlgNAPiG3uuOqLprrsaNK/H4REBUgf+rYXEO8BgElu+/rr5tCyD5P87bAIJ0C1WA5VTWJD6vA3ixGxjziTHCrC2eaLt32SKKsISGQEpLTK9YBwC3V7titnDfsfmy/0nUqIy5QQuwCpI2eygLgIiDHsAY1TfHKh+Xzfl3JohUesAqTe/WoeIGZ1t3ceV11sPnv7uWSpTA2xCZB6/zRdvM9xJDlMhMutweXjMklFQWzL4daTKxAI/q0PfYL0RcPepVahe8lTOJx9wcen8oAw5i4zE5efEfPaWYkxF5DMo7tZrafvaibOYJoHN04BTpRdh4lRRWg9cTdJvXe6p/XUin+T4GtBUXuNyrRp1TG6p4BnmZm4Ha3Cg87hoyTyYU+wfesYnQIQwWFiVBHkYDSuOkZHFEBipi2dzK39yP2eGeCCjz7PA5AxW6xPnv306hgLvCc4w6AesmmP2kUIgO0EVlL/D3Dvo9QxPkp3mu1f5gQwKOhFlSFEcJy3iwsRdYj27ePDiLC4i7axsh57HaOr4EvgAZ35LqgsdQvAe4J8TKuO0T0FoDOkA8e0MWWcpzlXF4KjgK8A6I4O8jGtOkaBB/iXlHjebx1pCTCF/QRPKOoYRyxaHSMH92LIJYIPok6ZeHCEEyBKHeNxF137m/mffdpxa8+/nxiV2O46Pf26vfK+5K0wxjpG79WgTzaIHv/akBgFotYx0nuFZ43+y+GpiCAD0eoYK/q97DsuBG+ICI0RBcmS5FDorGPsmr/1zWIWs7iKAAD/ARzhBiS0VNI7AAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: ibm-cpd-datastage-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-cpd-datastage-operator
          strategy: {}
          template:
            metadata:
              labels:
                app.kubernetes.io/instance: ibm-cpd-datastage-operator
                app.kubernetes.io/managed-by: ibm-cpd-datastage-operator
                app.kubernetes.io/name: ibm-cpd-datastage-operator
                icpdsupport/module: ibm-cpd-datastage-operator
                icpdsupport/addOnId: datastage
                icpdsupport/app: operator
                intent: projected
                name: ibm-cpd-datastage-operator
              annotations:
                productID: d8a97b146d6f4bf18f033db9105f87f1
                cloudpakName: IBM DataStage Extension for IBM Cloud Pak for Data
                productName: IBM DataStage Enterprise Plus for Cloud Pak for Data
                productVersion: 5.1.3
                productMetric: FREE
            spec:
              hostNetwork: false
              hostPID: false
              hostIPC: false
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - s390x
              serviceAccountName: ibm-cpd-datastage-operator-sa
              containers:
              - args:
                - --zap-log-level
                - info
                - --max-concurrent-reconciles
                - '6'
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                - name: WATCH_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: namespaces
                      name: namespace-scope
                      optional: true
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: registry.marketplace.redhat.com/cpopen/ds-operator@sha256:c2c27cf0826e1f96aa523ec68374680ce1f7f8f4cc5512c28962933b22aabbfe
                livenessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 1024Mi
                securityContext:
                  runAsNonRoot: true
                  privileged: false
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: false
                  capabilities:
                    drop:
                    - ALL
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ''
          - batch
          - extensions
          - apps
          - policy
          - rbac.authorization.k8s.io
          - autoscaling
          - route.openshift.io
          - authorization.openshift.io
          - networking.k8s.io
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          - jobs
          - configmaps
          - deployments
          - deployments/scale
          - statefulsets
          - statefulsets/scale
          - replicasets
          - services
          - persistentvolumeclaims
          - persistentvolumes
          - cronjobs
          - pods/exec
          - serviceaccounts
          - namespaces
          - roles
          - rolebindings
          - horizontalpodautoscalers
          - routes
          - routes/custom-host
          - jobs/status
          - pods/status
          - networkpolicies
          verbs:
          - apply
          - create
          - get
          - delete
          - watch
          - update
          - edit
          - list
          - patch
        - apiGroups:
          - ds.cpd.ibm.com
          - ccs.cpd.ibm.com
          - wspipelines.cpd.ibm.com
          resources:
          - ccs
          - ccs/status
          - ccs/finalizers
          - datastages
          - datastages/status
          - datastages/finalizers
          - pxruntimes
          - pxruntimes/status
          - pxruntimes/finalizers
          - wspipelines
          - wspipelines/status
          - wspipelines/finalizers
          verbs:
          - apply
          - edit
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - zen.cpd.ibm.com
          resources:
          - zenservices
          - zenextensions
          - zenextensions/status
          - zenextensions/finalizers
          verbs:
          - create
          - apply
          - edit
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.ibm.com
          resources:
          - operandrequests
          - operandregistries
          - operandconfigs
          - operandbindinfos
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
          - use
        serviceAccountName: ibm-cpd-datastage-operator-sa
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - DataStage
  - Analytics
  - Cloud Pak
  - Data
  - Cloud Pak for Data
  - IBM
  maintainers:
  - name: IBM
    email: cp4d@ibm.com
  maturity: alpha
  provider:
    name: IBM
    url: https://www.ibm.com/in-en/products/cloud-pak-for-data
  version: 7.3.0
