apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kurrentdb-operator.v1.5.0
  namespace: placeholder
  annotations:
    alm-examples: |
      [
        {
          "apiVersion": "kubernetes.kurrent.io/v1",
          "kind": "KurrentDB",
          "metadata": {
            "name": "insecure",
            "namespace": "kurrent"
          },
          "spec": {
            "replicas": 1,
            "image": "registry.connect.redhat.com/kurrent-io/kurrentdb@sha256:4dc9fcb41de27695ba04731e768fb18cde2f1c7882f8787dfce3d32b93520131",
            "resources": {
              "requests": {
                "cpu": "1000m",
                "memory": "1Gi"
              }
            },
            "storage": {
              "volumeMode": "Filesystem",
              "accessModes": [
                "ReadWriteOnce"
              ],
              "resources": {
                "requests": {
                  "storage": "512Mi"
                }
              }
            },
            "volumeSnapshotClassName": "e2e",
            "network": {
              "domain": "kurrent.dev",
              "fqdnTemplate": "{podName}.{domain}",
              "loadBalancer": {
                "enabled": true
              }
            }
          }
        },
        {
          "apiVersion": "kubernetes.kurrent.io/v1",
          "kind": "KurrentDBBackup",
          "metadata": {
            "name": "insecure",
            "namespace": "kurrent"
          },
          "spec": {
            "clusterName": "insecure"
          }
        },
        {
          "apiVersion": "kubernetes.kurrent.io/v1",
          "kind": "KurrentDBBackupSchedule",
          "metadata": {
            "name": "my-schedule",
            "namespace": "kurrent"
          },
          "spec": {
            "schedule": "* * * * *",
            "template": {
              "spec": {
                "clusterName": "insecure"
              }
            },
            "keep": 10
          }
        }
      ]
    capabilities: Full Lifecycle
    categories: Database, Streaming & Messaging, OpenShift Optional
    certified: 'true'
    createdAt: '2025-12-23T00:00:00Z'
    description: An operator to seamlessly deploy and manage KurrentDB clusters and
      backups.
    containerImage: registry.connect.redhat.com/kurrent-io/kurrentdb-operator@sha256:9e10c1f7055fc5bbe8e4d8289b247389d337a77a27d56232022695405a10b980
    support: support@kurrent.io
    repository: https://github.com/kurrent-io/kurrentdb
    operators.openshift.io/valid-subscription: license required, contact us at https://www.kurrent.io/contact
    features.operators.openshift.io/disconnected: 'false'
    features.operators.openshift.io/fips-compliant: 'false'
    features.operators.openshift.io/proxy-aware: 'false'
    features.operators.openshift.io/tls-profiles: 'false'
    features.operators.openshift.io/token-auth-aws: 'false'
    features.operators.openshift.io/token-auth-azure: 'false'
    features.operators.openshift.io/token-auth-gcp: 'false'
  labels:
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
spec:
  version: 1.5.0
  replaces: ''
  skips: []
  maturity: stable
  description: An operator to seamlessly deploy and manage KurrentDB clusters and
    backups.
  displayName: KurrentDB Operator
  keywords:
    - kurrent
    - event sourcing
    - database
  links:
    - name: Website
      url: https://kurrent.io
    - name: Documentation
      url: https://docs.kurrent.io/server/kubernetes-operator
  maintainers:
    - name: Kurrent, Inc
      email: support@kurrent.io
  provider:
    name: Kurrent, Inc
    url: https://kurrent.io
  minKubeVersion: 1.30.0
  icon:
    - base64data: PHN2ZyB3aWR0aD0iODU1IiBoZWlnaHQ9IjE4OSIgdmlld0JveD0iMCAwIDg1NSAxODkiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxnIGNsaXAtcGF0aD0idXJsKCNjbGlwMF82MTE1Xzc4MjcpIj4KPHBhdGggZD0iTTEuMTU0NzkgMTg3Ljg0MUwxLjE1NDc4IDAuMDAwMTgzMTA1TDE2LjgwODIgMjUuNDM3TDE2LjgwODIgMTYyLjQwNEwxLjE1NDc5IDE4Ny44NDFaIiBmaWxsPSIjNjMxQjNBIi8+CjxwYXRoIGQ9Ik0yNS44NjEzIDE4Ny44NDFMMjUuODYxMyAwLjAwMDE4MzEwNUw0MS41MTQ3IDM1LjIyMDRMNDEuNTE0OCAxNTIuNjIxTDI1Ljg2MTMgMTg3Ljg0MVoiIGZpbGw9IiM2MzFCM0EiLz4KPHBhdGggZD0iTTUwLjU2NjkgMTg3Ljg0MUw1MC41NjY5IDAuMDAwMTgzMTA1TDY2LjIyMDMgNDUuMDAzOEw2Ni4yMjAzIDE0Mi44MzhMNTAuNTY2OSAxODcuODQxWiIgZmlsbD0iIzYzMUIzQSIvPgo8cGF0aCBkPSJNNzUuMjczNCAxODcuODQxTDc1LjI3MzQgMC4wMDAxODMxMDVMOTAuOTI2OSA1NC43ODcyTDkwLjkyNjkgMTMzLjA1NEw3NS4yNzM0IDE4Ny44NDFaIiBmaWxsPSIjNjMxQjNBIi8+CjxwYXRoIGQ9Ik05OS45NzkgMTg3Ljg0MUw5OS45NzkgMC4wMDAxODMxMDVMMTE1LjYzMiA2NC41NzA2TDExNS42MzIgMTIzLjI3MUw5OS45NzkgMTg3Ljg0MVoiIGZpbGw9IiM2MzFCM0EiLz4KPHBhdGggZD0iTTEyNC42ODYgMTg3Ljg0MUwxMjQuNjg2IDAuMDAwMTgzMTA1TDE0MC4zMzkgNzQuMzU0TDE0MC4zMzkgMTEzLjQ4OEwxMjQuNjg2IDE4Ny44NDFaIiBmaWxsPSIjNjMxQjNBIi8+CjxwYXRoIGQ9Ik0xNDkuMzkxIDE4Ny44NDFMMTQ5LjM5MSAwLjAwMDE4MzEwNUwxNjUuMDQ0IDg0LjEzNzRMMTY1LjA0NCAxMDMuNzA0TDE0OS4zOTEgMTg3Ljg0MVoiIGZpbGw9IiM2MzFCM0EiLz4KPHBhdGggZD0iTTE3NC4wOTggMTg3Ljg0MUwxNzQuMDk4IDAuMDAwMTgzMTA1TDE4OS43NTEgOTMuOTIwN0wxNzQuMDk4IDE4Ny44NDFaIiBmaWxsPSIjNjMxQjNBIi8+CjwvZz4KPHBhdGggZD0iTTM5OS4xNzggMTY0LjM0N1YxNTIuNjY0QzM5NS41MTIgMTU3LjU3MiAzOTEuMjkxIDE2MS4yMzggMzg2LjUxMyAxNjMuNjU5QzM4MS44IDE2Ni4wMTYgMzc2LjQwMSAxNjcuMTk0IDM3MC4zMTQgMTY3LjE5NEMzNTYuNzY1IDE2Ny4xOTQgMzQ2LjM1OSAxNjMuMDM4IDMzOS4wOTQgMTU0LjcyNUMzMzEuODI5IDE0Ni40MTMgMzI4LjE5NiAxMzQuNDY4IDMyOC4xOTYgMTE4Ljg5MVY1Ni4zNTI2SDM1My42MjRWMTA0Ljg1MkMzNTMuNjI0IDExOS40NDcgMzU1LjI5MyAxMjkuNDI5IDM1OC42MzEgMTM0Ljc5NkMzNjEuOTY5IDE0MC4xNjIgMzY3LjcyOCAxNDIuODQ2IDM3NS45MSAxNDIuODQ2QzM4NC4yODcgMTQyLjg0NiAzOTAuMjc2IDEzOS44MzUgMzkzLjg3NiAxMzMuODE0QzM5Ny41NDEgMTI3Ljc5MiAzOTkuMzc0IDExNy41ODIgMzk5LjM3NCAxMDMuMTgzVjU2LjM1MjZINDI0LjExNFYxNjQuMzQ3SDM5OS4xNzhaIiBmaWxsPSIjNjMxQjNBIi8+CjxwYXRoIGQ9Ik00OTYuNTY4IDc4LjI0NkM0ODYuODE2IDc5LjAzMTQgNDgwLjAwOSA4MS41ODM5IDQ3Ni4xNDggODUuOTAzN0M0NzIuMjg2IDkwLjIyMzUgNDcwLjM1NSA5OC4wMTIxIDQ3MC4zNTUgMTA5LjI3VjE2NC4zNDdINDQ1LjIyMlY1Ni4zNTI2SDQ2OC43ODVWNjguODIxQzQ3Mi41ODEgNjMuOTc3NyA0NzYuNzM3IDYwLjQ0MzMgNDgxLjI1MyA1OC4yMThDNDg1Ljc2OSA1NS45MjcyIDQ5MC44NzQgNTQuNzgxOCA0OTYuNTY4IDU0Ljc4MThWNzguMjQ2WiIgZmlsbD0iIzYzMUIzQSIvPgo8cGF0aCBkPSJNNTYwLjc3NiA3OC4yNDZDNTUxLjAyNCA3OS4wMzE0IDU0NC4yMTcgODEuNTgzOSA1NDAuMzU1IDg1LjkwMzdDNTM2LjQ5NCA5MC4yMjM1IDUzNC41NjMgOTguMDEyMSA1MzQuNTYzIDEwOS4yN1YxNjQuMzQ3SDUwOS40M1Y1Ni4zNTI2SDUzMi45OTJWNjguODIxQzUzNi43ODggNjMuOTc3NyA1NDAuOTQ0IDYwLjQ0MzMgNTQ1LjQ2IDU4LjIxOEM1NDkuOTc2IDU1LjkyNzIgNTU1LjA4MiA1NC43ODE4IDU2MC43NzYgNTQuNzgxOFY3OC4yNDZaIiBmaWxsPSIjNjMxQjNBIi8+CjxwYXRoIGQ9Ik02NTAuMDE4IDk4LjM3MjFDNjQ3Ljg1OCA5MS4xNzI1IDY0NC4yMjYgODUuNzA3NCA2MzkuMTIxIDgxLjk3NjdDNjM0LjA4MSA3OC4xODA1IDYyNy42OTkgNzYuMjgyNCA2MTkuOTc2IDc2LjI4MjRDNjEzLjMgNzYuMjgyNCA2MDcuMzExIDc4LjMxMTQgNjAyLjAxIDgyLjM2OTRDNTk2LjcwOCA4Ni40MjczIDU5My4xNDEgOTEuNzYxNiA1OTEuMzA5IDk4LjM3MjFINjUwLjAxOFpNNTkwLjQyNSAxMTguMzAyQzU5MS4yNzYgMTI2LjA5MSA1OTQuMzUyIDEzMi4yNDMgNTk5LjY1NCAxMzYuNzU5QzYwNS4wMjEgMTQxLjIxIDYxMS45MjYgMTQzLjQzNSA2MjAuMzY5IDE0My40MzVDNjI1Ljk5OCAxNDMuNDM1IDYzMS4wMzcgMTQyLjI1NyA2MzUuNDg4IDEzOS45MDFDNjQwLjAwNCAxMzcuNTQ0IDY0My41NzEgMTM0LjIzOSA2NDYuMTg5IDEyOS45ODVINjczLjI4NkM2NjguNzA0IDE0MS43NjYgNjYxLjgzMiAxNTAuOTI5IDY1Mi42NjkgMTU3LjQ3NEM2NDMuNTcxIDE2My45NTQgNjMzLjAzNCAxNjcuMTk0IDYyMS4wNTYgMTY3LjE5NEM2MTMuMDA2IDE2Ny4xOTQgNjA1LjU3NyAxNjUuNzg3IDU5OC43NyAxNjIuOTcyQzU5Mi4wMjkgMTYwLjA5MiA1ODUuOTc0IDE1NS44NzEgNTgwLjYwNyAxNTAuMzA3QzU3NS41MDIgMTQ1LjAwNiA1NzEuNTQyIDEzOC44ODYgNTY4LjcyOCAxMzEuOTQ4QzU2NS45MTQgMTI0Ljk0NSA1NjQuNTA2IDExNy43NzggNTY0LjUwNiAxMTAuNDQ4QzU2NC41MDYgMTAyLjkyMSA1NjUuNzgzIDk1Ljg1MjIgNTY4LjMzNSA4OS4yNDE3QzU3MC45NTMgODIuNTY1NyA1NzQuNzgyIDc2LjU3NyA1NzkuODIyIDcxLjI3NTRDNTg1LjMyIDY1LjQ1MDMgNTkxLjUzOCA2MC45NjY5IDU5OC40NzYgNTcuODI1M0M2MDUuNDEzIDU0LjY4MzYgNjEyLjU4IDUzLjExMjggNjE5Ljk3NiA1My4xMTI4QzYyOS4zMzYgNTMuMTEyOCA2MzguMDczIDU1LjI0IDY0Ni4xODkgNTkuNDk0M0M2NTQuMzA1IDYzLjc0ODYgNjYxLjIxIDY5LjczNzMgNjY2LjkwNCA3Ny40NjA1QzY3MC4zNzMgODIuMTA3NiA2NzIuOTI2IDg3LjMxMDkgNjc0LjU2MiA5My4wNzA2QzY3Ni4yNjQgOTguODMwMyA2NzcuMTE1IDEwNS40NDEgNjc3LjExNSAxMTIuOTAyQzY3Ny4xMTUgMTEzLjQ5MSA2NzcuMDgyIDExNC40MDggNjc3LjAxNyAxMTUuNjUxQzY3Ni45NTEgMTE2LjgyOSA2NzYuOTE4IDExNy43MTMgNjc2LjkxOCAxMTguMzAySDU5MC40MjVaIiBmaWxsPSIjNjMxQjNBIi8+CjxwYXRoIGQ9Ik03MTcuNDY1IDU2LjM1MjZWNjguNjI0N0M3MjEuMTMgNjMuNzE1OSA3MjUuMzE5IDYwLjA4MzMgNzMwLjAzMiA1Ny43MjcxQzczNC44MSA1NS4zNzA5IDc0MC4yNDIgNTQuMTkyOCA3NDYuMzI5IDU0LjE5MjhDNzU0LjExOCA1NC4xOTI4IDc2MC44OTIgNTUuNjY1NCA3NjYuNjUyIDU4LjYxMDdDNzcyLjQ3NyA2MS41NTYgNzc3LjMyIDY1Ljk3MzkgNzgxLjE4MiA3MS44NjQ1Qzc4My42NjkgNzUuNzkxNSA3ODUuNDM2IDgwLjI3NDkgNzg2LjQ4MyA4NS4zMTQ2Qzc4Ny41OTYgOTAuMjg4OSA3ODguMTUyIDk3LjU4NjcgNzg4LjE1MiAxMDcuMjA4VjE2NC4zNDdINzYzLjAxOVYxMTYuNTM1Qzc2My4wMTkgMTAyLjA3IDc2MS4zNSA5Mi4xNTQzIDc1OC4wMTIgODYuNzg3M0M3NTQuNjc0IDgxLjQyMDMgNzQ4LjkxNCA3OC43MzY4IDc0MC43MzMgNzguNzM2OEM3MzIuMzU1IDc4LjczNjggNzI2LjMzNCA4MS43MTQ4IDcyMi42NjkgODcuNjcwOUM3MTkuMDAzIDkzLjU2MTUgNzE3LjE3MSAxMDMuNzA2IDcxNy4xNzEgMTE4LjEwNlYxNjQuMzQ3SDY5Mi45MjFWNTYuMzUyNkg3MTcuNDY1WiIgZmlsbD0iIzYzMUIzQSIvPgo8cGF0aCBkPSJNODA1LjczMSAxNjQuMzQ3Vjc4LjczNjhWNTYuMzUyNlYyMS40MDE5SDgzMC44NjRWNTYuMzUyNkg4NTVWNzguNzM2OEg4MjMuMDMxTDgzMC44NjQgODkuODA0OFYxNjQuMzQ3SDgwNS43MzFaIiBmaWxsPSIjNjMxQjNBIi8+CjxyZWN0IHg9IjIyNi4zMTUiIHk9IjIxLjQwMTkiIHdpZHRoPSIyNC4xNDAyIiBoZWlnaHQ9IjE0My4zMzMiIGZpbGw9IiM2MzFCM0EiLz4KPHBhdGggZD0iTTI4MS45ODggMTA4LjA3OUwzMTkuMDU4IDU2LjQwMzZIMjkyLjA1MUwyNjguNDg0IDg5LjI2NDRMMjU0Ljk4MSAxMDguMDc5TDI2OC40ODQgMTI2Ljg5M0wyOTUuNDAxIDE2NC40MDFIMzIyLjQwN0wyODEuOTg4IDEwOC4wNzlaIiBmaWxsPSIjNjMxQjNBIi8+CjxkZWZzPgo8Y2xpcFBhdGggaWQ9ImNsaXAwXzYxMTVfNzgyNyI+CjxyZWN0IHdpZHRoPSIxODguNTk2IiBoZWlnaHQ9IjE5MC4xMDQiIGZpbGw9IndoaXRlIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDE4OC41OTUpIHJvdGF0ZSgtOTApIi8+CjwvY2xpcFBhdGg+CjwvZGVmcz4KPC9zdmc+Cg==
      mediatype: image/svg+xml
  relatedImages:
    - name: operator
      image: registry.connect.redhat.com/kurrent-io/kurrentdb-operator@sha256:9e10c1f7055fc5bbe8e4d8289b247389d337a77a27d56232022695405a10b980
    - name: dns
      image: registry.connect.redhat.com/kurrent-io/dns@sha256:07e8771886b4e4ab7393dee7a56c4a6d2c2225ba0aeca25e47199da616c903e4
    - name: kurrentdb
      image: registry.connect.redhat.com/kurrent-io/kurrentdb@sha256:4dc9fcb41de27695ba04731e768fb18cde2f1c7882f8787dfce3d32b93520131
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  customresourcedefinitions:
    owned:
      - kind: KurrentDB
        name: kurrentdbs.kubernetes.kurrent.io
        version: v1
        description: A declarative representation of a KurrentDB cluster.
        resources:
          - kind: ConfigMap
            version: v1
          - kind: Service
            version: v1
          - kind: StatefulSet
            version: v1
          - kind: Pod
            version: v1
          - kind: PersistentVolumeClaim
            version: v1
          - kind: PersistentVolume
            version: v1
          - kind: VolumeSnapshot
            name: snapshot.storage.k8s.io
            version: v1
      - kind: KurrentDBBackup
        name: kurrentdbbackups.kubernetes.kurrent.io
        version: v1
        description: A VolumeSnapshot-based backup of a KurrentDB cluster.
        resources:
          - kind: VolumeSnapshot
            name: snapshot.storage.k8s.io
            version: v1
      - kind: KurrentDBBackupSchedule
        name: kurrentdbbackupschedules.kubernetes.kurrent.io
        version: v1
        description: A schedule for creating and retaining of KurrentDBBackup resources.
        resources:
          - kind: KurrentDBBackup
            name: kurrentdbbackups.kubernetes.kurrent.io
            version: v1
          - kind: VolumeSnapshot
            name: snapshot.storage.k8s.io
            version: v1
  nativeApis:
    - kind: VolumeSnapshot
      group: snapshot.storage.k8s.io
      version: v1
    - kind: VolumeSnapshotClass
      group: snapshot.storage.k8s.io
      version: v1
  install:
    strategy: deployment
    spec:
      deployments:
        - labels:
            control-plane: controller-manager
            app.kubernetes.io/name: kurrentdb-operator
            app.kubernetes.io/instance: kurrentdb-operator
            app.kubernetes.io/component: kurrentdb-operator
            app.kubernetes.io/created-by: kurrent
            app.kubernetes.io/part-of: kurrentdb-operator
          name: kurrentdb-operator
          spec:
            strategy:
              type: Recreate
            selector:
              matchLabels:
                control-plane: controller-manager
            replicas: 1
            template:
              metadata:
                annotations:
                  app.kubernetes.io/release-timestamp: '20251223130302'
                  kubectl.kubernetes.io/default-container: controller
                labels:
                  control-plane: controller-manager
                  app.kubernetes.io/name: kurrentdb-operator
              spec:
                securityContext:
                  runAsNonRoot: true
                containers:
                  - command:
                      - /kurrentdb-operator
                    image: registry.connect.redhat.com/kurrent-io/kurrentdb-operator@sha256:9e10c1f7055fc5bbe8e4d8289b247389d337a77a27d56232022695405a10b980
                    name: controller
                    imagePullPolicy: IfNotPresent
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                    env:
                      - name: XDG_CONFIG_HOME
                        value: /tmp/workspace/helm/.config
                      - name: XDG_CACHE_HOME
                        value: /tmp/workspace/helm/.cache
                      - name: NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                    volumeMounts:
                      - name: config
                        mountPath: config.yaml
                        subPath: config.yaml
                      - name: workspace
                        mountPath: /tmp/workspace
                      - name: annos
                        mountPath: /etc/annos
                    ports:
                      - containerPort: 18080
                        name: http-web-svc
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        memory: 128Mi
                      requests:
                        cpu: 1000m
                        memory: 64Mi
                volumes:
                  - name: config
                    configMap:
                      defaultMode: 420
                      name: kurrentdb-operator
                  - name: workspace
                    emptyDir: {}
                  - name: annos
                    downwardAPI:
                      items:
                        - path: annos
                          fieldRef:
                            fieldPath: metadata.annotations
                serviceAccountName: kurrentdb-operator
                terminationGracePeriodSeconds: 10
                nodeSelector: null
                nodeName: null
                affinity: null
                schedulerName: null
                tolerations: null
                topologySpreadConstraints: null
                imagePullSecrets: null
      permissions:
        - serviceAccountName: kurrentdb-operator
          rules:
            - apiGroups:
                - ''
              resources:
                - configmaps
                - persistentvolumeclaims
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ''
              resources:
                - secrets
              verbs:
                - create
                - update
                - delete
                - get
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - snapshot.storage.k8s.io
              resources:
                - volumesnapshots
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - events.k8s.io
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - kubernetes.kurrent.io
              resources:
                - kurrentdbbackups
                - kurrentdbbackupschedules
                - kurrentdbs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - kubernetes.kurrent.io
              resources:
                - kurrentdbbackups/finalizers
                - kurrentdbbackupschedules/finalizers
                - kurrentdbs/finalizers
              verbs:
                - update
            - apiGroups:
                - kubernetes.kurrent.io
              resources:
                - kurrentdbbackups/status
                - kurrentdbbackupschedules/status
                - kurrentdbs/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - snapshot.storage.k8s.io
              resources:
                - volumesnapshotclasses
              verbs:
                - list
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
                - list
                - delete
                - update
                - patch
