---
apiVersion: v1
kind: ConfigMap
metadata:
  name: compat-matrix-config
  namespace: vmware-system-vdo
data:
  versionConfigURL: "https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/compatibility.yaml"
  auto-upgrade: "disabled"
