# Intel OBL Limited Distribution (Commercial Use) License Agreement [v2022.12.20]
# Copyright (c) 2025 Intel Corporation
apiVersion: v1
data:
  config.json: |
    {
      "global": {
        "core": 10,
        "active between": "00:00-00:00"
      }
    }
kind: ConfigMap
metadata:
  name: ipm-controller-ipm-agent-config
