# Intel OBL Limited Distribution (Commercial Use) License Agreement [v2022.12.20]
# Copyright (c) 2025 Intel Corporation
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ipm.intel.com/v1",
          "kind": "CPUPowerProv",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ipm-controller",
              "node-label": "ipm-provisioning"
            },
            "name": "cpupowerprov-sample"
          },
          "spec": {
            "cstates": {
              "cores": {
                "all": {
                  "C1": true,
                  "C6": true
                }
              },
              "idleGovernor": "menu"
            },
            "pstates": {
              "cores": {
                "all": {
                  "maxFreqMHz": "default",
                  "minFreqMHz": "default"
                }
              }
            },
            "uncoreFreqCPU": {
              "cpu0": [
                {
                  "maxFreqMHz": "auto",
                  "minFreqMHz": "auto"
                }
              ],
              "cpu1": [
                {
                  "maxFreqMHz": "auto",
                  "minFreqMHz": "auto"
                }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Networking, Monitoring
    certified: "false"
    containerImage: registry.connect.redhat.com/intel/ipm-controller@sha256:1d801cd8390b80ddd7b61274d89cf47a08f2c3fe920247f85db9cc7f364eacf7
    createdAt: "2025-12-10T10:23:24Z"
    description: IPM Controller manages resources via REST API interactions.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    olm.operatorframework.io/required-sccs: '["privileged"]'
    olm.securityContextConstraints.required: privileged
    operators.openshift.io/infrastructure-features: RestrictedNetwork
    operators.openshift.io/valid-subscription: Intel OBL Limited Distribution (Commercial Use) License Agreement [v2022.12.20]
    operators.operatorframework.io.bundle.package.v1: ipm-controller
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    support: Intel® Corporation
  name: ipm-controller.v25.11.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: CPUPowerProv is the Schema for the cpupowerprovs API
        displayName: CPUPower Prov
        kind: CPUPowerProv
        name: cpupowerprovs.ipm.intel.com
        resources:
          - kind: Deployment
            name: ""
            version: v1
          - kind: Pod
            name: ""
            version: v1
          - kind: ReplicaSet
            name: ""
            version: v1
          - kind: Service
            name: ""
            version: v1
        specDescriptors:
          - description: C-States configuration for CPU power management
            displayName: C-States Configuration
            path: cstates
          - description: P-States configuration for CPU power management
            displayName: P-States Configuration
            path: pstates
          - description: Uncore frequency configuration for CPU power management
            displayName: CPU Uncore Frequency
            path: uncoreFreqCPU
          - description: Uncore frequency configuration for IO power management
            displayName: IO Uncore Frequency
            path: uncoreFreqIO
        statusDescriptors:
          - description: Conditions represent the latest available observations of the CPUPowerProv state
            displayName: Conditions
            path: conditions
          - description: ObservedGeneration is the most recent generation observed for this CPUPowerProv
            displayName: Observed Generation
            path: observedGeneration
        version: v1
  description: Infrastructure Power Manager (IPM) governs platform power technologies based on input from application workloads, the platform itself and customer input
  displayName: Intel® Infrastructure Power Manager
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAEgAAAAeCAMAAAC45KifAAABwlBMVEUAAAAAAP8AgIAAVaoAgL8AZswAVaoAbbYAcaoAZrMAXbkAar8AYrEAZrsAcK8AabQAY7gAZrMAbbYAaLkAZLEAZrgAbLEAarkAZrMAaLcAargAZ7MAabcAarQAZ7YAa7gAaLQAZrUAabcAarUAaLYAZrMAabQAaLMAZrUAabYAZ7MAarQAaLYAZrcAabQAZ7UAabYAZ7cAabQAZ7UAaLQAZ7UAabYAabQAZ7UAabYAaLMAZ7QAaLUAZ7YAabQAaLQAZ7YAabQAabUAaLYAabUAabQAaLUAaLYAZ7QAabUAaLYAZ7QAaLUAabQAaLYAZ7QAaLYAZ7UAaLYAZ7UAaLYAaLQAabYAaLUAZ7QAaLQAaLQAZ7YAaLQAaLQAaLYAabUAaLUAZ7UAaLQAaLUAaLUAaLYAabUAZ7UAaLQAaLUAabUAaLYAaLUAaLQAaLUAaLUAabQAaLUAaLUAabUAaLUAaLUAaLUAaLYAaLUAaLUAaLUAaLUAZ7UAaLUAaLUAabUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAabUAaLUAaLUAaLUAaLUAaLUAaLUAaLUAaLX////ygXFuAAAAlHRSTlMAAQIDBAUGBwkKCwwNDxAREhQVFhcZGh0eICQlJykqKywtLjAxMjM2Nzg5Ojs8PT4/Q0RFR0hJS09QUVJTVFVYXl9hYmRmZ2lqa2xtbnBzdHZ5fYOEhYuOj5OWmZqdoKGio6Slpqqtr7W2t7i6vL3Cw8XHyMnKzM3O0tfY2drd3t/h4ubn6Onq6+7x8vT29/j6/P3+PHdbFQAAAAFiS0dElQhgeoMAAAHvSURBVEjH1ZblW8JQFMaviAoG2N2KAVizu1tsxe5ObAzswkCR+wd7z9jGrE2UD/p+Oe+J/Z7tufduQ+gvKIeiqCQuS7ggmv8RyIoxXuCyFJJhw+eTecdE5S4AlUKv5t+CJH5E3i4ACelXIGk8lRH+FShYTamUX4CUZqIhhIYgusv7ruHiwwYpB3owm1foSS+dEXLrRrX7ZyB/aI4hNAYx7AAzWvJhQUSbMJh2yvawMUIMxHEwnnoHKrQ4evgqSgREZNq9tRvNG1DsPRjLztoRXdmXiYCMiWRDVNyBHWdAzUqlL0KrxD13wfNGL0K1XRh0qqBrlbTnr5oGXC2z8wB6KREEtTKjN8TbPHggPTF77CWxUE4XBMUxRQMkgTzQFtziLKsXkrUIghRMcQaSUB7oDL9XryBIzhQnxUF6Z0BFEOqgsA3bfZivCmdAuRA6oDBAzLVM8NAKgVQQpqGQBW6Q6ZZ1S5wEyWF5XkaqsxFah8qcivRSp2x4OcA5kH0b0Eck8YF2lpNHOp5HO0DhBcGioGLHoS154q/ZtJQDBTRVtcnEQKjHxr1G1Mcc5r5Z4ng0df5EZiTJFPDt6keoHyK7LnpIgsBpx01WOwh5Nhqs9MnvDLFPmcjQKJLq6nVu3/ui+vhyLkabrPjQ93Tlf8ArTI/G7cs88xAAAAAASUVORK5CYII=
      mediatype: image/png
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ipm.intel.com
              resources:
                - cpupowerprovs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ipm.intel.com
              resources:
                - cpupowerprovs/finalizers
              verbs:
                - update
            - apiGroups:
                - ipm.intel.com
              resources:
                - cpupowerprovs/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - list
                - get
                - watch
                - patch
                - update
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - pods
                - pods/status
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
          serviceAccountName: ipm-controller-controller-manager
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: ipm-controller
            control-plane: controller-manager
          name: ipm-controller-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --secure-listen-address=0.0.0.0:8443
                      - --upstream=http://127.0.0.1:8080/
                      - --logtostderr=true
                      - --v=0
                    image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.13.0@sha256:471549d9cc07fcec0f285a05745b3d39a48e9a503b01b4047156a86ec1a30c00
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 5m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                  - args:
                      - --health-probe-bind-address=:8081
                      - --metrics-bind-address=127.0.0.1:8080
                      - --zap-log-level=error
                    command:
                      - sh
                      - -c
                      - until curl -X GET -sf -o /dev/null http://localhost:32100/global/status --http2-prior-knowledge; do echo "Waiting for agent . . ."; sleep 2; done; /manager
                    env:
                      - name: NODE_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
                      - name: AGENT_ADDRESS
                        value: http://localhost
                      - name: AGENT_PORT
                        value: "32100"
                      - name: AGENT_CERT
                      - name: AGENT_KEY
                      - name: AGENT_CA
                      - name: AGENT_DIAL_TIMEOUT
                        value: "5"
                      - name: AGENT_CLIENT_TIMEOUT
                        value: "10"
                    image: registry.connect.redhat.com/intel/ipm-controller@sha256:1d801cd8390b80ddd7b61274d89cf47a08f2c3fe920247f85db9cc7f364eacf7
                    imagePullPolicy: Always
                    livenessProbe:
                      exec:
                        command:
                          - sh
                          - -c
                          - (find /tmp/ipm/ -iname ipm-agent.heartbeat -newermt '-15 seconds' | grep  ipm-agent.heartbeat) && (find /tmp/ipm/ -iname ipm-agent.pid -not -newermt '-15 seconds' | grep  ipm-agent.pid) && curl -f http://localhost:8081/healthz
                      initialDelaySeconds: 15
                      periodSeconds: 5
                    name: ipm-controller
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                    volumeMounts:
                      - mountPath: /etc/certs/ipm/
                        name: certs
                      - mountPath: /tmp/ipm/
                        name: heartbeat
                  - command:
                      - /opt/ipm-agent/ipm-agent
                      - -c
                      - /opt/ipm-agent/config/config.json
                      - -p
                      - "32100"
                      - -l
                      - none
                    image: registry.connect.redhat.com/intel/ipm-agent@sha256:0cbe0a21911db60b6aedfeb7b0aa941dd532fdbee2029f9ae4a932f456ffe96f
                    imagePullPolicy: Always
                    livenessProbe:
                      exec:
                        command:
                          - sh
                          - -c
                          - find /var/run/ -iname ipm-agent.heartbeat -newermt '-15 seconds' | grep  ipm-agent.heartbeat
                      initialDelaySeconds: 15
                      periodSeconds: 5
                    name: ipm-agent
                    resources:
                      limits:
                        cpu: "1"
                        memory: 200Mi
                      requests:
                        cpu: "1"
                        memory: 100Mi
                    securityContext:
                      allowPrivilegeEscalation: true
                      privileged: true
                      runAsUser: 0
                    volumeMounts:
                      - mountPath: /sys/devices
                        name: host-devices
                      - mountPath: /var/run/dpdk
                        name: host-run
                      - mountPath: /var/run/vpp
                        name: host-run-vpp
                      - mountPath: /dev/cpu
                        name: cpu-msr
                      - mountPath: /opt/ipm-agent/config/
                        name: ipm-agent-config
                        readOnly: true
                      - mountPath: /etc/certs/ipm/
                        name: certs
                      - mountPath: /var/run/
                        name: heartbeat
                  - command:
                      - sh
                      - -c
                      - until curl -X GET -sf -o /dev/null http://localhost:32100/global/status --http2-prior-knowledge; do echo "Waiting for agent . . ."; sleep 2; done; /opt/ipm-watcher/ipm-watcher --p 32100
                    env:
                      - name: MY_NODE_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: spec.nodeName
                    image: registry.connect.redhat.com/intel/ipm-watcher@sha256:564ece52e7effefe7d090db4dcb68aee3482cd840f740f6b48033f8d2036a9bc
                    imagePullPolicy: Always
                    name: ipm-watcher
                    resources:
                      limits:
                        cpu: 200m
                        memory: 60Mi
                      requests:
                        cpu: 100m
                        memory: 30Mi
                    volumeMounts:
                      - mountPath: /etc/certs/ipm
                        name: certs
                        readOnly: true
                securityContext:
                  runAsNonRoot: false
                serviceAccountName: ipm-controller-controller-manager
                terminationGracePeriodSeconds: 10
                topologySpreadConstraints:
                  - labelSelector:
                      matchLabels:
                        control-plane: controller-manager
                    maxSkew: 1
                    topologyKey: kubernetes.io/hostname
                    whenUnsatisfiable: DoNotSchedule
                volumes:
                  - hostPath:
                      path: /sys/devices
                      type: Directory
                    name: host-devices
                  - hostPath:
                      path: /var/run/dpdk
                      type: DirectoryOrCreate
                    name: host-run
                  - hostPath:
                      path: /var/run/vpp
                      type: DirectoryOrCreate
                    name: host-run-vpp
                  - hostPath:
                      path: /dev/cpu
                      type: Directory
                    name: cpu-msr
                  - configMap:
                      name: ipm-controller-ipm-agent-config
                    name: ipm-agent-config
                  - hostPath:
                      path: /etc/certs/ipm/
                    name: certs
                  - emptyDir: {}
                    name: heartbeat
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - privileged
              resources:
                - securitycontextconstraints
              verbs:
                - use
          serviceAccountName: ipm-controller-controller-manager
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: true
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - intel
    - infrastructure
    - power
    - manager
    - management
  links:
    - name: IPM
      url: https://builders.intel.com/intel-technologies/power-management
  maintainers:
    - email: infrastructure.power.manager.operator@intel.com
      name: Infrastructure Power Manager Operator
  maturity: stable
  minKubeVersion: 1.29.0
  provider:
    name: Intel® Corporation
    url: https://www.intel.com
  relatedImages:
    - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.13.0@sha256:471549d9cc07fcec0f285a05745b3d39a48e9a503b01b4047156a86ec1a30c00
      name: kube-rbac-proxy
    - image: registry.connect.redhat.com/intel/ipm-controller@sha256:1d801cd8390b80ddd7b61274d89cf47a08f2c3fe920247f85db9cc7f364eacf7
      name: ipm-controller
    - image: registry.connect.redhat.com/intel/ipm-agent@sha256:0cbe0a21911db60b6aedfeb7b0aa941dd532fdbee2029f9ae4a932f456ffe96f
      name: ipm-agent
    - image: registry.connect.redhat.com/intel/ipm-watcher@sha256:564ece52e7effefe7d090db4dcb68aee3482cd840f740f6b48033f8d2036a9bc
      name: ipm-watcher
    - image: registry.connect.redhat.com/intel/ipm-controller@sha256:1d801cd8390b80ddd7b61274d89cf47a08f2c3fe920247f85db9cc7f364eacf7
      name: ipm-controller-1d801cd8390b80ddd7b61274d89cf47a08f2c3fe920247f85db9cc7f364eacf7-annotation
  version: 25.11.0
