apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: resourcesupervisors.tenantoperator.stakater.com
spec:
  group: tenantoperator.stakater.com
  names:
    kind: ResourceSupervisor
    listKind: ResourceSupervisorList
    plural: resourcesupervisors
    singular: resourcesupervisor
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ResourceSupervisor is the Schema for the resourcesupervisors
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ResourceSupervisorSpec defines the desired state of ResourceSupervisor
            properties:
              argocd:
                description: ArgoCD contains details about ArgoCD to add Hibernation
                  schedule to it
                properties:
                  appProjects:
                    description: AppProjects lists the ArgoCD AppProjects that will
                      follow the Hibernation schedule for this resource
                    items:
                      type: string
                    type: array
                  namespace:
                    description: Namespace is the ArgoCD namespace where the AppProjects
                      are residing in
                    type: string
                required:
                - appProjects
                - namespace
                type: object
              hibernation:
                description: Hibernation contains the schedule during which the tenant
                  will be sleeping
                properties:
                  sleepSchedule:
                    description: SleepSchedule contains the schedule during which
                      the resources within the tenant's namespaces will be put to
                      sleep
                    type: string
                  wakeSchedule:
                    description: WakeSchedule contains the schedule during which the
                      resources within the tenant's namespaces will be awoken
                    type: string
                required:
                - sleepSchedule
                - wakeSchedule
                type: object
            required:
            - hibernation
            type: object
          status:
            description: ResourceSupervisorStatus defines the observed state of ResourceSupervisor
            properties:
              currentStatus:
                description: CurrentStatus shows the state the tenant's resources
                enum:
                - sleeping
                - running
                - error
                type: string
              nextReconcileTime:
                description: NextReconcileTime contains the next time at which the
                  namespace resources will sleep or wake up
                format: date-time
                type: string
              sleepingApplications:
                description: SleepingApplications contains the previous states for
                  each of the deployments currently scaled down
                items:
                  description: SleepingApplication contains the previous states for
                    the deployments or stateful sets currently scaled down
                  properties:
                    Namespace:
                      description: Namespace is the namespace that contains the application
                      type: string
                    kind:
                      description: Kind stores the application's kind (Deployment
                        or StatefulSet)
                      enum:
                      - Deployment
                      - StatefulSet
                      type: string
                    name:
                      description: Name is the name of the sleeping application
                      type: string
                    replicas:
                      description: Replicas are the number of desired pods for the
                        deployment, stored at the time of sleep
                      format: int32
                      type: integer
                  required:
                  - Namespace
                  - kind
                  - name
                  - replicas
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
