apiVersion: v1
data:
  properties.yaml: "version: 0.1.0\nspec:\n  units: []\nproperties:\n  - property:\
    \ &credentialsSecret\n      propertyNames:\n        - name: \"credentialsSecret\"\
    \n          kind:\n            type: \"env\"\n      datatype:\n        type: \"\
    string\"\n      roles:\n        - name: \"node\"\n          required: true\n \
    \     asOfVersion: \"0.0.0\"\n      description: \"The secret where the Airflow\
    \ credentials are stored.\"\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: airflow-operator
    app.kubernetes.io/name: airflow-operator
    app.kubernetes.io/version: 25.11.0
    stackable.tech/vendor: Stackable
  name: airflow-operator-configmap
